### ISSUE TITLE
Currently armed sensors

### ISSUE THREAD

**Issue by apocaliss92** [nielsfaber/alarmo#1022]
Would it be possible to include in the alarmo entity attributes the sensors currently harmed? Basically the on configured for the current active mode
I would need this to filter out some notifications from an external security system

**Comment by masi** [comment]
You mean armed?

Anyway, I'd appreciate attributes that list alls sensors, sensors for each mode and sensors for the active mode (reqeuest of @apocaliss92 ).

My use-case is that I specifically want to check the availability of the security devices. My work-around is to duplicate the sensor list. But this is error-prone when I add or replace a device.

**Comment by apocaliss92** [comment]
Yes sorry, armed, bad English :)

**Comment by apocaliss92** [comment]
I could implement this already on my local folder, not a complicated exercise, I will try to open a pr during next week

**Comment by apocaliss92** [comment]
@nielsfaber I have some changes prepared to propose in a PR, is it possible to have permissions or should I just fork the project?

**Comment by apocaliss92** [comment]
nevermind, got it working

**Comment by nielsfaber** [comment]
I agree it can be useful that users have access to the list of sensors configured in alarmo.
However, I don't agree that this should be added as an attribute, since this can be a lot of information and it would become a long and unreadable list. 
I think we should look for another way to share the information, for example via a service or event.
Also, we should discuss what information is shared, since as @masi already points out, some users may want to access the full sensor list rather than only the currently armed sensors, so I would prefer to implement a generic approach that cover multiple use-cases.

**Comment by apocaliss92** [comment]
This was the easiest for me with my limited py skills
I believe a proper sensor for each of the "combinations" would be the best. Since mqtt is very easy to extend, what about having 1 for each of the lists under the same topic?
