### ISSUE TITLE
Exclude sensor from arming prevention mechanism

### ISSUE THREAD

**Issue by bobvmierlo** [nielsfaber/alarmo#103]
Hi Niels,

Is there any possibility to exclude a sensor from preventing an arming action?
For example if my waterleak sensor somehow lost the connection to HA and still want the alarm to arm, exclude that sensor from blocking the arming action.

I know I can get the notification with the force arm action, but I would rather not get this notification for configured sensors.

**Comment by nielsfaber** [comment]
Hi Bob,

If you keep this setting OFF, the sensor should not trigger or block arming when it has state `unavailable` or `unknown`
![image](https://user-images.githubusercontent.com/16861605/105493453-b593ce80-5cb9-11eb-981e-1783e5e58d25.png)

Otherwise there is no functionality to "automatically bypass" sensors.
With this the security of your house becomes a bit questionable, I rather have the user confirm (every time) that they are OK with bypassing sensors.

**Comment by bobvmierlo** [comment]
Thanks that'll help!
