### ISSUE TITLE
Arm after closing

### ISSUE THREAD

**Issue by quentindavid** [nielsfaber/alarmo#1034]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.9.2

### Bug description

I am wondering if the "arm after closing" is working as it should. For me, when arming the alarm, the exit delay is starting. Once you open the door configured with "arm after closing" setting, and then close it, it should cancel the delay and arm the alarm.
On my side I think it work, except the exit delay continue decreasing on the lovelace dashboard. 
If I open the door though, it start the entry delay (that's why I think in fact the alarm is armed).

Is it a normal behaviour ?

I would expect to see on the dashboard the alarm is armed after closing the door.

### Steps to reproduce

Configure a sensor with 'door' type with the following options:
- Use an entry delay
- Use an exit delay
- Arm after closing

**Comment by quentindavid** [comment]
I think I understand the behaviour now after some digging, I have configured two sensors with the option "Arm after closing", and in fact it arms after all the sensors have been triggered opened and closed.
Is seems logical when  you know it but could you confirm it is n purpose ? If so maybe we could add this information within the docs ? I could propose an update of the doc when I'm sure about the expected behaviour.

**Comment by nielsfaber** [comment]
When the alarm is arming, closing of a door sensor with 'arm after closing' setting applied will cause the remainder of the exit delay to be skipped.
The alarm will then proceed to armed state, but this can only succeed if all doors/windows are closed (otherwise arming fails).
It is possible to apply the setting on multiple doors, but bear in mind that only one door should be opened+closed during the exit delay (otherwise closing of the first door will cause the arming to fail due to the second door being still open).

**Comment by quentindavid** [comment]
hi @nielsfaber , thanks for the feedback but it's not what I observe. I configured my main door and my portal gate with "Arm after closing", and when I exit the house by the main door, the delay is still decreasing, alarm is not armed. But once I open my portal gate, as soon as it closes the delay is terminated and the alarm is armed.

**Comment by nielsfaber** [comment]
Perhaps you observe different behaviour due to your own settings.
I just tested it and works as it should for me.

**Front door settings:**
<img src="https://github.com/user-attachments/assets/57a100c5-690e-447c-aaf4-c23c13666978" width="50%" height="50%">

**Back door settings:**
<img src="https://github.com/user-attachments/assets/4ed999ca-0e9b-4aaf-8c47-91d421d72cac" width="50%" height="50%">

**Demonstration:**
https://github.com/user-attachments/assets/39e27985-aa70-4060-a90c-52d2edb26178

As you can see in the video, opening+closing of the back door to causes the alarm to arm. I don't have to do any thing with the front door.

Note that there is a delay of approx 5 seconds noticeable, this is done intentionally to wait for the sensor signal to be stable (closing of a heavy door can cause the sensor to trigger multiple times).

**Comment by quentindavid** [comment]
Maybe I think I know what is going on. I have different zones. One for Sensors inside the hosue, and one for sensors outside. Those two zones have different delays (1.5min for inside sensors and 5min for outside).

When I arm alarm using "master" zone, I think it trigger two delays at the same time, and in fact on the dashboard I see the two delays mixed up, so when I exit the house it must arm the "inside" zone only, but delay for outside continues.

I will double check this asap ! Thanks for your help and for that amazing work on Alarmo
