### ISSUE TITLE
Compact Header?

### ISSUE THREAD

**Issue by luckypants123** [nielsfaber/alarmo#110]
Not really a big issue - just noticed that the header is the older, non compact style vs the rest of the UI.
1.5.0 looks great btw!

**Comment by stefanolson** [comment]
I assume that's because there are tabs at the top in that header. Looks okay to me.

**Comment by nielsfaber** [comment]
Not sure if I understand the request.

Alarmo header:
![image](https://user-images.githubusercontent.com/16861605/106108012-f7a09280-6147-11eb-9fae-421347218564.png)

Dev tools header:
![image](https://user-images.githubusercontent.com/16861605/106107887-c6c05d80-6147-11eb-91bb-567ab905d8a6.png)

I see some differences:
1. Alarmo header has 8 pixels more in height
2. Title is a bit more to the left
3. Tabs menu is a bit more to the right
4. There is no white bar under the selected tab

I don't really know what causes these differences (they are not intentional, I tried to make a copy-exact), but they are also pretty minor IMO.
@luckypants123 are these the differences you are referring to?

**Comment by luckypants123** [comment]
Ah yes sorry, I wasn't very clear. 
I had assumed that the Alarmo header would follow the compact header styling of dashboard tabs rather than that of developer tools. No biggie. Perhaps just due to the default placement of the add-on in the sidebar made me think it should conform to that UI style.
