### ISSUE TITLE
Have "Allow Open" as an option on door sensors (Feature Request)

### ISSUE THREAD

**Issue by danps1** [nielsfaber/alarmo#121]
Scenario: I have a bunch of door sensors that are used on internal doors within my house, and not many motion sensors. I use these primarily for automation triggers such as lights on off, etc. I'd like to use any status change on these to trigger Alarmo, however currently if I add these sensors to Alarmo, I need to have all internal doors within my house to be closed before leaving otherwise Alarmo will not arm.
Feature Request: Have an option on the door sensor to "Allow Open" for arming. Default should be "no" as current functionality.
Thanks!

**Comment by nielsfaber** [comment]
I think it’s best if Alarmo just treats these interior doors as motion/presence sensors.
It seems to give you the behavior you are looking for, since they would also automatically not be active in armed_home (a normal door sensor would).
See the table here regarding the differences between the types:
https://github.com/nielsfaber/alarmo#sensor-types

**Comment by danps1** [comment]
Thanks @nielsfaber - I'll give that a go and report back.

**Comment by danps1** [comment]
Seems to be working great - thanks @nielsfaber and also thanks for a great add-on - I really love Alarmo!
