### ISSUE TITLE
Allow adding of "cover" as a door sensor (feature request)

### ISSUE THREAD

**Issue by danps1** [nielsfaber/alarmo#124]
I have a garage door opener, implemented in HA as "cover" and would like to add it to Alarmo as a Door sensor.
Of course it's state is not purely binary, as it can be "opening", "closing", etc as well as "open" and "closed" but my thinking is that Alarmo could use "closed" and anything else as "open"
I know I could derive a binary_sensor in HA using a template, but it certainly would be neater if Alarmo natively supported Garage Doors.
Thanks!

**Comment by nielsfaber** [comment]
A `cover`  is an actuator and not a sensor.
You will have to create a template binary_sensor for mapping the state to a sensor.
I understand that it would be preferrable to have covers directly integrated in Alarmo, but you already gave a good reason for not wanting it.
Some users asked the same question regarding adding the support for `sensor` entities, it would create a lot of difficulties since the mapping to safe/unsafe conditions becomes non-trivial.
I prefer to limit Alarmo to binary sensors only to avoid such complexities. Hope you can live with this 👍

**Comment by danps1** [comment]
Fair enough! Easy enough to create the ```binary_sensor```
