### ISSUE TITLE
User Management now very slow

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#14]
After the change to the new model trying to add users is now very slow.  Not sure if there's anything that can be done about it but I thought I would just note it. I ended up pressing save twice and saving the new user twice

**Comment by xhemp** [comment]
This is also happening with editing the alarm sensors, takes around 20 seconds to open the edit screen after clicking on it.

**Comment by nielsfaber** [comment]
I'm surprised I haven't seen this behaviour while working on it.
Now i see it happening as well.

I took care of this, will release a fix soon.
Hitting F5 will help in the meantime..

**Comment by nielsfaber** [comment]
Please update to V1.1.1 and test if it solves the problem.
If so, you can close the issue.

Note: in the top right corner (next to the "Alarm panel" title), a version number is displayed (new since v1.1.1).
Check if it shows v1.1.1 after updating. There are often issues here due to browser-cache, I cannot really help with that (its done by HA).

**Comment by stefanolson** [comment]
Seems much better. Thanks.
