### ISSUE TITLE
Alarmo changed to armed when restarting HomeAssistant

### ISSUE THREAD

**Issue by sindudas** [nielsfaber/alarmo#145]
I don't know exactly why, if I miss something. But when doing a Home Assistant restart to apply some config changes, and when it started again Alarmo changed to Pending. And then to armed, and triggered when a sensor triggers the alarm.
It's normal behaviour or I'm doing something wrong?

**Comment by nielsfaber** [comment]
Alarmo is supposed to restore its previous state, so it sounds like something is going wrong.
I must say there is some difficult code in there, because sensors might not be available immediately after restart and Alarmo needs to wait for them to be initialised.

Could you enable debug logging for Alarmo?
This way we could trace back what happens in your situation.

You can do so by add something like this to the configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.alarmo: debug
```
Please post your findings next time it happens.

**Comment by nelsonamen** [comment]
There is problem when the alarm fail to arm then if you restart Homeassistant alarmo arm again

**Comment by sindudas** [comment]
Tried to Arm with one door opened. Failed to arm. Then restart home assistant, first time no issue. Restart again, and alarmo tried to Arm again.

Here is the debug from second restart:

> 2021-03-05 11:17:33 DEBUG (MainThread) [custom_components.alarmo.mqtt] MQTT config was (re)loaded
> 2021-03-05 11:17:33 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_control_panel.planta_baja is added to hass
> 2021-03-05 11:17:33 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] Initial state is disarmed
> 2021-03-05 11:17:33 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] Waiting for all sensors to be ready...
> 2021-03-05 11:17:33 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_control_panel.primera_planta is added to hass
> 2021-03-05 11:17:33 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] Initial state is disarmed
> 2021-03-05 11:17:33 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] Waiting for all sensors to be ready...
> 2021-03-05 11:17:33 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_control_panel.jardin is added to hass
> 2021-03-05 11:17:33 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] Initial state is disarmed
> 2021-03-05 11:17:33 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.jardin was updated from None to disarmed
> 2021-03-05 11:17:33 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_control_panel.master is added to hass
> 2021-03-05 11:17:40 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.livingroomdoor_contact changed: old_state=unknown, new_state=closed
> 2021-03-05 11:17:40 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.kitchensmoke_smoke changed: old_state=unknown, new_state=closed
> 2021-03-05 11:17:40 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.livingroomwindowsensor_contact changed: old_state=unknown, new_state=closed
> 2021-03-05 11:17:40 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.maindoor_contact changed: old_state=unknown, new_state=closed
> 2021-03-05 11:17:40 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.kitchenwindowsensor_contact changed: old_state=unknown, new_state=closed
> 2021-03-05 11:17:40 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.officewindow_contact changed: old_state=unknown, new_state=closed
> 2021-03-05 11:17:40 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.garagesmoke_smoke changed: old_state=unknown, new_state=closed
> 2021-03-05 11:18:03 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Not all sensors are initialized yet, starting anyway.
> 2021-03-05 11:18:03 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Alarm is now armed (armed_away).
> 2021-03-05 11:18:03 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.planta_baja was updated from None to armed_away
> 2021-03-05 11:18:03 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Not all sensors are initialized yet, starting anyway.
> 2021-03-05 11:18:03 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Alarm is now armed (armed_away).
> 2021-03-05 11:18:03 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.primera_planta was updated from None to armed_away
> 2021-03-05 11:18:25 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.shelly_shdw_1_f02fa2_door_window changed: old_state=unknown, new_state=closed
> 2021-03-05 11:18:25 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.shelly_shwt_1_b050fd_flood changed: old_state=unknown, new_state=closed
> 2021-03-05 11:18:25 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.shelly_shdw_2_483fda81f255_door_window changed: old_state=unknown, new_state=closed
> 2021-03-05 11:18:25 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.shelly_shdw_2_483fda81f16f_door_window changed: old_state=unknown, new_state=closed
> 2021-03-05 11:18:25 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.shelly_shdw_1_f03338_door_window changed: old_state=unknown, new_state=open
> 2021-03-05 11:18:25 DEBUG (MainThread) [custom_components.alarmo.sensors] Alarm is triggered due to sensor: binary_sensor.shelly_shdw_1_f03338_door_window
> 2021-03-05 11:18:25 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.planta_baja was updated from armed_away to pending
> 2021-03-05 11:18:25 DEBUG (MainThread) [custom_components.alarmo.automations] state of alarm_control_panel.planta_baja is updated from armed_away to pending
> 2021-03-05 11:18:25 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.master was updated from disarmed to pending
> 2021-03-05 11:18:25 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: default_config, homekit, transmission, met, unifiprotect
> 2021-03-05 11:18:25 DEBUG (MainThread) [custom_components.alarmo.automations] state of alarm_control_panel.master is updated from disarmed to pending
> 2021-03-05 11:18:28 DEBUG (MainThread) [custom_components.alarmo.sensors] entity binary_sensor.shelly_shgs_1_500291c3a904_gas changed: old_state=unknown, new_state=unavailable
> 2021-03-05 11:18:28 DEBUG (MainThread) [custom_components.alarmo.sensors] Entity binary_sensor.shelly_shgs_1_500291c3a904_gas should not trigger on unavailable state, ignoring
> 2021-03-05 11:18:45 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] async_entry_timer_finished
> 2021-03-05 11:18:45 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.planta_baja was updated from pending to triggered
> 2021-03-05 11:18:45 DEBUG (MainThread) [custom_components.alarmo.automations] state of alarm_control_panel.planta_baja is updated from pending to triggered
> 2021-03-05 11:18:45 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.master was updated from pending to triggered
> 2021-03-05 11:18:45 DEBUG (MainThread) [custom_components.alarmo.automations] state of alarm_control_panel.master is updated from pending to triggered
> 2021-03-05 11:18:45 DEBUG (MainThread) [custom_components.alarmo.automations] executing automation 1612608352
> 2021-03-05 11:19:23 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_disarm
> 2021-03-05 11:19:24 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_disarm
> 2021-03-05 11:19:24 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.planta_baja was updated from triggered to disarmed
> 2021-03-05 11:19:24 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_disarm
> 2021-03-05 11:19:25 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.primera_planta was updated from armed_away to disarmed
> 2021-03-05 11:19:25 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_disarm
> 2021-03-05 11:19:25 WARNING (MainThread) [custom_components.alarmo.alarm_control_panel] Cannot go to state disarmed from state disarmed.
> 2021-03-05 11:19:25 DEBUG (MainThread) [custom_components.alarmo.automations] state of alarm_control_panel.planta_baja is updated from triggered to disarmed
> 2021-03-05 11:19:25 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.master was updated from triggered to disarmed
> 2021-03-05 11:19:25 DEBUG (MainThread) [custom_components.alarmo.automations] state of alarm_control_panel.primera_planta is updated from armed_away to disarmed
> 2021-03-05 11:19:25 DEBUG (MainThread) [custom_components.alarmo.automations] state of alarm_control_panel.master is updated from triggered to disarmed

**Comment by nielsfaber** [comment]
This line provides a good clue:
> 2021-03-05 11:18:03 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Not all sensors are initialized yet, starting anyway.

It suggests that Alarmo was unable to start properly since there are sensors which remain in undefined state for too long (more than 30 seconds).
Does this sound familiar to you?

Besides this, I also see an issue in the Alarmo code that may lead to the starting in the wrong state (armed instead of disarmed).
I will update this code, hopefully it resolves the problem for you.

**Comment by nelsonamen** [comment]
👍

**Comment by sindudas** [comment]
> This line provides a good clue:
> 
> > 2021-03-05 11:18:03 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Not all sensors are initialized yet, starting anyway.
> 
> It suggests that Alarmo was unable to start properly since there are sensors which remain in undefined state for too long (more than 30 seconds).
> Does this sound familiar to you?
> 
The only sensor unavailable showed on the log, Alarmo says ignoring it. It should not be a problem, correct? It there's another sensor undefined, shouldn't it show up in the log?

> Besides this, I also see an issue in the Alarmo code that may lead to the starting in the wrong state (armed instead of disarmed).
> I will update this code, hopefully it resolves the problem for you.

Great! Will update and test it when available. Fast for me to test with some restart

**Comment by mariocao** [comment]
> There is problem when the alarm fail to arm then if you restart Homeassistant alarmo arm again

That's exactly what happened to me as well. Without going too deep into the code, I think that adding an additional condition `and not self.open_sensors` to the `async_added_to_hass` functions in `alarm_control_panel.py` should fix it:

```python
         _LOGGER.debug("Initial state is {}".format(initial_state))
        if initial_state == STATE_ALARM_TRIGGERED:
            await self.async_trigger(skip_delay=True)
        elif not self.hass.data[const.DOMAIN]["sensor_handler"].all_sensors_available_for_alarm(
            self.area_id,
            initial_state
        ):
            _LOGGER.debug("Waiting for all sensors to be ready...")

            @callback
            async def async_initialization_timer_finished(now):
                """Update state at a scheduled point in time."""
                _LOGGER.info("Not all sensors are initialized yet, starting anyway.")
                if self.arm_mode and not self.open_sensors:
                    await self.async_arm(self.arm_mode)
                else:
                    await self.async_update_state(STATE_ALARM_DISARMED)

            self.async_set_timer(const.INITIALIZATION_TIME, async_initialization_timer_finished)
        elif initial_state in ARM_MODES and not self.open_sensors:
            await self.async_arm(self._arm_mode)
        else:
            await self.async_update_state(STATE_ALARM_DISARMED)

        self.async_write_ha_state()
```

It seems to work, but I am not completely sure that I am not breaking any other thing. :sweat_smile: 
If you think it the correct solution, I wouldn't mind creating a pull request.

Btw, thanks very much for the project! It helped me a lot with some automations (especially with the notifications!). :clap:

**Comment by nielsfaber** [comment]
> That's exactly what happened to me as well. Without going too deep into the code, I think that adding an additional condition and not self.open_sensors to the async_added_to_hass functions in alarm_control_panel.py should fix it:

The `self.async_arm` function checks all conditions prior to arming, so it would not arm your system if there are sensors preventing this. 
Therefor I don't think your proposed change is an improvement, in fact it's rather dangerous as the `self.open_sensors` property may be outdated (so the system might disarm itself after restarting HA due to making false decisions).

If you want to help solving this issue, please update to v1.5.5, enable debug logging (see my earlier post) and share a log file covering the moment where alarmo starts up in the wrong state.
I cannot reproduce the scenario that you're experiencing, so I rely on your input for solving this case.

**Comment by mariocao** [comment]
The proposed change was inside the `async_added_to_hass` function that I thought it was only invoked after a restart (I read it from [here](https://developers.home-assistant.io/docs/core/entity/). Maybe my assumption was wrong :sweat_smile:

The way to reproduce the problem is the following (I always had the version v1.5.5):

1. Open a contact sensor (e.g. a door)
2. Arm the alarm (e.g. in arm home)
3. The arming process fails because there is an open sensor
4. The home alarm stays as DISARMED
5. I restart the Home Assistant
6. It will restart and will arm the alarm as ARMED_HOME

Here there are the logs from step 1 to step 3:

```
2021-04-06 12:46:08 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_arm_home
2021-04-06 12:46:08 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Cannot transition from state disarmed to state armed_home, there are open sensors
2021-04-06 12:46:08 DEBUG (MainThread) [custom_components.alarmo.automations] alarm_control_panel.home_alarm has failed to arm
2021-04-06 12:46:08 DEBUG (MainThread) [custom_components.alarmo.automations] executing automation *******
```

The state of the alarm as in step 4 is set to "disarmed". The rest of the state attribes are as follow:
```
code_format: number
changed_by: ***
code_arm_required: true
arm_mode: armed_home
open_sensors:
  binary_sensor.contact_door_front_contact: open
bypassed_sensors: null
delay: null
expiration: null
friendly_name: Home Alarm
icon: 'mdi:shield-home'
supported_features: 7
```

Finally, step 5 and 6 logs are:
```
2021-04-06 12:47:01 DEBUG (MainThread) [custom_components.alarmo.card] registering card
2021-04-06 12:47:01 DEBUG (MainThread) [custom_components.alarmo.mqtt] MQTT config was (re)loaded
2021-04-06 12:47:01 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_control_panel.home_alarm is added to hass
2021-04-06 12:47:01 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] Initial state is disarmed
2021-04-06 12:47:01 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] Waiting for all sensors to be ready...
2021-04-06 12:47:31 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Not all sensors are initialized yet, starting anyway.
2021-04-06 12:47:31 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Alarm is now armed (armed_home).
2021-04-06 12:47:31 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.home_alarm was updated from None to armed_home
```

And the home alarm state after step 6 is set to `armed_home` and the attributes are:
```
code_format: number
changed_by: ***
code_arm_required: true
arm_mode: armed_home
open_sensors: null
bypassed_sensors: null
delay: null
expiration: null
friendly_name: Home Alarm
icon: 'mdi:shield-home'
supported_features: 7
```

**Comment by mariocao** [comment]
Anyhow, I invested a little more of time in understing those conditions in the `async_added_to_hass` function and I think that the problem has an easy fix.

If I understood it correctly, the second branch checks if all sensors are available to arm the system. However the condition that the system should be armed is not checked there. Therefore the `self.async_set_timer(const.INITIALIZATION_TIME, async_initialization_timer_finished)` is called even in the case that there is no need to wait for sensors to arm the system because the initial state is `disarmed`.

I think that if we add the condition of `initial_state in ARM_MODES` in the second branch should be enough to solve this issue.

Here is a fragment of the function `async_added_to_hass` with the proposed fix and it worked witth my current configuration.

```python
        if initial_state == STATE_ALARM_TRIGGERED:
            await self.async_trigger(skip_delay=True)
        elif initial_state in ARM_MODES and not self.hass.data[const.DOMAIN]["sensor_handler"].all_sensors_available_for_alarm(
            self.area_id,
            initial_state
        ):
            _LOGGER.debug("Waiting for all sensors to be ready...")

            @callback
            async def async_initialization_timer_finished(now):
                """Update state at a scheduled point in time."""
                _LOGGER.info("Not all sensors are initialized yet, starting anyway.")
                await self.async_arm(self.arm_mode)

            self.async_set_timer(const.INITIALIZATION_TIME, async_initialization_timer_finished)
        elif initial_state in ARM_MODES:
            await self.async_arm(self._arm_mode)
        else:
            await self.async_update_state(STATE_ALARM_DISARMED)
```

Btw, it seems that maybe the previous code can be refactored by checking if `initial_state == STATE_ALARM_DISARMED`. The  code before the snippet already sets `initial_state` for the cases of `pending` and `arming`, setting it to `triggered` and `arm_mode` respectively. However I didn't change it in case I am overseeing something.

Thanks and let me know if I can help with something.

**Comment by nielsfaber** [comment]
> If I understood it correctly, the second branch checks if all sensors are available to arm the system. However the condition that the system should be armed is not checked there. Therefore the self.async_set_timer(const.INITIALIZATION_TIME, async_initialization_timer_finished) is called even in the case that there is no need to wait for sensors to arm the system because the initial state is disarmed.

The reason behind this, is that some sensors (smoke/flood sensors, etc.) can always trigger the alarm. 
So while the chance is very low that the system starts with the activation of such sensor, it cannot be ignored.
As long as the sensor states are not known (due to taking too long to initialize), the initial state cannot be assumed.

> I think that if we add the condition of initial_state in ARM_MODES in the second branch should be enough to solve this issue.

I think indeed this is the root-cause of the problem.
The `arm_mode` should be `null` when the alarm is disarmed, for some reason this is not the case.
I will check what causes this and work on a fix.

**Comment by nielsfaber** [comment]
I am assuming this problem is fixed since the last update.
Please let me know if there are still problems.

**Comment by sindudas** [comment]
I have not had problems again, it seems resolved now.

Thank you very much for your work

**Comment by axerontios** [comment]
Whenever i restart home assistant alarmo arm itselfs, even though that it was not armed before the reboot. Not very nice when you are tinkering your HA config and then suddenly lights start blinking after a reboot :/ 
Im in the latest version in alarmo and home assistant
