### ISSUE TITLE
Remote & Tags

### ISSUE THREAD

**Issue by mycanaletto** [nielsfaber/alarmo#146]
Hello!

With this out of the box solution it would be interesting to manage remote controls and rfid tags or arm or disarm.

Apart from that everything is perfect!

**Comment by nielsfaber** [comment]
I must say this feature is asked multiple times.
Although it can be done with a simple automation, it seems not too much work to add a panel for it.
Good thing too is that you don’t need to provide a code and maybe skip the delay time too.
What type of entities are your remotes/tags (I don’t use them in my HA setup)?

**Comment by mycanaletto** [comment]
Yes I do this without any problem with an Aqara inter Aqara and an rfid tag integrated to HA. It's just that it would be a plus for this integration for people less comfortable with automation...

**Comment by nielsfaber** [comment]
After long time without activity on this (but a lot of consideration), I have to close this request.
The main issue I'm facing is that HA has no generic implementation for remotes.
If some 'remote' entity type would exist, which would be used for buttons, keypads and keyfobs, it would significantly help to make a solution which would be compatible.
The reality is that the implementation varies wildly, and as a result, the interaction with the alarm requires custom approach.

Tags are a completely different story. They seem only compatible in combination with a DIY EspHome NFC card reader.
I think this makes it interesting for a very limited amount of users. 
If you ask me, this might as well be removed from HA and considered a custom component.

I am very much in favor of expanding functionality of Alarmo to make it easy to set up with remotes of any form.
However due to the lack of common ground between these devices, I don't see any way of facilitating this.
I think it's best to make use of blueprints as a link between the devices and Alarmo. There are already some around for zigbee keypads etc. 
If you have any ideas for improvements to facilitate automation for external arming/disarming, keeping things in sync, validating codes etc., please feel free to share.

**Comment by mycanaletto** [comment]
With hindsight I believe that the management of remote controls or keyboards can indeed be easily done from Home Assistant. Same for tags which are just another form of remote control.

I did it by hijacking a keyboard and it's a special case every time https://www.canaletto.fr/post/home-assistant-and-keypad

**Comment by pvtex** [comment]
i think including rfid tags are great.
i am using a wiegand keypad with rfid reader with a esp8266 with esphome.
now i have a bunch of automations to get the tags an pincode working together.

i need to input pin code and then scan the rfid card to open my door locks.

there is a tag_scanned event in ha, so this could be used and a new field in the codes section for the rfid tag id.
if there will be an option to choose between code or rfid only or both needed that would be perfect.

**Comment by Beau11999988** [comment]
But how can you make the RFID tags secure so that not everyone can see the code, assuming there is a tablet on the wall preloaded with the Home Assistant dashboard?

**Comment by Beau11999988** [comment]
But how can you make the RFID tags secure so that not everyone can see the code, assuming there is a tablet on the wall preloaded with the Home Assistant dashboard?
