### ISSUE TITLE
Not arming at all - additional Areas

### ISSUE THREAD

**Issue by Masterz69** [nielsfaber/alarmo#149]
Can You please explain - what is pre-requisites to arm area?

Have created area, added sensor into, configured some actions, but...
![image](https://user-images.githubusercontent.com/15225823/109704071-dbf13780-7b9e-11eb-9ae0-4a02465bb362.png)
^^ nothin happens pressing ARM buttons - state still Disarmed.

**Comment by nielsfaber** [comment]
There are probably some sensors active which block the arming.
Only motion (and door sensors for arm away) may be active prior to arming.
Windows / tamper / environmental sensors should be off.
I recommend to configure a notification for the "failed to arm" event, such that Alarmo tells you what's wrong.
Otherwise it is printed in the HA log (if you have "info" logging enabled)

**Comment by Masterz69** [comment]
Only one environmental sensor attached - see issue #150.
Logging enabled by
logger:
  default: info
Notification on 'failed to arm' created.

!!! Arming/disarming works ONLY on out-of-the-box created Area !!!
But NOT working on my manually created Area: pressing ARM % in panel - happens nothing, no logs, no notification.

**Comment by Masterz69** [comment]
Actually this is IMHO bug/feature of Alarm panel in Lovelace.
ARM buttons enabled for Modes, which is DISABLED for particular Area.

Mode disabled, Button enabled - arming not happens.

**Comment by nielsfaber** [comment]
I agree with you. I already reported a bug for this to the HA team months ago.
I'm planning to create an "alarmo card" which is a bit more intelligent for these matters.
