### ISSUE TITLE
Feature request? Arming alarm with open windows

### ISSUE THREAD

**Issue by dannymertens** [nielsfaber/alarmo#163]
Hi,

I'm almost sure that It should be possible, but really can't find it, probably my stupid mistake but can someone point me in the right direction please?

Situation..

Now thats it get warmer we want to leave to windows in the bedrooms (second floor) partially open at night when were sleeping, is there a way that we don't need to remove the window sensors for this.
Because now the alarm will not activate because there are windows open, I found this in the documentation, (https://github.com/nielsfaber/alarmo#allow-open) what will do the trick fine I think, but I really don't find an option for this for the window sensors, is this correct or am I'm missing something here?

Thanks in advance!

**Comment by nielsfaber** [comment]
Hi Danny,

This function has been requested a couple of times, but it is not supported.
The main issue is that Alarmo cannot know whether you intentionally left open a window, or you forgot to close it.
I think its better to be conservative here, and have Alarmo notify you that you left the window open.
You can then choose to bypass it (by means of actionable push message or the alarmo.arm service).
You can could also choose remove the window sensors from the list of registered sensors during the night. 
This would be my recommendation since it also allows you to open a window in the middle of the night (after arming).

**Comment by dannymertens** [comment]
Hi Thanks for the quick reply!! I  understand the reasons you bring up... and for the most part I even agree with them, well to be honest you are probably completely right if you look at the security part but as you know not everything is black and white so let me explain why I still think its a good idea to have this available  

In my previous solution the great Heimdall for Homey I could still enable the alarm with an open window if I excluded that, but after a couple of seconds the window was still armed, so closing the window or tampering with it would still activate the alarm.
I see your from the Netherlands so you know what an (draai kip raam) is :-P we have several on the second floor that are open during the summer if we leave for a short period of time, shopping, taking a walk..., there not (easy) reachable very clear view from the street (social security) and they have special locks so they can't be opened more or tampered with so not problem to leave them open, I even got approval from the police when we let them do an audit ;-) so only during the night will not work for us I'm afraid.

I checked the option you mentioned with a notification to bypass the alarm that seems to work fine, the only issue is here no smartphone for the wife and/or son at the moment, so also not an option for now I'm afraid.

I off course respect your opinion in this and will still be a happy user of the great tool you build where for my greatest thanks but still hope a little that you consider the option in a future version ;-)

Thanks!!

**Comment by nielsfaber** [comment]
There's a quick workaround that might help you.
You can remove the device type from your window sensors, then the "allow open" option magically appears under advanced settings:
![image](https://user-images.githubusercontent.com/16861605/112859651-51272e00-90b3-11eb-8cb6-4fbacc117be8.png)

![image](https://user-images.githubusercontent.com/16861605/112861410-0dcdbf00-90b5-11eb-8409-a7c2325356f2.png)

I will keep this request open for a while, perhaps I shouldn't be stubborn and allow people to do as they please 🙂

**Comment by dannymertens** [comment]
Hi Niels,

My apologies I don't think it's stubborn, maybe even what I want is stupid but hey we are all people, and to be honest you're the developer so you decide what your build in the app, it was just another view on things and to be honest I not disagree with your remarks if we look at the security side of it, your idea is probably a lot more responsible ;-)

Thanks!

**Comment by shred86** [comment]
First off, awesome work @nielsfaber with Alarmo. I just recently switched over from an Abode security system to using Konnected.io since the house I moved into has hardwired sensors. I initially created a manual alarm panel and setup a bunch of automations which I documented [here](https://github.com/shred86/smart-home/blob/main/home-assistant-konnected-security-system.md), but after setting up Alarmo I realized I could have saved a lot of time. ;)

That being said, I also think this feature request would be beneficial. I would love to see an option to always arm even with faults (e.g. window open) because for folks who use geolocation to arm, I think this would be a more conservative approach. For example, I use geolocation to arm the system but often I'll be driving when the system is armed. I will typically take a quick glance at my Apple Watch to confirm it's armed. As I've been using geolocation to arm for several years now, I often get into the habit of just assuming everything armed so I'd rather have it arm as a default since that still provides better security than remaining disarmed.

I'd imagine it would become another available event, "Alarm is armed with faults", so users could create a custom notification for this particular scenario.

**Comment by nielsfaber** [comment]
In the v1.5.6 update I added a new option for window sensors:

![image](https://user-images.githubusercontent.com/16861605/113810755-3025a380-976b-11eb-97ec-ae85077356d3.png)

It should have the effect you're looking for.

It does not work exactly the same as the "allow open while arming" option for motion sensors.
The "allow open" option does not result in the bypassing of the sensor, but only allows it to be **initially** ON.
This option is specifically intended for a sensor that remains ON for x time until it resets.
After the resetting it will still provide security function.

Differences between the "auto bypass" and "allow open while arming" option:
1. Setting the auto bypass option will add the sensor to the bypassed_sensors list. If you set up a push notification after arming, you could include `{{bypassed_sensors}}` to show this information. In a future update I might also add a display of bypassed sensors in the alarmo-card.
2. A bypassed sensor can still be closed and opened after the system is armed (while the "allow open while arming" option is only works for the initial state). Hence it could be useful at night when its noisy or raining at some point, so you want to close your window and later perhaps open it again.

Please check it out, let me know if it works for you or additional changes are needed.

**Comment by dannymertens** [comment]
Hi Niels,

This is a great option for the night when your home I think, to be honest I forgot in the past a couple of times to disable the alarm before closing a window when it started to rain, was not really fun I can say 🤪 so very happy with this option!

But if I leave the house for a walk for instance I would prefer the allow open while arming function because this way the window is still armed if someone tampers with the window.

Or do I misunderstand the new option?

Thanks!

**Comment by nielsfaber** [comment]
> But if I leave the house for a walk for instance I would prefer the allow open while arming function because this way the window is still armed if someone tampers with the window.

For all those nice burglars who close the windows for you 🙂 
I think this is a bit too much. Think it would confuse more users than it would be meaningful.
I actually think the biggest risk here is the wind closing a window, giving you a false trigger.
I’d recommend bypassing open windows completely,  it seems an illusion you can still obtain some security by triggering on the closing of a window.
As said, bypassed sensors are registered in Alarmo, so you can be made aware of them by GUI/notifications.

**Comment by dannymertens** [comment]
Your probably right ;-) thanks for the new option works great!
