### ISSUE TITLE
Different pending states

### ISSUE THREAD

**Issue by tremebundo** [nielsfaber/alarmo#17]
Hi,
I have a feature request. I would like to have different events for pending to armed away and pending for armed night. Something like "pending_away" or "pending_night".
The reason is that I automate this changes with some different actions like tts.say, switch on different lights, that are not the same in both cases.
The same request for warning states make sense too, I think.

**Comment by nielsfaber** [comment]
Actually this is already possible.
You can restrict any automation (currently notification) to specific arm modes only.

I have to add a field in the UI for this still, but the behavior is already there and tested.

I will keep you posted when I added this.

**Comment by tremebundo** [comment]
What I mean is that the state between "disarmed" and "armed away" and "armed night" is the same: "pending"
I would like to say "You have 30 secs to leave the house" during the pending time when going to armed_away, but say "The night alarm mode is going to be armed, close corridor door. Good night"
But now, in both cases it says:"You have 30 secs to leave the house"

**Comment by nielsfaber** [comment]
I understand.
The states are defined by HA, otherwise I wouldn’t have used ‘pending’ and such.

But once you arm, Alarmo stores the arm mode (away/home etc) and is stored until you disarm.
You can consider this mode as a ‘substate’.
What I’m trying to say is that you can create notifications for specific state+substate combinations.
So a message for ‘leave+away’ is no problem.

**Comment by tremebundo** [comment]
I really meant arming states and not arming.
Anyway, I already thought that it was a limitation imposed by HA.
Thanks for your suggestions and interest.
