### ISSUE TITLE
Feature request: geofencing for arm/disarm?

### ISSUE THREAD

**Issue by ShayaanF** [nielsfaber/alarmo#19]
I'm enjoying the integration thus far (thank you for your efforts!), and as I'm a recent convert from SmartThings one thing I did like was being able to trigger alarm states based on geofencing of my mobile devices. Is this something possible to add as a way to arm and disarm? Also any thoughts on when we'll be able to trigger a siren within this integration? I use Konnected for my devices and that one isn't working yet

**Comment by nielsfaber** [comment]
Glad to hear. I'm just starting it, so you can expect more improvements to come.
Geofencing can be achieved in many ways. With the HA app for example, you can detect whether a `person` is home or not.
Such functionality will not become part of Alarmo.

The only thing that you need in addition, is some automation/logic to set the alarm to `armed_away` if all `person`s left the house, and to `disarm` when someone arrives.
You can already make this, by creating an automation.
The only problem is that you cannot configure the alarm to have a code (or you should type it as parameter it in the automation).
Maybe I will add a UI to configure such `triggers` from within Alarmo at some point. But it would have the same effect as writing an automation.

As for:
> Also any thoughts on when we'll be able to trigger a siren within this integration

The same applies. You can create a automation to turn on your siren when the alarmo state goes to `triggered`.
I will add a small editor (like the notifications), but it is only for convenience.
It's not really needed because such functionality is already in HA. 
It should probably be released by the end of the weekend (unless I encounter issues).

**Comment by nielsfaber** [comment]
I'm closing this issue since it seems to be outdated.
The functionality you asked for is in place now.
