### ISSUE TITLE
Card integration error for HA core-2021.5.0

### ISSUE THREAD

**Issue by thanksmister** [nielsfaber/alarmo#208]
Getting an error for the card in HA this is my version: 

```
Core
Version
core-2021.5.0
Newest Version
core-2021.5.4
```

This is from the HA logs

```
Logger: homeassistant.config_entries
Source: custom_components/alarmo/card.py:37
Integration: Alarmo (documentation, issues)
First occurred: May 6, 2021, 12:03:22 PM (1 occurrences)
Last logged: May 6, 2021, 12:03:22 PM

Error setting up entry Alarm Panel for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alarmo/__init__.py", line 77, in async_setup_entry
    await async_register_card(hass)
  File "/config/custom_components/alarmo/card.py", line 37, in async_register_card
    hass.data[DATA_EXTRA_MODULE_URL].update(url_set)
AttributeError: 'UrlManager' object has no attribute 'update'
```
Here is what you see in the integration section of HA:

<img width="364" alt="Screen Shot 2021-05-18 at 2 13 13 PM" src="https://user-images.githubusercontent.com/142340/118695106-3041a600-b7e3-11eb-9dc7-c48b72a5c682.png">

**Comment by thanksmister** [comment]
Sorry, this looks like duplicate of closed issue https://github.com/nielsfaber/alarmo/issues/199

**Comment by thanksmister** [comment]
sorry, duplicate of https://github.com/nielsfaber/alarmo/issues/192 and many others.

**Comment by nielsfaber** [comment]
Looks like you answered yourself :)
Please make sure to run latest-greatest before reporting bugs (saves time for both of us).

**Comment by thanksmister** [comment]
Don't you have a way to upgrade alarmo?   There is no update to this, so I am assuming you mean I have to update HA?

**Comment by nielsfaber** [comment]
Looks like you updated HA but not Alarmo.
By using HACS you can stay up-to-date automatically, otherwise you should overwrite the files manually.
This holds for any custom integration in HA.

**Comment by thanksmister** [comment]
Yeah, thanks for the info, but I will not run HACS.  I think HA should have way to update integrations, some like MQTT do this.

**Comment by nielsfaber** [comment]
There's a difference between internal integrations (which come pre-installed with HA) and custom integrations.
I would also prefer if HA offers a way to manage custom integrations, especially since their updates often contain breaking changes (like the one you found today), hence you will have to keep the custom integrations in sync as well.

I guess they consider HACS as the way to do it, but this is quite a heavy implementation (it seems more like a plug-in store), and it is still not very integrated (an 'update' button on the integrations page would do nicely).

I also avoided HACS for a long time, as I had issues with my own installation in the past.
But nowadays it runs pretty solid actually, so you might give it a second chance (to make your life easier).
I estimate 95%+ of Alarmo installations use HACS.

**Comment by thanksmister** [comment]
I hear you man, but HACS has really messed with my setup in the past and has been impossible to remove.  I think HA should offer a way for integrations to submit updates or something along those lines.   I updated manually, thanks!
