### ISSUE TITLE
{{open_sensors}} shows wrong sensor

### ISSUE THREAD

**Issue by Knaackee** [nielsfaber/alarmo#21]
Hey,

at first, thanks for this great integration.

I got an Alarm with Push Notifictions in which i use `{{open_sensors}}`. 
But the variable `{{open_sensors}}` is always the first sensor that triggers the Alarm.

e.g.

- I open `Window 1` and the Notification is correct. "Window 1 is on"
- I dissarm and arm again
- I open `Window 2` and the Notification is wrong. "Window 1 is on"

-- Restarting Home Assistant --

- I open `Window 2` and the Notification is correct. "Window 2 is on"
- I dissarm and arm again
- I open `Window 1` and the Notification is wrong. "Window 2 is on"

Any ideas? 

Thanks again!

**Comment by nielsfaber** [comment]
I'm a bit confused by your text, please be more specific.

Title says 
> shows wrong sensor

Text says
>  is always the first sensor that triggers the Alarm

There's a difference. 

Regarding:

> 1. I open Window 1 and the Notification is correct. "Window 1 is on"
> 2. I dissarm and arm again
> 3. I open Window 2 and the Notification is wrong. "Window 1 is on"

For steps 1+3, is the notification for the `armed -> triggered` transition?
I'm asking, since you can also have an `{{open_sensors}}` notification when arming fails.

Do you leave Window 1 open during steps 2+3?
If that's the case, step 2 should already fail right? The arming should be blocked when you have an window.

When the alarm is triggered, this is always caused by one sensor. 
It's pretty impossible that two sensors change state simultaneously.
You will never see a list of multiple entities in a 'alarm is triggered' notification.

**Comment by Knaackee** [comment]
Hey Niels,

thanks for your fast response.

I think the title should say "Wrong Sensor in the Notification", you're right.

Yes the transition is "Alarm is triggered".

No, I don't leave any window open for the test. 
I arm, and open one window, and close it after receiving the Notification.

Thanks!

**Comment by nielsfaber** [comment]
OK thanks for the additional info.
I will reproduce your test-case, and let you know if i agree something is wrong 🙂

**Comment by nielsfaber** [comment]
Yes, you were 100% correct.
It is an awful bug actually:

-  The notification settings are loaded into the alarm component after startup and after making changes to the notifications.
 So the alarm keeps a local copy of the stored configuration
- The `{{open_sensors}}` wildcard in the message text would get overwritten the first time the notification is processed/sent
- The next instance, this wildcard is gone, and the previous sensor info has become a fixed part of the message, that would be sent every time (until you restart HA or change the config)

Anyway, it was an easy fix, just making a local copy of the message text before making changes to it.
The patch will be included in the upcoming release.

Thanks for reporting this!

**Comment by Knaackee** [comment]
Thank you very much!

**Comment by nielsfaber** [comment]
This is fixed in release v1.2.0.
Please update and test if the issue is resolved.
Close the issue if this is the case, otherwise let me know!

**Comment by Knaackee** [comment]
It does now works as expected. 
Thank you!
