### ISSUE TITLE
Feature Request (or Bug?) - Toggle Keyboard

### ISSUE THREAD

**Issue by Tosko4** [nielsfaber/alarmo#219]
First if all @nielsfaber , thank you so much for your time and effort thusfar!

Maybe it's a bug or I am just utterly blind.

In release v.1.5.6 you mentioned the following bullet:

- add option to keep keypad visible in alarmo-card

Now I appreciate if there was an option, because it's now always showing. I don't require a code when arming, which makes it confusing now. As if the code is still mandatory. Where can I find this switch, or could you enable it again in a new release? Thanks!

**Comment by nielsfaber** [comment]
I wouldnt call you utterly blind, but for me it shows up like this:

![image](https://user-images.githubusercontent.com/16861605/122097346-dea33000-ce0f-11eb-8c45-9d2eedb2ca79.png)

Its affected by this setting:
![image](https://user-images.githubusercontent.com/16861605/122097409-efec3c80-ce0f-11eb-8b9c-ab6d3a206c96.png)

If i turn it on, it looks like this:
![image](https://user-images.githubusercontent.com/16861605/122097465-fda1c200-ce0f-11eb-8c17-cec7742d0fc2.png)

Are you sure you are looking at alarmo-card?
A lot of users confuse it with the Alarm Panel card of Lovelace (https://www.home-assistant.io/lovelace/alarm-panel/), because the differences are very subtle.

**Comment by Tosko4** [comment]
You're right. Confusion was the same here. With alarmo card its hidden. Sorry bout that!

**Comment by nielsfaber** [comment]
No problem.
Please close your issue.
