### ISSUE TITLE
alarmo 1.6.1 BUG in actions

### ISSUE THREAD

**Issue by cokeman0** [nielsfaber/alarmo#224]
Hi trying to make a "turn on siren" work 24/7 (smokes sensors)

When trying to save this, I get this error

![image](https://user-images.githubusercontent.com/6389802/121365605-148c7400-c939-11eb-85d5-d306900fa20e.png)

**Comment by nielsfaber** [comment]
Missing some context to be able to help.
Are you editing an older notification, or creating a new one?
Which modes show up in the list?

**Comment by cokeman0** [comment]
I have tried both. change old, and create a new

![image](https://user-images.githubusercontent.com/6389802/121409362-b627bb80-c961-11eb-802b-521881f45cef.png)


and deleting the items, and the list shows up as:

![image](https://user-images.githubusercontent.com/6389802/121409490-e1120f80-c961-11eb-970f-83cd7e803a07.png)

Here I have created a new action:
![image](https://user-images.githubusercontent.com/6389802/121409684-0ef75400-c962-11eb-9bfa-52ab9988a2db.png)

**Comment by nielsfaber** [comment]
Ah, I'm finally able to see the same problem:
![image](https://user-images.githubusercontent.com/16861605/121410128-8d53f600-c962-11eb-950e-55050827e418.png)

I will work on a fix.

**Comment by nielsfaber** [comment]
I fixed it locally https://github.com/nielsfaber/alarmo/commit/670cc8c49b645c71c040c21c41df6e5a9cd603c8
I will release a new update in the upcoming days which should fix this.
In the meantime you need to have at least 1 mode selected, otherwise you're not able to save.

**Comment by cokeman0** [comment]
Thanks, we hope soon, as this trigger with "none or all" is needed to trigger the sirens if/when a smoke sensor detects smoke

**Comment by cokeman0** [comment]
Sorry, the fix is not complete.

When trying to remove both modes so there is no restrictions on when the action will run, smoke sensor, it still add both modes back to the list.

Please try to make a new action, remove all restrictions, and save it. When you look at it again,  You will then find that is will only trigger armed_home and armed_home.

I need it to trigger always if a environment sensor triggers, and instantly 😄

**Comment by nielsfaber** [comment]
I will take another look at this 👍

**Comment by nielsfaber** [comment]
In my test instance of HA I set up the front door as environmental sensor

![image](https://user-images.githubusercontent.com/16861605/122095516-c6caac80-ce0d-11eb-8b91-0e47cdb34372.png)

Action is set up to execute regardless of the arm mode:
![image](https://user-images.githubusercontent.com/16861605/122095628-ea8df280-ce0d-11eb-948c-cfef1fd039f1.png)

After saving, the siren is indeed switched on by the frontdoor, while the system is disarmed.
So the functionality is OK.

But when returning to the action, I see that the modes are filled in:
![image](https://user-images.githubusercontent.com/16861605/122095767-14dfb000-ce0e-11eb-8945-2d3881defd52.png)

It seems more a display issue than functionality issue.
But I agree that it is not pleasant (especially because after editing you will have to remove the arm modes again).

**Comment by nielsfaber** [comment]
Fix is on the way https://github.com/nielsfaber/alarmo/commit/a6ae72575b5245ee3bd9722a23f0bd9bec205cee
