### ISSUE TITLE
Disallow arming state if sensors are open

### ISSUE THREAD

**Issue by goyney** [nielsfaber/alarmo#245]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal

Currently, if you try to set the alarm while a sensor is in an open state, the entire "exit delay" time has to expire before it failing. This is not ideal. For example, if my back door is cracked open, I hit "Arm Away," then leave... by the time I get the notification informing me the alarm could not be set because the back door was open, I'm already driving down the street.

Instead, I would like to propose an option to completely disallow arming while a sensor is open (this could be configurable on the sensor itself). So say I have 3 doors. All 3 doors MUST be closed to even start the arming process. If any door is open, I get the IMMEDIATE feedback that it cannot start arming, so I can remedy the situation. Once all 3 doors are closed, I hit start the arming process and leave the house within my defined timeframe.

This is really the only thing currently preventing me from using this wonder addition to Home Assistant.

**Comment by nielsfaber** [comment]
> Currently, if you try to set the alarm while a sensor is in an open state, the entire "exit delay" time has to expire before it failing. This is not ideal. For example, if my back door is cracked open, I hit "Arm Away," then leave... by the time I get the notification informing me the alarm could not be set because the back door was open, I'm already driving down the street.

The idea I had in mind is that sensors on entry doors should be assigned with type `door`. 
During the exit delay, the `door` sensors of type are still allowed to be open(ed). A non-entry door should be treated as a `window`.
As soon as you close any `door`, this signals Alarmo that you left the house and the alarm will be armed instantly, so rest of the exit delay is skipped.
So you should get the notification of Alarmo failing to arm due to any other door or window being open, right as you close your front door..

If it doesn't work well for you, I guess you have one of the following situations:
- A) You have a garage attached to your house, so the garage door is an entry and you're literally driving away once Alarmo is armed.
- B) You don't operate Alarmo from within the house, but you're already outside (in this case the exit delay is pretty useless).
- C) You set things up in a different way than I anticipated.

Please let me know 👍

**Comment by goyney** [comment]
Traditional alarm systems work in the way in which I described. If I'm standing at my wall-mounted tablet and try to arm the alarm, I want the feedback there, not after I walked down the hall and open/close the garage entryway door. At this point, I'm out of range to hear/see the tablet's feedback. If I have a notification sent to my phone, it can easily be missed in the shuffle of getting into my car (especially with a 2 year old 😄 ).

I think both configurations are useful; obviously plenty of people are using this as is. But for those coming from traditional keypad-on-the-wall solutions, its a change. Unfortunately for me, it's not a wife-friendly change.

**Comment by Savagedlight** [comment]
How about adding an option to the advanced sensor configuration, right next to the "Immediate" trigger (triggers alarm immediately instead of starting entry delay)? The new one would be something like "Fail arming if this sensor is open".

My workaround for this feature is to have a HASS panel which shows the state of all exit doors, and the alarm panel - letting me see whether doors are currently open when I (dis)arm the alarm.
Additionally, I have configured an action in Alarmo which is triggered by "Failed to arm", and by "Exit delay started", which checks the status of doors and gives a TTS audio warning when appropriate.

**Comment by goyney** [comment]
Just some more context into this. Using the native `alarm_control_panel`, with some trickery, my touch panel interface looks like this in "Ready to Arm" and "Not Ready" states:

![Screen Shot 2021-07-28 at 8 34 34 AM](https://user-images.githubusercontent.com/1015040/127334431-02a85dcd-ccac-47f7-af16-c36fb024fd05.png)
![Screen Shot 2021-07-28 at 8 52 43 AM](https://user-images.githubusercontent.com/1015040/127334436-de86e5b4-327e-4c76-b90c-d5621eab890a.png)

This prevents the alarm from even being enabled while in a "not ready" state. In the cases that the alarm is attempted to be set from an automation or via a voice assistant, the alarm panel uses TTS to announce what sensors are open.

**Comment by nielsfaber** [comment]
I will see what I can do!
Which means: I will probably add this function (unless I encounter some blocking problem), but give me a month or so to find the time.
Note that this feature seems only appropriate for window and tampering sensors. 
Entry doors and motion sensors don't have to be deactivated prior to arming.

**Comment by Savagedlight** [comment]
> I will see what I can do!
> Which means: I will probably add this function (unless I encounter some blocking problem), but give me a month or so to find the time.
Awesome!
Are you open for pull requests?

**Comment by goyney** [comment]
> I will see what I can do!
> Which means: I will probably add this function (unless I encounter some blocking problem), but give me a month or so to find the time.
> Note that this feature seems only appropriate for window and tampering sensors.
> Entry doors and motion sensors don't have to be deactivated prior to arming.

Except for when the back sliding doors are slightly cracked. Honestly, if you can make this a toggleable option for any sensor, that would provide the most flexibility. I don't allow the alarm to be set if any contact sensor is open, included the door I'm about to leave out of.

**Comment by nielsfaber** [comment]
@Savagedlight 
> Are you open for pull requests?

I would be happy with contributions as I have very little time to work on Alarmo currently.

But in this case, I would like to play around with the GUI side a bit.
I have my doubts whether these flip switches are really scalable (and people don't seem to like sticking to door/window/motion sensors), so I was thinking to move to another concept.
Therefore I am not sure if this particular feature is a good candidate for PR, unless we would discuss first how it should look like.
Hope you understand 🙂

**Comment by nielsfaber** [comment]
I decided to add the following options:
![image](https://user-images.githubusercontent.com/16861605/128756503-dccbbbc8-d2bd-4f8b-9362-27ecc9adbe6c.png)

They will replace the former "immediate" setting and instead offer separate control over exit / entry behaviour.
I hope these settings are self explanatory and help for your use-cases.
If not, now is the time to shout.

Note that if the "use exit delay" setting is off, the user is required to have these sensors (e.g. doors) closed when starting the arming procedure, otherwise the arming fails (with push message etc.).
During the exit delay however (so after passing the preconditions checks), it is allowed to open and close these sensors (to allow you to leave your house).

**Comment by nielsfaber** [comment]
This feature is now added in the v1.7.0 release.
