### ISSUE TITLE
alarmo-card not created

### ISSUE THREAD

**Issue by swa72** [nielsfaber/alarmo#246]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
When hitting the + Buttton, I can search for alarmo-card

### Actual behavior
There is no alarmo-card 

### Steps to Reproduce
Running core-2021.6.6
Running HACS 1.13.2
Went to HACS, integrations, searched for "Alarmo" and added the repo.
Rebooted
Loaded the integration into HA.
I can see the entity `alarm_control_panel.alarmo` in e.g. "Developer Tools"

With 

```
type: 'custom:alarmo-card'
entity: alarm_control_panel.alarmo
```

I get

```
Custom element doesn't exist: alarmo-card.
type: custom:alarmo-card
entity: alarm_control_panel.alarmo
```

**Comment by nielsfaber** [comment]
Duplicate of https://github.com/nielsfaber/alarmo/issues/221
Duplicate of https://github.com/nielsfaber/alarmo/issues/199
Duplicate of https://github.com/nielsfaber/alarmo/issues/196
Duplicate of https://github.com/nielsfaber/alarmo/issues/177
etc.

Issue is caused by browser caching. Clearing the cache should resolve it.

**Comment by swa72** [comment]
My bad. You're right.
