### ISSUE TITLE
No automatic switch off after Operating time/Siren operating time

### ISSUE THREAD

**Issue by Darkbull64** [nielsfaber/alarmo#258]
**The problem**

If you configure an action (I made several test with "light" or "electrical outlet").
When an alarm is triggered on, the action is correctly execute, so "light" or "electrical outlet" is correctly "powered on".
But there is never automatic "power off" after the "Operating time/Siren operating time" that is set-up on the main tab.

**Environment**

Home Assistant 2021.7.4 on raspberry pi 4
Alarmo v1.6.2

Have you ever had this issue?
Thanks for your help.

**Comment by Darkbull64** [comment]
Hi all,
I see that nobdy is commenting but perhaps I don't understant how the system work.
Are you agree with that description :
Action which is triggered on (ie. siren) with an event like "alarm released" is automatically power off after timer setting in the "general tab" (Operating time/Siren operating time).

Thanks in advance  for you help.

**Comment by EdwardSoaresJr** [comment]
I would have given my two cents sooner but I too was hoping for an answer. In the meantime what I do is create actions in Alarmo, one obviously that turns on the siren entity when alarm is triggered. I then create an action that disables the alarm entity on disarm and arm. If you have Alarmo set to disarm after trigger then it will turn off siren after the trigger time has expired due to setting to disarm status. Same thing when set to rearm after triggered state the action to turn off siren when armed will be executed. works for me, I can help further if this doesn't make sense.
Creating these actions like this should work for you for the time being until we have a more dedicated Siren Setting page or better instructions for Siren.
![Screen Shot 2021-08-05 at 12 23 56 PM](https://user-images.githubusercontent.com/10336569/128401851-21cf8c9e-f4ab-47bc-b8e1-2f552a8dc6be.png)
![Screen Shot 2021-08-05 at 12 24 02 PM](https://user-images.githubusercontent.com/10336569/128401858-4d4d6b40-0c4a-499c-aad8-b911399aaa30.png)

**Comment by Darkbull64** [comment]
Thanks a lot for your answer!
I will do as you say for the moment.
Regards

**Comment by nielsfaber** [comment]
As @EdwardSoaresJr said, the _idea_ is to create a separate "turn off" action when disarming, so you will end up with 2 rules involving the siren.
I understand this is can be simplified, however there are many limitations to the _actions_ panel.
I'm not sure yet how far I want to go with the automations within Alarmo, as they can also made with HA automations (and all cost effort to make and maintain).
Hope you can live with the 2 separate rules for now 🙂
