### ISSUE TITLE
Feature request: Publish the Alarmo command to MQTT command topic

### ISSUE THREAD

**Issue by JOHLC** [nielsfaber/alarmo#259]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Currently, it does not look like Alarmo sends a payload on the command topic when it's state is changed through Home Assistant. I have subscribed to the command topic that I set, yet it doesn't update the MQTT command topic when you change states. Is this by design, am I missing something? 

What does work: manually publishing commands to this topic successfully changes the state in Home Assistant. 

It would be nice to have this as a feature that could be enabled/disabled. I would use it to sync with another alarm system that I have which also accepts commands on this same topic. 

### Additional info
None

**Comment by nielsfaber** [comment]
As described [here](https://github.com/nielsfaber/alarmo#command-topic), the command topic is an **input** topic, and can be used for arming/disarming Alarmo externally (and not the other way around).

If you want to see when the state of Alarmo changes, you may want to use the **state topic**. 
There is also an **event topic**, which you could use to see when the alarm is armed/disarmed (and in which mode).

Note that it is not really possible to keep 2 alarm systems in sync through MQTT.
Limitations:

- if one alarm triggers, this doesn't cause the other alarm to trigger
- if one fails to arm (due to a blocking sensor), this is not known by the other
- code used for arming is not sent through MQTT (for security reasons)
- delay times may be different

I strongly recommend a centralized approach, so a single alarm system which is in charge.
The MQTT topics of Alarmo are mostly intended for communication with a touchscreen or keypad, devices without internal stating behaviour.
