### ISSUE TITLE
New sensors cannot be added

### ISSUE THREAD

**Issue by Eyco1981** [nielsfaber/alarmo#274]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
Existing sensors can be added to Alarmo.

### Actual behavior
Trying to add new sensors results in an error 400. This behavior started with version 1.7.0 and continues with 1.7.1.
Error message is as follows:

Something went wrong!
Message format incorrect: extra keys not allowed @ data['immediate']
Response error: 400
Please report the bug. 

### Steps to Reproduce
Adding a new sensor in the Alarmo integration SENSORS/Add Sensors.

**Comment by nielsfaber** [comment]
Could you check in the Alarmo configuration frontend whether your browser loads the correct version?

![image](https://user-images.githubusercontent.com/16861605/129485350-0e7c1c2b-dd4f-4a18-9519-a41f2a0dd124.png)

**Comment by Eyco1981** [comment]
It shows 1.7.1.

**Comment by nielsfaber** [comment]
It is strange to me because for me this doesn't happen, and the code does not contain any place where `immediate` is added to the data.

Clicking "add to alarm" here:
![image](https://user-images.githubusercontent.com/16861605/129485468-bbe24317-b3cb-4a21-8270-27f4fccbcb95.png)

Leads to the sensor showing up at the bottom of the "Sensors" list:
![image](https://user-images.githubusercontent.com/16861605/129485497-156995ad-0195-4c5f-885a-c8b529e5520f.png)

**Comment by H2OKing89** [comment]
Having the same issue. i've also tried removing everything and readding with no luck

**Comment by nielsfaber** [comment]
I need some clues guys, else I cannot work this out…
Please don’t give up and revert, would be better if you could pinpoint it to certain entities, browser etc..

**Comment by H2OKing89** [comment]
Found the issue. Switch to Chrome and was able to add. Went back to Edge and reset cached, I am now able to add stuff. need to clear browser

**Comment by Eyco1981** [comment]
I have uninstalled the integration in HACS, removed it in Integrations and deleted the file alarmo.storage in the /config/.storage folder. So basically wiped everything.
After reboot and reinstalling it works now.

**Comment by nielsfaber** [comment]
So the conclusion is that this issue is cache-related?
I am afraid that this would mean that I cannot solve it (caching is handled by HA internally).
I was hoping that display of the version number in the top right corner of the Alarmo panel would make it easy to spot caching issues, but if I understand correctly the version number was showing correctly (latest) while the error occurred.

**Comment by Alex230177** [comment]
Ciao, anche a me dopo aver aggiornato mi da Response error: 400, e nonostante ho disinstallato ed installato piu' volte mi dice che la versione è la 1.6.2 sulla sheda Alarmo,

**Comment by Alex230177** [comment]
Modifico ho risolto il problema cancellando la cronologia del browser, e riavviando home assistant la nuova versione 1.7.1 funziona,
Comunque sarebbe perfetto se si riuscisse ad integrare le telecamere, ottimo lavoro grazie

**Comment by nielsfaber** [comment]
@Alex230177 English only please.

**Comment by tader** [comment]
Clearing browser cache (macOS, Safari) fixed this issue for me.

**Comment by nielsfaber** [comment]
Closing issue due to lack of response from @Eyco1981, assuming problem is fixed.
