### ISSUE TITLE
Feature Request: Bypass until the sensor gets closed

### ISSUE THREAD

**Issue by xefil** [nielsfaber/alarmo#285]
Hello all,

It's possible to implement a bypass mode that permit to arm the alarm, but doesn't get ignored if open as soon it gets closed?
In example, I'm ready to leave the home, so I open the door, and as soon I'm moving out I activate the alarm... but, huh, the door is open and so it gets ignored until I rearm it because the bypass option is enabled. If I disable it, for sure the next time I'll try to arm the alarm, the door is open and I cannot arm it.

Possible to implement such feature? Seems not present afaik.

Thanks and great project anyway!

Simon

**Comment by nielsfaber** [comment]
For motion sensors such feature exist.
The idea is that some motion sensors take 1-2 minutes after seeing movement before they return to inactive state.
So if you try to arm the alarm from within the house, you could immediately trigger the alarm when the exit delay is passed (if exit delay is shorter than this motion sensor delay).

This setting will cause the initial state to be ignored:
![image](https://user-images.githubusercontent.com/16861605/134453822-262cff3c-4c13-4beb-adda-ca2038850e37.png)

If you want to apply this kind of behaviour to a door sensor, you could clear the sensor type field:
![image](https://user-images.githubusercontent.com/16861605/134453953-da0e9552-58c8-47db-84db-7f2a86546843.png)

This makes all settings show up, rather than only appropriate ones.
I'd say it would work for your use-case, give it a try 👍 

I'm hesitant to implement extra functionality for this. In my opinion, the bypass functionality should remain transparent, so should completely eliminate the sensor. Assigning extra rules for this might be confusing for users.

**Comment by xefil** [comment]
Hello,
Thanks, but removing the device type, this option is not (immediately) shown:

![image](https://user-images.githubusercontent.com/17131053/135811537-0a7d9449-91aa-4138-9d99-037362742568.png)

But it's shown only if I do the following:
1) remove the sensor type, the option is not there
2) select the "Motion" sensor type, the option is shown and activated by default
3) remove the sensor type, the option remains.

Sorry for the delay answerring and thanks for the support @nielsfaber  !

Simon

**Comment by xefil** [comment]
Hello @nielsfaber ,
I was partially wrong. If I remove the sensor type, I can enable the "Use Exit Delay", but the sub-command "Allow open after arming" is grayed out, and I cannt activate it.
So to have both "Use Exit Delay" and "Allow open after arming", I need to:
- delete the sensor type
- select the Motion sensor type
- delete the sensor type

Normal?
Thanks, Simon
