### ISSUE TITLE
Alarm system can be armed in AWAY mode even one sensor is in open state

### ISSUE THREAD

**Issue by bcutter** [nielsfaber/alarmo#292]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
If a sensor is in open state, alarm system can not be armed - independently of arm mode.

### Actual behavior
One sensor is in open state, the alarm system can be armed in AWAY mode. If HOME mode is chosen the sensor is listed in "can not arm due to following sensors" message.

The sensor is a door sensor (NOT a motion sensor which is listed in AWAY mode description). No difference to all the other sensors.

**Comment by nielsfaber** [comment]
I take such accusations very seriously. If people's security is at risk this would be a critical problem.
But of course I'm hoping this is not the case.

First off, could you check the configuration for the sensor which seems to be ignored?
Especially the following fields are relevant:
![image](https://user-images.githubusercontent.com/16861605/134210512-a83b5cb3-160d-49ca-b8c5-1fee8e0ca86e.png)

If this is all OK, could you share some evidence/reproduction info?
For me (obviously) this does not happen, if I click 'arm away' while the frontdoor is open, the alarm returns to disarmed after the exit delay, due to the frontdoor being open:

![image](https://user-images.githubusercontent.com/16861605/134210918-1d4f1c5a-00f4-4772-a05e-ab663059b168.png)

It would be best if you could shoot a screen recording showing the sensor configuration in alarmo, followed by arming the alarm while the sensor is active.
Otherwise some history or logbook data might also be useful.

**Comment by bcutter** [comment]
I tried to reproduce it with the exact same sensor. Feels like the main issue is
a) me as an Alarmo beginner "not using it right" and
b) a not comprehensible detail configuration of sensors

Regarding b):
This is the configuration of the door sensor mention in the OP:
![grafik](https://user-images.githubusercontent.com/13799156/134811406-4fc4af06-6a02-4cd6-a6ef-9cf9dead6b19.png)

**Is it correct this is the default configuration for device type = door?** And for `window` all switches are off, right?

This is the config by the way:
![grafik](https://user-images.githubusercontent.com/13799156/134811593-7155d98e-f6a7-4e9c-945d-6f73a0fce5c3.png)

I think this is not an Alarmo but level 8 (user) issue. **The main thing I learned is:** alarm can be activated if doors are in open state because of the default configuration for device type door (use exit delay + arm after closing) - which is only reasonable for simple scenarios like front door. If back door or garage door are also active sensors, this advanced configuration should be modified for the AWAY MODE arming - to not be confused like I was before creating the issue. Sorry for that.
