### ISSUE TITLE
Keypad Support

### ISSUE THREAD

**Issue by f3rr311** [nielsfaber/alarmo#320]
Allow physical keypad devices in for the alarm arming and disarming, they devices are there just not really a integration that works good

![image](https://user-images.githubusercontent.com/14023914/141525621-8e2cf911-e5ad-412f-b7dd-eeed473692f6.png)

### Checklist
- [X ] I checked for similar existing requests (both open and closed) before posting.
- [X ] My request is generic, other users may benefit from it too.

### Additional info
allowing to use a card but also allowing the use of the buttons on the keypads to do the arming, disarming and pin entry

**Comment by Eyco1981** [comment]
The Z-Wave Keypad Ring Keypad v2 works perfectly with the according blueprint and synchronizes with Alarmo in both directions.

**Comment by nielsfaber** [comment]
I don't understand the request.
What do you mean with the list you shared? I don't recognize it.

**Comment by EdwardSoaresJr** [comment]
I use the Xfinity XHK1-UE Keypads without issue and fully supported by using Zigbee2MQTT and Node Red as an interpreter. I can share the flow if anyone would like it. It can likely be modified for other non natively supported keypads. I use two of these now with two tablets running MQTT Alarm Panel.
![Screen Shot 2021-11-18 at 10 40 58 AM](https://user-images.githubusercontent.com/10336569/142468009-4f9c80ec-75fc-44fa-8f79-7c6079d58b13.png)

**Comment by nielsfaber** [comment]
> Adding this, correct me if I am wrong but Alarmo is literally just an extension of Alarm in HA, HA is the actual core alarm system? You can control Alarmo by different means and MQTT is one of them and then Alarmo controls HA Alarm? While not impossible, Alarmo can not likely accommodate hardware or EVERYONE's hardware directly and asking for that would be insane. It does one thing and one thing well, it allows you to graphically setup and control what's necessary to run and use the Home Assistant alarm feature, nothing more, the rest is up to you and or Home Assistant.

This statement is a very good point that I wish everyone would realise.

Fact is that HA introduced a binary_sensor device type which standardises the behaviour for on/off sensors.
However for remotes/keypads there is not such uniformity, so it would be very hard for me to create support for it inside Alarmo which would work across multiple brands and types.
The alarm_control_panel entity type in HA is misleading, since it might sound like a very good fit for a keypad, in fact this type is for complete alarm systems instead (implementing their own rules and logic).

The best offer I can make is an easy way to set up automations involving alarmo and external keypads.
There are plans for adding a panel to alarmo for setting up simple tasks for automatic arming/disarming through external devices. But bear in mind this might never reach the same experience as tailor-made automations/blueprints can.

If you could revise your request to some specific points that could be added to alarmo to facilitate linking it with a keypad, I would be happy to hear.

**Comment by f3rr311** [comment]
The list is the device entities I think it's called, I am a little new to the who ha system I'm a migrating hubitat user.


An yes I'll update the post when I get home and if I can't provide more I'll close it.

**Comment by f3rr311** [comment]
The biggest issue I have is I made a mistake in my initial setup and didn't get a mqtt compatible ZigBee doggle so now I have to go and get that sorted to get the compatatability I want.

**Comment by EdwardSoaresJr** [comment]
What dongle do you have?

**Comment by f3rr311** [comment]
Nortek HUSBZB-1,

Was a bad purchase lol. 

The keypad was the Iris V2 keypad, it says it's centralite ilo2 I think it is.  

I see that it can arm and disarm the system but my issue is now I have now like central code manager or anything that links my locks and keypads to users which I don't even think exists in HA which is kinda disappointing thing as they did have that in hubitat stock.

**Comment by f3rr311** [comment]
And the reference was it asked for what device you can arm and disarm in the alarmo menu and I could not see the keypad as a option like you mentioned.

From what I'm gathering here is that the physical keypad can disarm the ha system which is tied to the alarmo front end and so it can work.

Please correct me if I'm wrong.

**Comment by EdwardSoaresJr** [comment]
Nortek is a good combo stick for HA ZHA, I use that stick for my non security zigbee stuff and z-wave stuff. Get second stick for security to use with Zigbee2MQTT, conbee ii is good out of the box and has really good range and stability compared to all CC variants I have ever tried, whereas any CC I tried had bad range, died or just had sensors drop off a few days later, all my xfinity sensors are zigbee 1.2 so that might play into that?

 Welcome to HA, I started with zigbee and HA a year ago doing some work at a hotel that was using zigbee and the bug bit me, since then I have learned way too much and started developing hardware and software for my home and hope to release to the community once it matures some.

I have the same Iris (Xfinity branded) keypad around here somewhere from what it looks like? The Centralite 3400?, I know it works with Zigbee2MQTT appeared to be the same as my other keypads though never tried it with my NodeRed setup. I'll test it shortly and let you know, should work and if so all you need is that other dongle and my NodeRed flow. You can contact me for help setting those things up, I just want to help out where I can to contribute back to the community in ways that I currently can.

**Comment by nielsfaber** [comment]
> From what I'm gathering here is that the physical keypad can disarm the ha system which is tied to the alarmo front end and so it can work.

Alarmo creates alarm_control_panel entities which can be armed/disarmed within HA through services.
I don’t know how your keypad looks like in HA (if anyone knows a place where to buy it in the EU I would like to know).
But the idea is to create automations to have the alarmo entity arm when the keypad is armed, etc.

If it would be helpful if alarmo has built-in support for ‘syncing’ state with another/external alarm_control_panel, I could work this out.

**Comment by EdwardSoaresJr** [comment]
@f3rr311 I can not find my old keypad that is similar to the Iris but am positive it was the same inside of Zigbee2MQTT as my current keypads and confirmed as much looking it up on zigbee2mqtt website.

@nielsfaber Here is the Zigbee2MQTT link on my current keypads
https://www.zigbee2mqtt.io/devices/XHK1-UE.html

Here is the link to the 3400-D which is the same as the Iris I think that f3rr311 is using.
https://www.zigbee2mqtt.io/devices/3400-D.html

From what I can see between these and all other current keypads supported by Zigbee2MQTT is that they all support the same ZCL specifications and even the payloads appear to be the same.

`Valid mode values as per ZCL specifications are disarm, arm_day_zones, arm_night_zones, arm_all_zones, exit_delay, entry_delay, not_ready, in_alarm, arming_stay, arming_night, arming_away.`

@nielsfaber It looks like the Iris is discontinued as far as finding one, I don't mind sending you an XHK1-UE keypad to help with development if you can not find a suitable device locally as they are only $40 new here from Xfinity.

**Comment by erwintenbrink** [comment]
@nielsfaber I saw you are based in the Netherlands, just like I am. I am interested in the keypad connection with alarm as wel. If neede you could borrow one of my xfinity keypads. They are unavailable in shops in the Netherlands.  Guess it will safe shipping and import Costs. I got 2 diverent versions at home at the moment.

**Comment by nielsfaber** [comment]
Owning one would be the best starting point to develop (and maintain) built-in support for it.

@erwintenbrink Borrowing one would be a good option, however I cannot commit to a timeline (my spare time for this project varies) so you might need it back before things are done. And since Alarmo is quite new (and knowing things in HA change quite often) I think the risk for future changes is quite high, so from maintenance point-of-view I think I would rather own one myself.

@EdwardSoaresJr If you could send one from US this would be great as I still haven't been able to find a shop myself.
However for me $40 + shipment + vat (I guess total €60) is still a bit steep, especially since I don't think it will become part of my home security system (I operate Alarmo from Google Home).

My proposal is to divide the cost between all stakeholders, I count 4 here including myself.
I really hope people don't take this as greedy, please consider i am probably spending ~10 hours of free time to make this happen.
It would come down to around €15 per person, which I think is a pretty small amount.
There is also a previous topic about this (https://github.com/nielsfaber/alarmo/issues/202), perhaps they are willing join as well, making the cost even lower.
If you do want to participate, please donate some [coffees](https://www.buymeacoffee.com/vrdx7mi) and mention that it is intended for this little experiment, I will arrange things with Edward once the amount is reached (otherwise I will refund all).
I don't want to make people feel obliged to contribute, it's just a proposal.
Also I cannot give guarantees for success, so there is also a risk (as with any crowdfunding). 
Ofcourse I will keep you up-to-date with the progress and the result.

**Comment by EdwardSoaresJr** [comment]
@nielsfaber my email is on my GitHub profile, contact me so we can work out some details.

**Comment by erwintenbrink** [comment]
@nielsfaber i got some of these keypads placed on marktplaats. If i see your calculation above i think that will be cheaper. Maby get in touch in private?

**Comment by EdwardSoaresJr** [comment]
Well this is embarrassing I am sitting here trying to pair a custom device I just flashed firmware to and my old keypad paired with the system. It is in the house somewhere :)
![keypad_og](https://user-images.githubusercontent.com/10336569/142977234-46c3dc79-076f-49e6-9510-bbd58a179921.PNG)

**Comment by jeffphilly** [comment]
Id love to support the cause. Ill buy another one and mail it to you if that would help. Alarmo is amazing and I would love to see the keypad get integrated.  my email is in my profile.

**Comment by nielsfaber** [comment]
@jeffphilly Little has changed regarding this feature in the past month. 
My proposal for crowdfunding to buy a keypad to support the development has not led to any results yet. 
Which model of keypad would you like to see integrated?

I saw just now that for the Ring Alarm Z-wave Keypad someone already made a [blueprint](https://community.home-assistant.io/t/synchronize-ring-alarm-keypad-v2-with-alarmo/349461) for Alarmo, it looks quite promising.
So far we have been discussing the Centralite 3400 / Xfinity XHK models here (seem to be quite the same, both are zigbee based), I might either create a blueprint for them or integrate support within Alarmo.
If someone else is willing and able to create and maintain a blueprint for these devices (and owns one), that could also be a good solution.

I don't expect you to buy and send such a device own your own due to the costs involved, but it would definitely put things in motion. Your email address is not exposed on your github profile, so I cannot contact you directly.

**Comment by jeffphilly** [comment]
@nielsfaber Just added my email to my profile, Shoot me an email and I will figure out how to get you one. Alarmo is amazing and if I can contribute in this small way i would love it!

**Comment by chino-lu** [comment]
FIY: there is a blueprint which is working quite good:https://community.home-assistant.io/t/zigbee2mqtt-sync-keypad-and-alarm-control-panel-states/345311/19

just be aware, there is an issue with zigbee2mqtt 1.22.2-1

**Comment by nielsfaber** [comment]
For who is still interested in this: I made a blueprint to connect a zigbee2mqtt keypad to Alarmo: https://community.home-assistant.io/t/zigbee2mqtt-control-alarmo-via-keypad/420016. 
It can probably modified to support other keypads, ZHA, Zwave, etc.
I think it's better to leave this outside of Alarmo, since the implementation is device-specific.
