### ISSUE TITLE
Allow open after arming for contact sensors

### ISSUE THREAD

**Issue by MarpleA** [nielsfaber/alarmo#324]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
With motion sensors there is an option "Allow open after arming". This prevents Alarmo to trigger a failure in case one of these sensors is still active while arming.
Please add the same option to contact sensors. Reason is, that I'd like to arm Alarmo even if windows are still open or tilted.

### Additional info
 It could work the way, that these contact sensors are not taken into account for alarming unless they become closed and opened again.

**Comment by nielsfaber** [comment]
My feeling is that it will add complexity and misunderstanding for the users, without any benefit for security.
But I guess I don't understand the use-case for this.
Could you explain a scenario for your home?

**Comment by MarpleA** [comment]
Hi Nils,

yes, of course. My use case is quite simple. I often leave the house while leaving some of the windows tilted. Especially in summer times. This way I can't arm Alarmo. 
If one could arm Alarmo even though some windows are still open, at least for the closed windows and doors the alarm triggers in case of opening. Think about doors and windows on ground floor which should be protected while windows on second floor are not that critical.
Another use case but maybe more complex to realize, is:
your window is open, you arm Alarmo with a leaving time of 1 minute and after that, you close the window and leave home. Currently you get a failure immediately after arming.

**Comment by nielsfaber** [comment]
> If one could arm Alarmo even though some windows are still open, at least for the closed windows and doors the alarm triggers in case of opening. Think about doors and windows on ground floor which should be protected while windows on second floor are not that critical.

For this you can make use of the bypassing functionality. You can configure a window sensor to be bypassed automatically when it is open while you arm. In this case the sensor will be temporary eliminated/ignored from the alarm, until next time the alarm is armed.

I think its very important that the user selects which windows may be bypassed and which not, because ofcourse a window could be accidentally left open

> your window is open, you arm Alarmo with a leaving time of 1 minute and after that, you close the window and leave home. 

I would say arming the alarm is one of the last steps you do before leaving the house.  I don't picture people will run upstairs to close some windows in that time..

Also I would say the user should be outdoors by the time the exit delay is over. If you are still in the house afterwards, you will also trigger the alarm with motion.

> Currently you get a failure immediately after arming.

You can choose to get a failure at the moment of arming or after the exit time is expired. 
I would say for windows you want to know at the moment of arming, but a door can be open until you close it for exiting the house.

I still have the feeling the current functionality in place covers your needs. Is there anything I am overlooking?

**Comment by Celer21** [comment]
Hi, 
the automatic bypassing on opened windows is great solution. But it would be nice to trigger bypassed window (sensor) if it changes state (from open to close...).

**Comment by MakerLab-Dev** [comment]
> Hi, 
> the automatic bypassing on opened windows is great solution. But it would be nice to trigger bypassed window (sensor) if it changes state (from open to close...). 
> 

I totally agree, having that feature would be very helpful
Everytime I close a window I have to disarm and arm the alarm so that it picks up that window in case it gets opened again
