### ISSUE TITLE
Alarm panel kepad showing

### ISSUE THREAD

**Issue by tomlut** [nielsfaber/alarmo#327]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
[What you expected to happen]
The core Lovelace alarm panel card keypad to not show if the alarm is in the disarmed state and Use Arm Code is off.

### Actual behavior
[What actually happened]
The keypad is always visible. 

### Steps to Reproduce
[Explain how to see the behaviour]
Set Use Arm Code switch off:

![Screenshot 2021-11-20 at 12-15-15 Alarmo - Home Assistant](https://user-images.githubusercontent.com/10679300/142709083-aba7edcc-5363-44a9-abcc-f86ee263f1ec.png)

Disarm the alarm:
![Screenshot 2021-11-20 at 12-15-37 Overview - Home Assistant](https://user-images.githubusercontent.com/10679300/142709091-f956d141-4553-447e-89bc-9fcc8bb5adca.png)

Keypad should not be visible in this case.

**Comment by nielsfaber** [comment]
The Lovelace Alarm Panel card only looks at the `code_format` option for determining whether the keypad should be visible (see [code](https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/cards/hui-alarm-panel-card.ts#L182)).

This property only is [intended ](https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/#code-formats)for indicating whether the code is numeric or text.

The property `code_arm_required` (as [defined ](https://github.com/home-assistant/core/blob/dev/homeassistant/components/alarm_control_panel/__init__.py#L218)in the native alarm_control_panel entity) is not evaluated by the card, while Alarmo implements it (together with `code_disarm_required`, those two are essentially controlled by the switches you mentioned).

Summarizing I think the problem is on the side of the Lovelace Alarm Panel card, and on the side of Alarmo I cannot do much to improve this.
Since the card lacks some more essential features, there is an [Alarmo Card](https://github.com/nielsfaber/alarmo-card) which offers a slightly better experience.
It will hide the keypad when not applicable, but also it will also show reason why arming failed, and some more additions.
My recommendation would be to use it instead, or file a bug report in HA frontend for this.

**Comment by tomlut** [comment]
Interesting. I was wondering how bwalarm managed to do it and found this:

https://github.com/akasma74/Hass-Custom-Alarm/blob/master/custom_components/bwalarm/alarm_control_panel.py#L718

Looks like it sets `code_format` to `none` when disarmed and an arm code is not required. 

As your integration is just an easy way to set up the required parts of a manual alarm I guess requesting this is beyond the scope of the project. 

I was hoping to use the core card as I have quite a bit of card-mod customisation of the core card that does not work with the alarmo card. Looks like I will have to spend the to do this. I hate css :)

**Comment by nielsfaber** [comment]
> Looks like it sets code_format to none when disarmed and an arm code is not required. As your integration is just an easy way to set up the required parts of a manual alarm I guess requesting this is beyond the scope of the project.

This is definitely worth considering. 
For me a small change so if it helps you and doesn't bother others, I'm fine with it.

> I was hoping to use the core card as I have quite a bit of card-mod customisation of the core card that does not work with the alarmo card. Looks like I will have to spend the to do this. I hate css :)

I am not a user of card-mod, but I know it is used by a lot of people. I do want to walk the extra mile and make alarmo-card card-mod-friendly. But I would need some pointers on what to change for this.
If you are willing to assist on this, please open a github issue in alarmo-card for follow-up.

I will re-open this and make the update for code_format (when I find the time to do so).

**Comment by tomlut** [comment]
Nice one. Thanks Niels.

**Comment by nielsfaber** [comment]
I made some changes to accommodate this (https://github.com/nielsfaber/alarmo/commit/82b428f11199abe80e92f861473399c95f8ebb69).
Will try to release it soon.

Disarmed (left=Alarmo card, right=Alarm Panel card)
![image](https://user-images.githubusercontent.com/16861605/143590240-f18667fd-17f6-4e8f-82a9-30a46ebb1954.png)

Armed(left=Alarmo card, right=Alarm Panel card)
![image](https://user-images.githubusercontent.com/16861605/143590297-a3c4a8eb-0a41-470a-aeb4-838f6015bc7e.png)

**Comment by nielsfaber** [comment]
This is implemented in the latest release (v1.8.0).
Please update Alarmo locally and check whether it works as you would expect.
If so, you can close the issue. Otherwise, please let me know.
Thanks for the help 👍

**Comment by tomlut** [comment]
Thanks for the update.
