### ISSUE TITLE
Arm service seems to be ignored by Alarmo

### ISSUE THREAD

**Issue by LeclercqG** [nielsfaber/alarmo#330]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
Calling the service "alarmo.arm" on the entity "alarm_control_panel.alarmo" should arm the system every time I call it.

### Actual behavior
Quite randomly, calling the service "alarmo.arm" on the entity "alarm_control_panel.alarmo" does nothing and require several call to arm the system.

### Steps to Reproduce
Call the service from developer tool without parameter other than entity_id
Call the service from NodeRED node (Simple node input -> Call Service) with just the entity_id
Ask Alexa to Arm the alarm system, it says OK.
Look at the state of Alarmo which will randomly still at "disarmed" instead of "arming".

### Information on my issue 
I'm using alarmo as an easy way to create an alarm system. I'm not using a code but other methods (Node-RED with NFC tag automation, Alexa Cloud Integration, HA iOS app) that are calling the service "alarmo.arm" on the entity "alarm_control_panel.alarmo" to arm the system. I have only one alarm system (the away one).
Sometimes (and I didn't find yet a common point where it doesn't work), the call on the service seems to do nothing like Alarmo is not receiving the call or just ignores it.
I can tell it is not coming from my activation methods because :
On Node-RED, the node is displaying that the service is called properly.
In the log event viewer, I can see Alexa logging that it has called the service properly but again Alarmo seems to ignore it.
It seems I encounter the issue with developper tool too. Logs are not helping in this case.
However, I never had the problem when just using the arm button on the Lovelace card.
I, of course, tried to reinstall Alarmo, I restarted HA and the whole system several times.
I'm running HA 2021.11.3 and Alarmo 1.7.6.

I should also add that the disarm service works properly and only the arm service is causing an issue here.

I'm not sure it is a bug (and I'm sorry if it is not) since I find it quite strange I'm the only one reporting the issue on such a core function but as my service are called properly, I don't see how the issue couldn't be on Alarmo's side.

Thanks for your help on this.

**Comment by nielsfaber** [comment]
I cannot reproduce your issue.
I am not a node-red user, so I only tried via Developer Tools.
After 10x consecutive arm/disarm actions I gave up trying.

Don't get me wrong, I do take this serious since I can imagine it is very bothering if the alarm refuses to arm completely.

Could you try to enable debug logging in alarmo, see if you can catch a log when it happens?
You can do so by adding this to the configuration.yaml file:
```
logger:
  default: warning
  logs:
    custom_components.alarmo: debug
```
Also, could you find some more clues like:
- Does it happen on the alarm master entity or just an area entity (in case you don't use areas you have a single area entity)?
- Does it happen with exit delay configured or with direct arming or does not matter? (I tried with arm_home and zero delay only)
- Code used?
