### ISSUE TITLE
 Something went wrong!

### ISSUE THREAD

**Issue by Elitaz** [nielsfaber/alarmo#335]
Message format incorrect: extra keys not allowed @ data['is_admin']

Response error: 400

Please report the bug.

**Comment by jazzyisj** [comment]
As noted in the release notes for the latest release, that parameter has been removed from Alarmo. 
Remove it from your configuration.

https://github.com/nielsfaber/alarmo/releases

**Comment by Ronniec10** [comment]
Hi ... I didn't understand what the solution to this problem is, friend. Can you say more clearly what needs to be done to solve?

**Comment by nielsfaber** [comment]
Please fill in the bug report template.
I cannot help without extra info (like when this is shown)..

**Comment by Ronniec10** [comment]
*Something went wrong!*
Message format incorrect: extra keys not allowed @ data['immediate']

Response error: 400

Please report <https://github.com/nielsfaber/alarmo/issues> the bug.

Il giorno lun 29 nov 2021 alle ore 16:17 Niels Faber <
***@***.***> ha scritto:

**Comment by nielsfaber** [comment]
@Ronniec10 
Please fill in the bug report template.
I cannot help without extra info (like when this is shown)..

**Comment by Ronniec10** [comment]
Amico ...continua a non lavorare per me il tuo Alarmo. Continua ad uscire
quel messaggio di errore che ti ho postato ieri. Puoi darmi una mano?
Ho provato già a disinstallare e poi a reinstallare ma con scarsi risultati.
Puoi darmi una mano per trovare la soluzione? Ti prego non dirmi di
riempire moduli... Cerca di darmi una spiegazione "veloce " ma valida.
Ti ringrazio molto

Il lun 29 nov 2021, 21:15 Niels Faber ***@***.***> ha scritto:

**Comment by jazzyisj** [comment]
@Ronniec10  You are never going to get help here, or anywhere else, with that attitude.  You weren't even the person who opened this thread.  The reason you are asked to fill in the form is because you are not providing enough information for him to help you.  Hell we're not even sure if you had the same problem as the initial poster.

Rudeness to someone who has spend undoubtedly countless hours to create something which is offered to you for free is just not acceptable.  Everyone else who has an issue fills out the form.   It's a simple request.  Either fulfil it or figure it out on your own.

**Comment by Ronniec10** [comment]
Amico non pensavo di essere stato maleducato nei tuoi confronti.
Io al contrario di quello che tu dici apprezzo molto il prodotto che hai
creato infatti dal momento che non funziona più ( per me ovviamente) mi
dispiace e vorrei che tornasse a funzionare proprio perché lo apprezzo
moltissimo.
Potresti gentilmente dirmi quale modulo devo usare ? Non lo ho trovato . Mi
manderesti cortesemente un link ?
Spero di non aver urtato i tuoi nervi anche questa volta amico perché non è
certo la mia intenzione.
Cerco di risolvere da solo ma mi rendo conto che con tutti i tentativi
ricevo sempre lo stesso errore, per questo mi occorrerebbe una mano.
Grazie.

Il gio 2 dic 2021, 00:23 jazzyisj ***@***.***> ha scritto:

**Comment by nielsfaber** [comment]
@Ronniec10 Please take the effort to speak in English. You cannot expect everyone to adapt to your native language (mine is not English either).
The issue you are reporting looks different than discussed in this thread, please open a [new issue](https://github.com/nielsfaber/alarmo/issues/new?assignees=&labels=bug&template=bug-report.yml) for it.
I recommend you to check the version number you are running, we are now at v1.8.1. The version is in the corner of the screen on the Alarmo pages. I think you have a browser cache problem. 

I closed this topic because it is going nowhere. Feel free to try again.
