### ISSUE TITLE
Camera Snapshot Grouping

### ISSUE THREAD

**Issue by trankillity** [nielsfaber/alarmo#348]
### Checklist
- [✔] I checked for similar existing requests (both open and closed) before posting.
- [✔] My request is generic, other users may benefit from it too.

### Proposal
Create a way to group cameras with clusters of trigger sensors. This could then be extended to allow automatic snapshotting and sending of camera image in notification when alarm is triggered.

### Additional info
- Somewhat related to #290, but extending significantly upon it
- Would need a custom delay before snapshot is taken, likely 5s+ to get a clear view of intrusion

**Comment by nielsfaber** [comment]
As mentioned in your other request, I currently don't have any plans for implementing support for cameras in Alarmo.
Ofcourse this doesn't mean that we cannot discuss it, particularly if other users would start showing interest for this as well the priorities can shift.

> Create a way to group cameras with clusters of trigger sensors.

Could you elaborate on this? What is the purpose/meaning of such group?
I don't really see a link between cameras and sensors, besides for automating snapshots as you mentioned.

Some considerations from my side:
* Is a snapshot always a picture or can also be a video?
* Is it true that cameras which have person detection usually expose a separate binary_sensor for this, or is this signalled via an attribute of the `camera` entity?
* I have my doubts whether Alarmo should be tasked with linking motion detection to camera activation.
I would expect that a modern camera would have built-in support for this, and that a PTZ camera would even start following the motion of an intruder. Is a camera in HA just a video stream or is some intelligence provided by the platform?

Would like to get an idea of which functionality is in common between different camera integrations, and which is specific to certain.
I am asking these questions since I don't use cameras for my home, would like to get an understanding of how it should be integrated.

**Comment by trankillity** [comment]
The link between them would be exactly as you described, purely for automating the snapshotting.

For instance:

_Lounge Camera Group_
- Lounge Camera
- Front Door Contact
- Lounge PIR

In such a grouping, a snapshot would be generated for the _Lounge Camera Group_ when either the sensors included in it were triggered (after a defineable delay, no use taking a snapshot right as a door opens, or you won't see anything).

As for the other considerations:
- The `camera.snapshot` service call only produces a picture, so makes sense it would only be a picture not a clip.
- Usually, they do have a separate presence binary sensor for person detection (as well as a separate binary sensor for motion detection).
- I agree about leaving the camera activation external. Any good NVR will already handle that. This request was purely about making it easier to make notifications from Alarmo richer/more useful.

I use the Synology Surveillance Station as my NVR with Wyze Cams using RTSP as my cameras, so can certainly answer any more specific questions about that. I will also be installing a Nest Battery Doorbell soon, but can't imagine many use cases for that within Alarmo as it's mostly self-contained functionality.

**Comment by augustodinizl** [comment]
> The link between them would be exactly as you described, purely for automating the snapshotting.
> 
> For instance:
> 
> _Lounge Camera Group_
> 
> * Lounge Camera
> * Front Door Contact
> * Lounge PIR
> 
> In such a grouping, a snapshot would be generated for the _Lounge Camera Group_ when either the sensors included in it were triggered (after a defineable delay, no use taking a snapshot right as a door opens, or you won't see anything).
> 
> As for the other considerations:
> 
> * The `camera.snapshot` service call only produces a picture, so makes sense it would only be a picture not a clip.
> * Usually, they do have a separate presence binary sensor for person detection (as well as a separate binary sensor for motion detection).
> * I agree about leaving the camera activation external. Any good NVR will already handle that. This request was purely about making it easier to make notifications from Alarmo richer/more useful.
> 
> I use the Synology Surveillance Station as my NVR with Wyze Cams using RTSP as my cameras, so can certainly answer any more specific questions about that. I will also be installing a Nest Battery Doorbell soon, but can't imagine many use cases for that within Alarmo as it's mostly self-contained functionality.

man, its easily "achievable" with automation/blueprint... i think that home assistant is perfectly capable of achieving your need without trying to make someone else change something that works, just because you don't search/think enough to solve your own needs

FIY, here is the "starting point" to you achieve your needs with some tinkering:
https://community.home-assistant.io/t/notification-with-camera-snapshot-with-blocking-condition-and-clickaction/258040


sorry @nielsfaber for that, but i'm just trying to help

**Comment by trankillity** [comment]
> man, its easily "achievable" with automation/blueprint... i think that home assistant is perfectly capable of achieving your need without trying to make someone else change something that works, just because you don't search/think enough to solve your own needs

Yes, it's easily "achievable" in Home Assistant using Blueprints/automations, but then again - so is absolutely everything that Alarmo does as a custom component. You're suggesting that I'm asking to re-invent the wheel, which is true - but it's also exactly what Alarmo is doing as a component. The author has just done a brilliant job of simplifying the process.

So I feel like you're missing the point of the request - to make common security-based features as easy as Alarmo makes creating a alarm system. If the author thought it was irrelevant or not within the scope of the project, they could have easily closed the feature request as out of scope.

**Comment by liljenstolpe** [comment]
Maybe I can put a bit of color around why this might actually belong in alarmo, @augustodinizl and @nielsfaber.  I want to use noonlight as a monitoring service, and they can use video verification to reduce false alarms.  Also, some LE departments (at least in the US) will respond faster if they are told that the alarm is video verified.

So, if I take a number of sensors in a given area (glass break, door, window, motion, etc.), say a room, and if any of them are triggered WHILE they are armed (i.e. motion isn't armed when in 'home mode' but is armed in 'away mode') - which is why this would be much more useful to have in alarmo (rather than duplicating the armed state logic a second time), then take an image and ship it off to noonlight as part of the alarm event stream.

Yes, it can be done outside alarmo, but you are then duplicating armed state of each sensor a second time, unless I am missing something.

Christopher
