### ISSUE TITLE
Actions panel hierarchy/structure re-work

### ISSUE THREAD

**Issue by trankillity** [nielsfaber/alarmo#349]
### Checklist
- [✔] I checked for similar existing requests (both open and closed) before posting.
- [✔] My request is generic, other users may benefit from it too.

### Proposal
I believe the Actions panel (and the documentation for the Advanced Actions) are more convoluted than they need to be. An action automation should always be a reaction to an event occurring, so logically it should flow `trigger event -> action(s)`. Using this philosophy, you can remove the separation between the two current action types (notifications and actions) and make the Actions panel function more like the standard HA automations panel, with multiple actions per trigger. I feel like this would make the flow significantly clearer/easier and would be more inline with the standard HA implementation of `trigger event -> action(s)`.

### Additional info
A few examples of how the flow would work:
- Event: failed to arm (extending included example, handled through Alarmo instead of HA automations)
-- Action: Notify phone 1
-- Action: Notify phone 2
-- Action: TTS service announcement "Couldn't arm because of {{open_sensors}}"
-- Action: Flash lights to warn of failed arm
- Event: alarm triggered
 -- Action: Camera in offending area snapshot
 -- Action: Notify phone 1, attaching snapshot
-- Action: Notify phone 2, attaching snapshot
-- Action: TTS service announcement "Cameras recording, alarm triggering in 60 seconds. Disarm to prevent."
-- Wait: 60 seconds
-- Action: Trigger siren
- Event: arm away
-- Action: Notify phone 1 that home is armed
-- Action: Lock front door
-- Action: Close garage
-- Action: Service - set away mode in NVR

**Comment by nielsfaber** [comment]
We are not on the same page with this.
I don't think it is wise to make a copy of the HA automation editor.
It would involve a lot of effort and maintenance, which I am not looking for.

I prefer to limit the support to basic tasks with a simple interface, and advise to using HA automations for anything that goes beyond what's possible from within Alarmo.
If you ask me, the HA automation editor is bloated by having too many things which can be configured.

To respond to your use-cases:
* I might be able to add support for `TTS` notifications next to `notify`, I guess the main reason why it is not in place yet is that I don't use it personally.
* Configuring flashing lights has been requested before,  but I am holding back from adding support for it since there is no straightforward way to trigger this (AFAIK). Some bulbs might support native flash effects, others might need to be toggled repeatedly. Additionally users might want to choose color, duration, etc. It seems too specific to add. I think this is possible to setup already through YAML configuration.
* Implementing a waiting time inside the triggered state is a bad idea in my opinion. I would rather recommend to set the correct delay time for entry, such that triggered state is the final state.
* Support for cameras is not in scope for now. I think it will be a very long road before Alarmo will be able to support most use-cases, I think the priorities are currently elsewhere.

**Comment by trankillity** [comment]
I think there may be some confusion here. The examples were purely that, examples. The examples weren't what I was requesting. More a logical restructuring of how the Actions panel works.

As mentioned in the original description, all actions are a result of an event occurring, so there's no logical reason that you should have to duplicate actions over events based on whether the action you want to fire are notifications or actions. This would drastically reduce the number of actions needed to achieve the desired results.

This would involve two main aspects:

- Restructuring the panel to be event-first, rather than action-first
- Allowing multiple actions per event

Let's take an overly simplified example using the current UI to really illustrate it:
_Send a notification to an Android phone and an iOS phone, then turn on a light when the alarm is triggered._
**Current Implementation**
- New Notification
- Select "Alarm is triggered" event
- Choose Android target
- Fill in message details
- Change name
- Save

- New notification
- Select "Alarm is triggered" event
- Choose iOS target
- Fill in message details
- Change name
- Save

- New action
- Select "Alarm is triggered" event
- Choose light target
- Choose "Turn on"
- Change name
- Save

Result: Three automations for one event

**Proposed Implementation**
- Track Event button
- Select "Alarm is triggered" event
- Add Action button
- Choose Notification
- Choose Android target
- Fill in message details
- Add Action button
- Choose Notification
- Choose iOS target
- Fill in message details
- Add Action button
- Choose Automation
- Choose light target
- Choose "Turn on"
- Save

Result: One automation for one event
