### ISSUE TITLE
Provide support to send passcode and custom outgoing MQTT messages

### ISSUE THREAD

**Issue by sparkydave1981** [nielsfaber/alarmo#35]
For Alarmo to interface with and control an external alarm system there is a requirement to send outgoing MQTT messages to the external alarm.  Since the external alarm is a security device it requires a passcode.  Doing so allows HA to control the external alarm system such that HA and the external Alarm system remain synchronised.

Please provide support to allow sending of passcodes in the outgoing MQTT messages.

Please also allow for subcommands to be sent in the MQTT message.

ie:
```
JSON Payload template
   {
    "password":"1234",
    "Command":"arm",
    "Subcommand":"0"
   }
```

Having subcommands will also allow for controlling multiple 'Areas' in future.

**Comment by nielsfaber** [comment]
I was not aware that your system requires such messages to be sent TO the alarm panel.
I thought that this is the kind of message would be received FROM the alarm panel.

I think this is a _very_ specific functionality that might help for your use-case, but will not provide any extra functionality for others.
Alarmo is not designed with the goal to send commands to another alarm panel, it _is_ the alarm panel.
I don't think there is any alarm system in HA (including BWalarm) that offers the functionality you are looking for.
It also doesn't really fit in the scope of Alarmo.

IMO it's bad practise to 'connect' multiple alarm panels together. 
You can never ensure they are in sync, since they have their own delay logic, sensors and actions.
There is currently no functionality either for triggering Alarmo through MQTT (only a sensor can trigger it).
I would recommend you to consider migrating to a centralized approach having a 'master' alarm controller.

The best I could do to help you is add a command output topic.
This topic would send a message whenever Alarmo is armed or disarmed (optionally with the code that was used as well).
The payload structure, however will not be identical to what you're looking for, so you will have to make changes elsewhere to make it work.
An example of what Alarmo could send, would be:
```
{
  command: "arm_away",
  code: "1234"
}
```
This is the same format as the command input topic.

The subcommands / areas you are mentioning, are currently out of scope as well.
This could be added at some point (if a lot of users want such as function), but i don't want to add functionality for this right now.

**Comment by nielsfaber** [comment]
Hi Dave,
I thought about this some more and decided that it would be a good addition for Alarmo to be able to control an external alarm system.
The current implementation seems to match with the [manual MQTT](https://www.home-assistant.io/integrations/manual_mqtt/) integration, where you have an external GUI (like wall display) for controlling the alarm in HA.

I would like to extend this with a "command out topic", to be able to arm an external system.
Additionally I want to add support for [JSON templates](https://www.home-assistant.io/integrations/sensor.mqtt/#json-attributes-template-configuration) for the "command in topic", such that it is possible to define a mapping between variable names used by the external system and the names used by Alarmo.
The idea here is that Alarmo should be flexible when it comes to the format of the input+output MQTT payloads, such that the external system can stay as-is.

I still have some concerns regarding corner-cases, such as: 
What to do if the external system cannot arm (due to an open sensor), how will Alarmo be notified of this?
And how to keep the delay times in sync?
I was hoping you could help me out here by discussing the desired behaviour for such scenarios.

**Comment by sparkydave1981** [comment]
Potentially not quite related to this issue as such but it would be nice to slightly change the wording of the MQTT topic input items in the Alarmo GUI. 
Currently we have:
State topic- topic on which state updates are published (this is ok, states outbound from Alarmo)
Event topic- topic on which alarm events are published (also fine)
Command topic-topic on which arm/disarm commands are sent (I feel this should be reworded to say 'topic which Alarmo listens to for arm/disarm commands)

**Comment by nielsfaber** [comment]
Agreed, I just fixed it in https://github.com/nielsfaber/alarmo/commit/2dca089a1ebb8cf5a98832af4f318fad36cc943d
Please note that users are invited to contribute improvements to the translations as well (its just a json file).

This issue is indeed very old.
The requested functionality does not fit in the concept for alarmo currently, and the concerns are still valid.
I'm still hoping you can manage to integrate your alarm without any big changes from my side.
Sounded like you were quite close, so I keep my fingers crossed.
