### ISSUE TITLE
Use/Extend Blueprint Target Selector

### ISSUE THREAD

**Issue by trankillity** [nielsfaber/alarmo#350]
### Checklist
- [✔] I checked for similar existing requests (both open and closed) before posting.
- [✔] My request is generic, other users may benefit from it too.

### Proposal
The [Target selector](https://www.home-assistant.io/docs/blueprint/selectors/#target-selector) functionality that was added to Blueprints would be the perfect fit (and maintain consistency) for Alarmo action targets. Hopefully it would be fairly easy to implement/extend from the Blueprints implementation.

### Additional info
- Can still be restricted to certain entity `device_class`
- Solves issue of multiple targets easily

**Comment by nielsfaber** [comment]
Alarmo does not support targeting areas or devices, only entities.

I personally don't make use of the target selector since the difference between an entity and device in HA is rather vague to me (it was never properly introduced if you ask me), and I did not set up areas either.

In addition, it is not possible for me to re-use UI elements from HA, since they are only loaded in the frontend when accessing certain pages and I cannot request the loading of these elements from Alarmo's side.

I currently implemented my own 'alarmo selector' which also allows picking multiple entities (where applicable).
Is there something specific which you are missing?

**Comment by trankillity** [comment]
Ahh, that sucks about not being able to re-use their Blueprint selector component. Was hoping it would save you making your own selector.

As for device vs entity, that took me a while too. Entities seem to me to be distinct child objects with defined functions of devices. Devices appear to have attributes, states, events, and functions. Entities themselves only have attributes and states from what I understand. The distinction isn't stark enough IMO, but devices are certainly capable of more.
