### ISSUE TITLE
Pending step is not executed

### ISSUE THREAD

**Issue by Atreiide** [nielsfaber/alarmo#364]
### Alarmo Version

v1.8.1

### HA Version

2021.12.7

### Bug description

Hi,

First of all, thanks a lot for this great work 

I configured pending time before alarm is triggered (20 seconds), but alarm is triggered immediately when a sensor state has changed, like a door opened

Tried several delay, ha restart, plugin reload but same issue : no pending step

Here is the setting and the log : 

https://ibb.co/VtCdcnR
https://ibb.co/HgzFfcy

All is working (arm, disarm, action) but not the pending time

**Comment by nielsfaber** [comment]
Please check the sensor settings:
![image](https://user-images.githubusercontent.com/16861605/148196911-69e90b64-c755-40f7-9d09-df7bc7b8b5a8.png)

By default a window sensor will not have entry delay, because it is not used for entering the house.
If you want to change it, turn on the 'use entry delay' setting.

**Comment by Atreiide** [comment]
Ok. My bad. I thought that it was by default...and didn't search enough on doculmentation. So, I'm gone pay you a coffee ;-)

**Comment by nielsfaber** [comment]
No problem. Documentation is quite limited so I understand things are not clear for everyone. Hope you can configure things to your liking. Thanks a lot for your donation, it is a good motivator for spending time on improvements!
