### ISSUE TITLE
What Siren?

### ISSUE THREAD

**Issue by kiki3529-0** [nielsfaber/alarmo#37]
Hello
What Siren do you use?
I have gateway xiaomi, which could not be directly triggered, but just put alarm on or off, it can't command and play siren directly
Thanks
Michael

**Comment by nielsfaber** [comment]
A siren device is typically a `switch` entity in HA.
From what I can see, the Xiaomi Gateway the siren is not directly switchable.
You could consider to create a script for turning it on and off.
This post seems to have a lot of information: https://community.home-assistant.io/t/xiaomi-gateway-alarm/44230/30?u=neliss

**Comment by brandondb1** [comment]
There are dozens of home security sirens on Amazon or similar.  Just get a 12v power supply and a Sonoff Basic with Tasmota installed and you have an MQTT switch that triggers a siren from Home Assistant.  Send me a note if you need more details.

**Comment by kiki3529-0** [comment]
Hello
Yes could you please more details about Mqtt?
Is it possible to chose a 220v used with tuya 220v sockets?
Thanks

**Comment by brandondb1** [comment]
Hi,

The horns I have seen work on 12v DC, so you need a power supply to provide
that current.  You can easily find a 220v AC to 12V DC power supply.  I use
a Sonoff Basic because it is easy to wire - 220v mains to Sonoff, then
sonoff to power supply (220v, remember to wire the ground together around
the Sonoff), then power supply to horn (12v)  In this way, the Sonoff
switches the power supply on and off, which activates/deactivates the horn.

A 220v tuya socket would work as well, but you'd have to switch it on and
off via the Tuya app/Tuya Homeassistant integration unless you have put
tasmota on the Tuya plug.

For MQTT, whether on a Sonoff Basic or Tuya plug, you would need the
Tasmota firmware installed.  There are lots of resources on how to flash
Tasmota onto various devices.

You need to install the MQTT broker add-on on Home Assistant and configure
it - this is simple and well documented.  Make sure to turn on Auto
Discovery.

Then with Tasmota on your device, go to the web interface for tasmota,
connect it to your Wifi, then configure the device type, and the MQTT
settings (MQTT broker address - same as yur HASS instance, the username and
password you configured in the HASS MQTT add-on).  You can then go into the
console on Tasmota and issue the command [setoption19 1] (without
brackets), which will turn on Homeassistant Autodiscovery, and the device
should appear under the MQTT integration in HASS...from there you control
it like any other switch - switch on = horn on.

Hope this helps!

**Comment by nielsfaber** [comment]
@kiki3529-0 My recommendation is to use zigbee for wireless connection (rather then WiFi)
Maybe this is an option: https://a.aliexpress.com/_BUBtal
A good siren should have internal batteries such that they work when power is removed.

**Comment by kiki3529-0** [comment]
Hi
Thanks you very very much
I will   informed you
Michael

Le mer. 2 déc. 2020 à 20:56, Niels Faber <notifications@github.com> a
écrit :

**Comment by LasseSLambertsen** [comment]
> A siren device is typically a `switch` entity in HA.
> From what I can see, the Xiaomi Gateway the siren is not directly switchable.
> You could consider to create a script for turning it on and off.
> This post seems to have a lot of information: https://community.home-assistant.io/t/xiaomi-gateway-alarm/44230/30?u=neliss

But how does one actually connect the switch entity to alarmo?

**Comment by nielsfaber** [comment]
@LasseSLambertsen You can configure an action to turn it on when the alarm is triggered, and an action to turn it off when the alarm is disarmed.

**Comment by X1pheR** [comment]
> @kiki3529-0 My recommendation is to use zigbee for wireless connection (rather then WiFi)
> Maybe this is an option: https://a.aliexpress.com/_BUBtal
> A good siren should have internal batteries such that they work when power is removed.

Do you have experience with this one? I'm also on the look for one which obviously works well and stable in HA 😁

**Comment by nielsfaber** [comment]
@X1pheR No, I personally only have experience with: Aeotec Siren Gen5 and  POPP Smoke Detector with Indoor Siren.
Both are Z-wave devices and have considerably higher price tag.
My personal experience with Z-wave is not that good as with Zigbee, so I will not invest more in any Z-wave sirens.
With chinaware electronics there's usually a 'catch': the device may need some exotic battery, the siren sound maybe awful etc.

**Comment by Gowah8** [comment]
I am very much a newbee to HA. As part of the development of my HA system I have set up an house alarm based on ALARMO (much thanks to Niels). For this I purchased what I was led to believe were zigbee sirens:

[https://uk.banggood.com/Zigbees-Smart-Sensor-Wireless-WiFi-Linkage-Smart-Sound-And-Light-Alarm-Horn-Siren-Remote-Controller-Smart-Module-p-1758665.html?rmmds=search&cur_warehouse=CN 6]

However, on receipt it is apparent that these are not zigbee but WIFI ( I have complained to Banggood - and eventually received a refund) and can be installed on your local wifi network using TuyaSmart. However, the HA Tuya integration does not recognise these. But by experimentation I determined that HA does recognise if included via the localtuya integration. This is somewhat a protracted process as to do this you need to known the device local key - how to do this can be found on Github and there are several YouTube videos. Anyway, I eventually got the siren included in HA and after trial and error determined the relevant ID. is 13 - for this the siren flashes red and is very loud for such a small item. Occasionally with inadvertent powering on and off it might loose connection to HA but this can be quickly re-established by switching the siren on and off via the TuyaSmart app, i.e. I have the siren simultaneously linked to both HA and TuyaSmart on my phone. Not perfect but is a start.

**Comment by nielsfaber** [comment]
Im closing this issue since I think this discussion belongs better in the HA forum thread.
The GitHub issues are meant for bugs and feature requests.
