### ISSUE TITLE
Arm modes in scenes always "Arm Home" or "Arm away" and independent of modes in the alarmo settings

### ISSUE THREAD

**Issue by Ehlz77** [nielsfaber/alarmo#384]
### Alarmo Version

v1.8.1

### HA Version

2021.12.10

### Bug description

The arm modes when adding Alarmo as a unit in scenes are independent of the choosen ones in the alarmo settings. I have set up "arm away" and "arm night" but the modes displayed in scenes are "armed away", and "armed home". Also, it does not seem that i am able to "disarm" the alarm in a scene. I am able to manually change this in the scenes.yaml however, so the bug is only in the UI

**Comment by nielsfaber** [comment]
This is a known issue in HA.

I can make an alarm with 4 arm modes:
<img src="https://user-images.githubusercontent.com/16861605/152726528-b212a587-4cef-4f76-a295-f77635429152.png" width="50%" height="50%">

If I click on the circle with the icon, I get the 'more info' dialog with only 2 arm modes:
<img src="https://user-images.githubusercontent.com/16861605/152726592-b0999ca2-68c1-458c-80e1-e2e66c04eb7d.png" width="50%" height="50%">
I guess this dialog is the same when you use the alarm in a scene.
Unfortunately this UI belongs to HA itself, I cannot change it from Alarmo.

The issue has been reported in 2020 already, but is not solved yet, see: https://github.com/home-assistant/frontend/discussions/11287.
I cannot help you with this bug. The.bug is in HA, not in Alarmo.

PS: I am not sure if you can use the alarm in scenes, because you (may) need to enter the pin code for arming/disarming. I don't think you can configure a scene to do this.
