### ISSUE TITLE
Can't see all binary sensors

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#4]
For some reason this alarm panel doesn't see all my binary sensors. E.g: binary_sensor.sm_g988b_is_charging.  May be a good reason for this, but I can't see it because the text in the section for adding sensors is cut off. It gets as far as this "There are no available HA entities that can be configured for the alarm. Make sure to include ent":
![image](https://user-images.githubusercontent.com/1751192/97794398-54ca9c00-1c5e-11eb-8436-2829b04b0245.png)

**Comment by nielsfaber** [comment]
is your sensor type (device class) one of these:
```
          'door',
          'garage_door',
          'gas',
          'heat',
          'lock',
          'moisture',
          'motion',
          'moving',
          'occupancy',
          'opening',
          'presence',
          'problem',
          'safety',
          'smoke',
          'sound',
          'vibration',
          'window',
```

Other types are not supported.
Charging suggests the sensor is not security/safety related?

**Comment by stefanolson** [comment]
You are correct. Device class is plug.  I was able to use that with bwalarm to test the system before I get an actual physical alarm installed. Ordering an alarm in the next few days.

**Comment by stefanolson** [comment]
Weirdly though, binary_sensor.updater is available to alarmo. Don't think it's any of the above? But can't see a device type when I look at it in the debugging tools...
![image](https://user-images.githubusercontent.com/1751192/97796520-c236f680-1c77-11eb-9ae3-4b368bc45d93.png)

Thanks.

**Comment by nielsfaber** [comment]
> Device class is plug. 

I don't think this belongs in an alarm panel.
IMHO its useful that such entities are automatically filtered out.

Regarding:
> binary_sensor.updater is available to alarmo

This is a device without device class.
For now, I don't filter these out. Because I don't know if all sensor integrations properly set the device class.

But most importantly:
> ... to test the system before I get an actual physical alarm installed. Ordering an alarm in the next few days.

You mean you have no intention of using Alarmo?
I don't understand why you make feature requests if so..

**Comment by stefanolson** [comment]
I'm hoping to use Home assistant with a konnected alarm. But I as yet I haven't found a satisfactory alarm panel to use in Home Assistant. Thus why am looking at Alarmo and making requests for features that would enable me to use it. I'm trying to verify that the behaviour will be what I need before purchasing the konnected alarm, Thus wanting to test a sensor activation.

**Comment by nielsfaber** [comment]
As an electronics professional (yes, I live in Eindhoven after all) my recommendation to you is to stay away from Konnected.
If you have a wired alarm system in your house which you want to migrate to HA, there are much better ways.
The ESP devices (microcontrollers) used in Konnected system have a BOM of 3 euros.
The RF antenna is very poor, you will have dropouts when hiding these boards in a cabinet.
I think you will end up throwing it in the bin within 2 years.
If are open to it like I could help you with finding a better alternative.

I'm sure I can develop Alarmo to fit your needs, but it will take some time to get there.
By sharing this project in HA, my intention was to create a discussion on what features would be useful.
The current state is by no means representative for what it will become.

I suggest you to close this issue since we're drifting off.
The plan is to add more descriptive text in the GUI + extend the documentation. It will surely cover the restriced device types.
If you want some support for the hardware part then lets continue by PM.

**Comment by stefanolson** [comment]
I feel like this should be obvious, but can't figure out how to p.m. on github :-(

**Comment by nielsfaber** [comment]
It’s not supported.
But in HA you can.
