### ISSUE TITLE
Would like an audio out feature to add

### ISSUE THREAD

**Issue by WireBucket** [nielsfaber/alarmo#406]
Looking for a media output option to add our own alarm audio. Plus have it output to a speaker or cast to a media speaker on the network.

If the alarm is triggered to allow option to play sound on speakers on the network.

Possible if able to add feature as well to chime as a count down when alarm is arming for away.

**Comment by WireBucket** [comment]
Or to add a pre made automation. I was able to make a automation for audio trigger but no way to input it in as a command

**Comment by nielsfaber** [comment]
I am not sure whether it is possible to create a generic support for this.
From my own experience, the possible actions for media players vary a lot.

IMO the most suitable service for this would be:
<img src="https://user-images.githubusercontent.com/16861605/159118981-a483ea7f-0b77-47c2-922b-055b7210abb7.png" width="75%" height="75%">

I am not sure whether this is the same as casting.

I have some devices with Google Assistant in my house.
On the [HA page](https://www.home-assistant.io/integrations/cast/) of this integration, there is no full example of how to play a sound, but it seems you can store MP3 files in the HA config folder and send a URL to such file to your media player.
No idea if it would work the same with Amazon Alexa for example.

My feeling is that it's best to handle such automations externally from Alarmo, due to the following:
* As explained above, the configuration may be different depending on the type of (media player) device
* The user has to pick and store locally the MP3 files (or similar) to be played
* The user should decide when it is desired to play sounds

Perhaps this would be a good candidate for a blueprint.
Making blueprints requires no programming skills (besides YAML), so anyone could make a starting point for this.
If changes are needed from the side of Alarmo to facilitate the use of the blueprint, I'd be happy to help.

>  I was able to make a automation for audio trigger but no way to input it in as a command

I don't know what you mean by this, could you please elaborate?
