### ISSUE TITLE
Request feature override

### ISSUE THREAD

**Issue by sondreen** [nielsfaber/alarmo#41]
Hi,

Can we please implement a feature allowing certain users or codes perform a master-override when arming?
Master-override means that any sensors that are either active or failed will not block arming the alarm nor trigger the alarm, instead they would be bypassed and set as disabled for the session. Active or failed sensors that block arming is troublesome for me as the alarm is to arm automatically when I leave and as I leave by car I can't stop in the middle of the highway because a sensor is failed or delibarately left active and the alarm won't arm. This means the alarm is left disarmed far longer than I want.

Scenario is f.ex.:

1. Window in the bathroom is left open to air out, window is usually not left open.
2. User leaves house, alarm tries to arm automatically.
3. Alarm notices window is left open over the allowed time, but since it's asked to arm anyways it does.
4. Alarm bypasses the sensor, logging this and then arms the alarm.
5. User can then be notified that alarm is armed, but that sensor is bypassed due to active/error.

**Comment by nielsfaber** [comment]
This functionality is already requested and mostly in place.
If you run the latest version, in the users editing panel, you can mark a code as "override" code, and it will do exactly as you wish.

Regarding:
> Window in the bathroom is left open to air out, window is usually not left open.

Maybe it would be nice to mark such a sensor as 'optional'.
So only if it is initially closed when arming, it will be watched.
Essentially the same as bypassing it, except that it wouldn't require the "override" code to be entered.

Steps 2/3/4 are already in place.

> logging this and then arms the alarm.
User can then be notified (...) that sensor is bypassed due to active/error.

This is not in place yet. Currently you don't see that a sensor is bypassed, other than checking the alarm_control_panel entity attributes.

The function is brand-new so let me know if you have trouble setting it up.

**Comment by sondreen** [comment]
My apologies, I thought I'd checked everywhere, but I must have completely missed it! I'll check it out, thanks for such a great component and great support!

**Comment by nielsfaber** [comment]
For next time, please close an issue when it is resolved.
