### ISSUE TITLE
Modes Setup not available (Leave Time and Entry Time)

### ISSUE THREAD

**Issue by fabiobrolo** [nielsfaber/alarmo#412]
### Alarmo Version

v1.8.5

### HA Version

2022.3.0

### Bug description

The options "Leave Time" and "Entry Time" are not available in modes setup of the General pane.

### Steps to reproduce

Open Alarmo settings, navigate to General pane and check that the options "Leave Time" and "Entry Time" are not available under each available mode as follows:
![image](https://user-images.githubusercontent.com/91396121/156457557-cb75c423-7979-4073-b555-7d246684f087.png)

**Comment by nielsfaber** [comment]
Yes, this is due to changes in the HA 2022.3 release.
I also made an announcement as warning for this: https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910/770?u=neliss

Hopefully I can make a new release soon to fix this. On the other hand this release will break things for people who have older HA version.

**Comment by fabiobrolo** [comment]
Another feature that is not working with the new version of Home Assistant is the indication of the sensors that are still open when you try to arm the alarm.

**Comment by nielsfaber** [comment]
This is fixed by updating to v1.8.6.
