### ISSUE TITLE
Setup failed for alarmo: Unable to import component: cannot import name 'STATE_ALARM_ARMED_VACATION' 

### ISSUE THREAD

**Issue by lancelon** [nielsfaber/alarmo#422]
### Alarmo Version

v1.8.3

### HA Version

2021.4.0

### Bug description

Alarmo doesn't load, warning in logs

Setup failed for alarmo: Unable to import component: cannot import name 'STATE_ALARM_ARMED_VACATION' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

I'm wondering if HACS has allowed me to update to a newer version of Alarmo than is actually compatible with my version of HA ?

### Steps to reproduce

n/a

### Relevant log output

```shell
Setup failed for alarmo: Unable to import component: cannot import name 'STATE_ALARM_ARMED_VACATION' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

**Comment by lancelon** [comment]
Downgrading to "v1.8.0" has solved the issue, but it's strange because I didn't think there was a known incompatibility between the HA I am running and v 1.8.3

**Comment by nielsfaber** [comment]
I believe this is a bug caused by changes I made in v1.8.1.
It's strange that I never experienced the issues myself though, but I will investigate.

**Comment by lancelon** [comment]
thanks, not an issue for me as have worked around it - but maybe for others?

**Comment by nielsfaber** [comment]
This is not a bug.
Alarmo v1.8.1 and onwards require updating HA to 2021.8 or newer.

**Comment by lancelon** [comment]
ah OK - so did I miss a breaking change or has the warning just been added? I did have a look when researching the bug (now non-bug) and don't remember seeing it.

**Comment by nielsfaber** [comment]
From the side of Alarmo this is considered a new feature, as you can now set up a ‘vacation’ mode.
A breaking change would be that existing functionality is removed or has to be changed by the user.

In case you update Alarmo without updating HA, you may reach incompatibility which could break things.
I don’t know to what extend things remain backwards compatible, I only develop Alarmo with latest-greatest HA version.
I often have to change things from Alarmo’s side to keep up with changes in HA, so I advise to keep Alarmo updates in sync with HA.

**Comment by lancelon** [comment]
actually strictly speaking I think a breaking change is 
"A change in one part of a software system that potentially causes other components to fail"
but I don't want you to think I'm complaining - far from it - I am super impressed, in awe and grateful for what you do and others like you.

Just wondering how I could have avoided this issue - as I think your text warning was only added today?? Unless I'm wrong about that.

Anyway thanks again!! :-)

**Comment by nielsfaber** [comment]
>  I am super impressed, in awe and grateful for what you do and others like you.

I'm glad to hear that! 😄 

> Just wondering how I could have avoided this issue - as I think your text warning was only added today?? Unless I'm wrong about that.

The obvious answer is to keep your HA version (more or less) up to date.
Looking back I can tell you that v1.8.6, v1.8.4, v1.8.2, v1.8.0 all contain changes which were made to keep up with changes in HA, which I don't consider as 'breaking changes' but this only holds in case users have their HA updated as well.

I could start mentioning (as far as possible) the linked HA versions for which the updates apply in the release notes.
However, since the release notes in HA are often very poorly written I don't always see them coming (I often find things broken and have to look inside the source code for the actual changes), and I don't want to test my changes against multiple HA versions to test backwards compatibility.

The conservative (and safest) approach would be to not update Alarmo to a more recent version than your HA version.
