### ISSUE TITLE
Tamper/vibration sensor warning before Alarm Trigger

### ISSUE THREAD

**Issue by Puppetmaster91** [nielsfaber/alarmo#423]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
Add the ability to set a treshold for how many time a tamper/vibration sensor should be activated within a time limit before it triggers alert.

### Additional info
The other day i had a bird flying into my window and set the alarm off, it could be nice if a single bump wouldn't trigger the alarm.

**Comment by nielsfaber** [comment]
From my point of view, this is an issue caused by the sensor, rather than the alarm (it seems too sensitive and I suppose this is not configurable).
I think (at least for now) it's better to solve such customizations externally from Alarmo, rather than adding extra complexity to it. 

If you want to filter out glitches, you can use a [template sensor](https://www.home-assistant.io/integrations/template/#binary_sensor) as middleware.
Check the `delay_on` setting, you can use it to configure how long the vibration sensor needs to be ON before the template sensor goes ON.
Obviously, you should swap the actual vibration sensor with the template sensor in Alarmo, to make it effective.

**Comment by Puppetmaster91** [comment]
That is for sure one way to solve it, I was "just" thinking that with thresholds options like that, you could also have the ability to make the siren make a short bip if the sensor was activated to warn intruders that this window is protected.

but template sensors, and some node-red flows with siren bips will do for now. thanks for responding. :)
