### ISSUE TITLE
add smart locks as sensors for alarmo

### ISSUE THREAD

**Issue by RaptorPR443** [nielsfaber/alarmo#440]
### Checklist
- [ y] I checked for similar existing requests (both open and closed) before posting.
- [y ] My request is generic, other users may benefit from it too.

### Proposal
add smart lock entities as sensors to be used as triggers for alarmo. example of a smart lock: August smart lock. 

### Additional info
example of an event:
my door have some glass areas that could be broken by thieves and manually open the august smart lock before opening the door. having the smart lock trigger the alarm before the thief opens the door would be very useful.

**Comment by lzinga** [comment]
+1 I'm running into this issue now. Eventually I'll add a a door sensor to detect if it's open or closed but for now it would be nice to have if any of my sensors are changed.

If I'm away, my smart lock changing state would definitely be something that I'd like to know about.

**Comment by nielsfaber** [comment]
If you want to use the locked/unlocked status of a lock as sensor in Alarmo, you should define a [template ](https://www.home-assistant.io/integrations/template)sensor.
For example:
```
template:
  - binary_sensor:
      - name: "Lock status"
        state: {{ is_state('lock.my_lock', 'locked') }}
```
This is not natively supported by Alarmo, since its very user dependent how a lock should behave (an unlocked door doesn't necessarily mean there is a burglar in the house).

**Comment by lzinga** [comment]
I will be using a template in the meantime to get it working; however, I do think its typically best to give the user the options and leave it up to them how it should be configured.

Although an unlocked door doesn't necessarily mean there is a burglar in the house, if the house is set to away mode and the door changes to unlocked there can be high suspicion that something is going on that is not expected. Unless someone types in the disarm code, the alarm would trigger.

Now a template would work, however if the lock already has this state existing, I would prefer not having to duplicate a sensor in an already huge list of sensors.

**Comment by ArmoredCavalry** [comment]
> If you want to use the locked/unlocked status of a lock as sensor in Alarmo, you should define a [template ](https://www.home-assistant.io/integrations/template)sensor. For example:
> 
> ```
> template:
>   - binary_sensor:
>       - name: "Lock status"
>         state: {{ is_state('lock.my_lock', 'locked') }}
> ```

This worked for me, although I had to flip 'locked' to 'unlocked' when using a device class of `lock`. Since `on` is interpreted as `unlocked`. I did notice that sensor state in Actions is showing the inverse though, will say failed to arm due to the door being 'locked' (when it is actually unlocked). So, functionality works, but label seems wrong?
