### ISSUE TITLE
Notification delivery priority

### ISSUE THREAD

**Issue by geofffarmer** [nielsfaber/alarmo#474]
The notifications delivered by Alarmo are not considered high priority on my phone. I often only see them when I unlock my phone.

For notifications in my own automations and scripts, I use:

`service: notify.mobile_app_geoff_s_s21
data:
  data:
    ttl: 0
    priority: high
    push:
      sound:
        name: default
        critical: 1
        volume: 1
  message: "Alarm triggered by {{ state_attr((state_attr('alarm_control_panel.alarmo','open_sensors') | list)[0],'friendly_name') }}"
  title: Home Assistent`

Which seems to gaurentee immediate delivery.

Whilst I can add the above code to the scrips called by Alarmo, it would be nice if Alarmo could deliver the messages with higher priority natively.

**Comment by patrik-malina** [comment]
+1

**Comment by nielsfaber** [comment]
It is already possible to create a notification from Alarmo with extra service data parameters by switching to YAML mode in the editor.

As you can read [here](https://companion.home-assistant.io/docs/notifications/critical-notifications), it is device (iOS, Android etc.) dependent how the service data must be formatted.
Since there is no generic format, I don't see a possibility to add native support for this (unless I ask the user to specify their device type in the form, but I don't see this very elegant).

**Comment by geofffarmer** [comment]
Hi NielsI apologise. I hadn't seen the YAML button. I'll use that.Thank youGet Outlook for Android
