### ISSUE TITLE
Allow transitioning between arm modes

### ISSUE THREAD

**Issue by sdujolo** [nielsfaber/alarmo#48]
Is ti possible to add soo you can go from Armed away to Armed home in one click?

**Comment by nielsfaber** [comment]
Yes.. I was planning to make this.
The question is if there should be a leave delay again.
And whether actions/notifications should be executed.
What do you think?

**Comment by sdujolo** [comment]
I don´t think delay is needed but if it´s not alot of work maybe some one want it.

**Comment by zbuh** [comment]
These transitions are usually automated. 
I think it should not have the delays.

**Comment by zbuh** [comment]
Can I do a PR with this change?

**Comment by nielsfaber** [comment]
The change is not that straightforward, since the following logic needs to be added:

-  Code check must be skipped (there is no need to enter the code again, since the alarm is already armed)
- Delay must be skipped
- Sensor states must be re-evaluated to see if the transition is allowed, else the previous state must be kept

If you're confident you can take these requirements into account, go ahead.
Else i will add it as soon as i find the time.

**Comment by zbuh** [comment]
https://github.com/nielsfaber/alarmo/pull/56

I did some tests, seems ok.
Check if it's missing something

**Comment by nielsfaber** [comment]
Added in v1.4.0.
Thanks again!
If you ever feel like helping out again, it is much appreciated 👍
