### ISSUE TITLE
[Feature Request] Update (open sensor) when status change

### ISSUE THREAD

**Issue by LucaBors** [nielsfaber/alarmo#483]
Hi, first of all, thank you for your great work! :)

I'd like to know if it's possible, once the alarm fail to arm because of one/some open sensor, if, when the status of the sensor change also  status of alarmo can change.
![image](https://user-images.githubusercontent.com/73178440/171337463-5efafb6b-c6be-4dc7-b35c-539c6d8c0011.png)

I'm asking that because of this case on a panel that i use to arm/disarm alarmo. https://github.com/joBr99/nspanel-lovelace-ui/issues/242.

Thank you.

**Comment by nielsfaber** [comment]
The open_sensors property provides the reason why arming failed (or alarm was triggered).
The property will not update if the sensor status changes afterwards, since this has nothing to do with the reason of the failure.

For getting the current sensor state (rather than its state while triggering or arming) you can check the HA entity directly, there is no need to use an Alarmo property for this.
