### ISSUE TITLE
Disarming notify bug

### ISSUE THREAD

**Issue by magomao** [nielsfaber/alarmo#493]
### Alarmo Version

1.9.3

### HA Version

2022.6

### Bug description

When disarming can’t create different notifications (tts) from the mode was armed.

### Steps to reproduce

want to tts say “welcome home” when disarming from Away mode and say “good morning” from Night mode.
I create two notify actions but didn’t work.

**Comment by nielsfaber** [comment]
This is not really a bug, since the arm mode doesn't exist in the disarmed state (alarm cannot be disarmed and armed simultaneously).
But I do understand that it is useful to filter on the mode which was active **before** the disarming.
I made some changes which enable you to do so: https://github.com/nielsfaber/alarmo/commit/2e73142debb3f5d890e715f40352d3be9da886bc
I will let you know when the next version of alarmo is out.
