### ISSUE TITLE
Exiting during arming causes a sensor bypass issue.

### ISSUE THREAD

**Issue by NickPickles937** [nielsfaber/alarmo#497]
### Alarmo Version

v1.9.4

### HA Version

core-2022.6.2

### Bug description

When I set the alarm to Armed_Away, I have a 90 second delay that begins. Within that 90 seconds, up until I upgraded to version 1.9.4, I was able to set the alarm to Armed Away, exit the house through my garage door and everything worked normally. Now- when I set the alarm to armed away, the 90 second countdown begins, but if I open the garage door, the countdown stops and tells me that the garage door being opened caused an arming failure.

### Steps to reproduce

Attempt to leave the house while armed away countdown is running.

### Relevant log output

```shell
Nothing relevant that I have found. Everything runs the way it should, except now the ability to set the armed away countdown and leave has stopped.
```

**Comment by nielsfaber** [comment]
Please share the configuration of this sensor.

**Comment by NickPickles937** [comment]
Is the configuration inside of the Alarmo configuration what you're looking for?

**Comment by NickPickles937** [comment]
I see. Was this a breaking change from v1.9.4? I haven't made any modifications to any sensors in months and this only started happening after I upgraded to v1.9.4. I do see on the configuration that this option is not checked, so I'm sure that will resolve it. But it's weird to me that that toggle is now turned off.

**Comment by nielsfaber** [comment]
No, it should always have worked like this. But I got a similar comment the other day: https://github.com/nielsfaber/alarmo/issues/494#issuecomment-1146652310.
It seems the previous version had different (unintentional) behaviour, so a bug.

I think for doors (which you use to exit) the 'use exit delay' setting should be on, for windows it should be off. 
That way you will be notified immediately when arming starts of windows being left open, doors should all be closed by the end of the delay time.

**Comment by NickPickles937** [comment]
Copy that. I'm pretty certain "use exit delay" was turned on when I set up the Alarmo integration on my HA instance, so I'm sure this is the fix. I'll test it tonight when I get back home and let you know if it doesn't work. Thanks for the quick answers!

**Comment by jutley** [comment]
I recently updated (can't recall which version I was on) and now seem to be running v1.8.7. I think there are newer versions but for some reason I can't see any updates available in HACS. I am running into the same issue as reported in this ticket, but I think I have observed behavior that is a bit different than what has been previously explained.

Prior to updating, the alarm would refuse to start when a window or door is open, which makes sense. You don't want to leave and unknowingly leave a door open. Now I run into the issue described in this ticket - after starting countdown, when I open a door, the alarm is cancelled. I can mark the sensor as described in this ticket, but the issue with this is that now there isn't any feedback if a door was accidentally left open. The result is that I set the alarm, leave through a door, and then the alarm cancels at the end of the countdown because there wasn't any feedback that the door was open to begin with.

I think I can work with the current setup with my own automations, but wanted to share this experience since I felt like it was missing from the discussion.

**Comment by nielsfaber** [comment]
@jutley You should be able to open/close a door during the exit delay for allowing you to leave the house (assuming you're arming while you're inside still). This is intended behavior.

If you don't want this, you can control it via this setting:
![image](https://user-images.githubusercontent.com/16861605/186073288-a7a4dbc9-c976-4e30-98f5-9352997c6b8c.png)

> The result is that I set the alarm, leave through a door, and then the alarm cancels at the end of the countdown because there wasn't any feedback that the door was open to begin with.

If the door which you used to leave the house is the only open door, it should be fine (assuming you close it after leaving). If there is a second door, you would indeed be notified at the end of the exit delay.
However I would recommend to either have only 1 door for exiting (others are not allowed to be open while exiting), or use this setting to skip the remainder of the exit delay after closing the door:
![image](https://user-images.githubusercontent.com/16861605/186074218-ceeead08-26bb-40bb-8bd8-3e3e1d8f24f5.png)
