### ISSUE TITLE
Zone Disarmed -> Disarm Master: Cannot go to state disarmed from state disarmed

### ISSUE THREAD

**Issue by jazzyisj** [nielsfaber/alarmo#515]
### Alarmo Version

v1.9.4

### HA Version

2022.7.0

### Bug description

When one zone is disarmed (say for example the garage) and the master zone is subsequently disarmed a warning appears in the log.  I'm wondering if either Alarmo should be skipping already disarmed zones when the master zone is disarmed or maybe this warning can just be suppressed for this case.  There are no negative consequences are far as I can tell, it's always worked fine other than the warning in the log.

### Steps to reproduce

- Multiple zone Alarmo setup.
- Arm Master zone
- Disarm one zone
- Disarm master zone

### Relevant log output

```shell
`WARNING (MainThread) [custom_components.alarmo.alarm_control_panel] Cannot go to state disarmed from state disarmed.`
```

**Comment by nielsfaber** [comment]
Fix is on its way: https://github.com/nielsfaber/alarmo/commit/aec30228e34fc433ff289ac0ed47cad8c8a1426d

**Comment by nielsfaber** [comment]
Version v1.9.5 is released and should fix this problem.
Please update your alarmo version and test whether the issue is indeed solved.
You can close the issue if so, otherwise please let me know.

**Comment by jazzyisj** [comment]
The log warning is gone but the alarm modes are no longer working correctly.  I assume it is related to this change.  If not I can open a new issue.

- Alarm zones all disarmed
- Arm garage in armed_home
- Master zone does not go into arming mode, stays disarmed

- Garage is armed_home, House is disarmed (master see above)
- Arm house in armed_night
- Master goes to arming and stays there, never goes to armed_home or armed_night

![image](https://user-images.githubusercontent.com/44064559/182035089-7a951263-98f9-47db-9203-ff2d874ccf41.png)

**Comment by nielsfaber** [comment]
I don't think the behaviour you describe is related to the recent change.
What you're observing is as I would expect it, what would you expect instead?
Please read the [documentation](https://github.com/nielsfaber/alarmo#alarm-master) on the behaviour of the master, including the notes at the bottom.

**Comment by jazzyisj** [comment]
Sorry Neils I was away for a few days.  So I have reread the documentation as requested.  I've been using Alarmo since you first released it so admittedly it has been a while since I gave the docs a good reading.  And after having done so I think I may have explained my new issue here poorly as my understanding of Alarmo logic and functionality seems to be in line with the docs.

I am aware of the following caveat however in my case the functionality of the master has been adequate for my needs (until now) with the exception of the case I've explained at the bottom of this comment.

> If the areas are independently operated, the user is reponsible to maintain synchronism between the areas. If independent operation is desired, usage of the Master Alarm is not recommended.  _(just noticed you have a typo in the README here - responsible)_

So according to the docs for[ alarm master](https://github.com/nielsfaber/alarmo#alarm-master).

> One or more areas have state arming, others have state armed_away, armed_home, armed_night, armed_vacation or armed_custom_bypass:  Master Alarm State - **arming**

That is not happening now.  In this screenshot the garage zone is `arming`, the master zone is still `disarmed`.

![image](https://user-images.githubusercontent.com/44064559/182855720-778f719d-dd0c-4c5b-9b97-c6cd9fa1feae.png)

Now after the arming delay, the garage zone is `armed_home `and the house is `disarmed`.  The master zone is still disarmed (correct according to docs).  Now if we arm the home zone to `armed_away `both home and master zone go to `arming`.  This is also the correct behaviour.
![image](https://user-images.githubusercontent.com/44064559/182859206-4bc41e9d-c083-4e83-9cda-b01167190041.png)
But after the arming delay has expired, the house zone goes to `armed_away`, but the master zone stays in `arming`.  **This is not the expected or previous behaviour.**
![image](https://user-images.githubusercontent.com/44064559/182859689-9d9cbdd5-3603-4b6d-b633-e12422f1cde5.png)
**I would expect the master zone to go back to `disarmed `here.** as no zone are still in the `arming `state.

On a related note I'm wondering if the logic of the master alarm zone could actually be improved here.  In my train of thought the alarm zones have a security level logic associated with them.

 `disarmed `< `armed_home `< `armed_night `< `armed_away `< `armed_vacation`

Would it not make sense for the master zone state to be the set to the "lowest security level" of all it's zones instead of it's previous state?  For example if in my case the garage is armed_home and the house is armed_away, the master should be set to armed_home instead of disarmed since no zones are actually disarmed.  In this case the master control panel currently can't even be used to disarm the system even though all zones are armed because the master is still in the disarmed state.  The change I suggest would resolve this issue. 

I don't think a change like this should even affect any custom synchronization behaviour that user may already have in place. I realize I can accomplish this logic myself with automations, I just think this logic change would make Alarmo a little more robust right out of the box.

**Comment by jazzyisj** [comment]
Not stale, waiting for response.

**Comment by nielsfaber** [comment]
Sorry for the delayed response (busy times).

Regarding:
>> One or more areas have state arming, others have state armed_away, armed_home, armed_night, armed_vacation or armed_custom_bypass: Master Alarm State - arming

> That is not happening now. In this screenshot the garage zone is arming, the master zone is still disarmed.

In your screenshot the area 'garage' is arming while 'house' is disarmed.
Hence your situation doesn't match with the condition as described in the documentation (the "others" part).
The master area is deliberately programmed to ignore this combination.
The reason is that I consider it misleading if the master would indicate the alarm is armed, while in fact only the garage is armed.

> Now after the arming delay, the garage zone is armed_home and the house is disarmed. The master zone is still disarmed (correct according to docs). Now if we arm the home zone to armed_away both home and master zone go to arming. This is also the correct behaviour.

> But after the arming delay has expired, the house zone goes to armed_away, but the master zone stays in arming.
This is not the expected or previous behaviour.

I don't understand why this is unexpected. This situation still matches with "One or more areas have state arming, others have state armed_away, armed_home, armed_night, armed_vacation or armed_custom_bypass", so the master will be in the arming state.

The reason behind this is the same, it's a conservative choice. The master will only show armed state if ALL areas are armed (and in the same mode).

> I would expect the master zone to go back to disarmed here as no zone are still in the arming state.

In this case your areas are all armed but in different modes. Hence I would say the alarm is definitely not disarmed. The master remains in the arming state, because it was in that state.
It cannot handle the case where areas are in different arm modes, because they are ambiguous.
This is exactly what's meant by the notes in the documentation. The user has chosen to arm the areas separately, instead of doing so via the alarm master. Hence synchronism is lost.

The code behind this behaviour this was written in January 2021 and has remain the same, see [here](https://github.com/nielsfaber/alarmo/blame/45054375a30e7bba93811e3cb8a54118172d5b9a/custom_components/alarmo/alarm_control_panel.py#L851-L871) for the source code.
Hence I am surprised to hear that you experience the behavior to be different than before.

Hope this explanation helps you and you are now aware of how the master works (including its limitations).
I'm open for a discussion on possible changes to improve this (and make it more intuitive).

**Comment by jazzyisj** [comment]
Still planning on digging into this.
