### ISSUE TITLE
1.9.5 won't start on my setup

### ISSUE THREAD

**Issue by CrallH** [nielsfaber/alarmo#538]
### Alarmo Version

V.1.9.5

### HA Version

2022.7.7

### Bug description

After 1.9.5 Alarmo won't start. Tried uninstalling and reinstalling but no difference. 
Downgraded to V.1.9.4 and it works again. Logs added.

### Steps to reproduce

Update to V.1.9.5 error occur, downgrade to 1.9.4 and it works again.  Verified 10 times with same result.

### Relevant log output

```shell
Felet härrör från en anpassad integration.

Logger: homeassistant.config_entries
Source: custom_components/alarmo/store.py:191
Integration: Alarmo (documentation, issues)
First occurred: 00:06:07 (1 occurrences)
Last logged: 00:06:07

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmo/__init__.py", line 55, in async_setup_entry
    store = await async_get_registry(hass)
  File "/config/custom_components/alarmo/store.py", line 687, in async_get_registry
    return cast(AlarmoStorage, await task)
  File "/config/custom_components/alarmo/store.py", line 682, in _load_reg
    await registry.async_load()
  File "/config/custom_components/alarmo/store.py", line 312, in async_load
    data = await self._store.async_load()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 114, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 123, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 168, in _async_load_data
    stored = await self._async_migrate_func(data["version"], data["data"])
  File "/config/custom_components/alarmo/store.py", line 228, in _async_migrate_func
    data["automations"] = [
  File "/config/custom_components/alarmo/store.py", line 230, in <listcomp>
    **parse_automation_entry({
  File "/config/custom_components/alarmo/store.py", line 191, in parse_automation_entry
    output["actions"] = list(map(lambda el: ActionEntry(**el), data["actions"]))
  File "/config/custom_components/alarmo/store.py", line 191, in <lambda>
    output["actions"] = list(map(lambda el: ActionEntry(**el), data["actions"]))
TypeError: ActionEntry.__init__() got an unexpected keyword argument 'service_data'
```

**Comment by nielsfaber** [comment]
I'm sorry for creating this problem.
Could you share your alarmo.storage file? I would like to see the "automations" part.
It is located in the .storage folder in your HA config folder (where you have the configuration.yaml as well).
It could be hidden in Windows (see [here](https://support.microsoft.com/en-us/windows/show-hidden-files-0320fe58-0117-fd59-6851-9b7f9840fdb2) for instructions for showing it).

**Comment by CrallH** [comment]
https://pastebin.com/E0gDZ0Gu

Sorry for bad formating, did it on the phone.

**Comment by CrallH** [comment]
![Screenshot_2022-07-31-12-11-33-628_io homeassistant companion android](https://user-images.githubusercontent.com/32394267/182021445-76338bb2-d1f1-4cbb-8d89-2a9c1609ddd3.jpg)
I just saw this also.  Can the swedish non latin characters play a role in the issue?

**Comment by nielsfaber** [comment]
Your storage file shows version 1 at the top. 
This suggests you were still running a version of Alarmo dating from before January 2021. Does this make sense to you?
Alarmo v1.9.4 uses storage version 5, it doesn't match with your storage file either.
Additionally I am missing the minor_version property which has been added approx. half year ago.

It seems like your previous HA/Alarmo installation is too old, or you haven't made any changes in over a year.
I think that you are facing some backwards-compatibility problems due to skipping several intermediate versions.
Could you try making a change to your configuration (e.g. disable a sensor or action), and see that your storage file shows version 5?

**Comment by CrallH** [comment]
> Your storage file shows version 1 at the top. This suggests you were still running a version of Alarmo dating from before January 2021. Does this make sense to you? Alarmo v1.9.4 uses storage version 5, it doesn't match with your storage file either. Additionally I am missing the minor_version property which has been added approx. half year ago.
> 
> It seems like your previous HA/Alarmo installation is too old, or you haven't made any changes in over a year. I think that you are facing some backwards-compatibility problems due to skipping several intermediate versions. Could you try making a change to your configuration (e.g. disable a sensor or action), and see that your storage file shows version 5?

Yes doing a change updated it to version 5. Will test and update the component again.

**Comment by CrallH** [comment]
Doing an update of config fixed it. Thanks!

**Comment by LoganJFisher** [comment]
I think I have the same issue. Here is my alarmo.storage: https://pastebin.com/bbuCV273

I'm not understanding what you mean by "Could you try making a change to your configuration". I tried editing my configuration.yaml and restarted HA, but nothing changed.

**Comment by nielsfaber** [comment]
@LoganJFisher What I meant was: go into the alarmo panel and make a change here (e.g. change the exit delay). 
This should cause the alarmo.storage file to be overwritten. 
Perhaps the storage file is too old to be upgraded.

I will (whenever I have time) copy your storage file and use it in my setup and perform the 1.9.4 -> 1.9.5 update. Hopefully I can figure out what is going wrong.

**Comment by LoganJFisher** [comment]
@nielsfaber Oh, I see. Yeah, I can't access the alarmo panel. It's gone.

**Comment by LoganJFisher** [comment]
I decided to just delete my alarmo.storage and reinstall. That means losing my setup, but it's not like I had anything particularly advanced set up.

**Comment by nielsfaber** [comment]
@LoganJFisher I used your storage file and managed to reproduce the problem.
The problem was caused by having a very old storage file (older than v1.6.0, which dates from June 2021).
This suggests that you either haven't updated alarmo in over a year, or you haven't made any changes to the configuration since, is this correct?
I some changes to the code which should fix this: https://github.com/nielsfaber/alarmo/commit/fe206d0fcd10ee5fedcec47afbe651c59bc6fc4b
If you still have the problem you could manually update the store.py file with the changes as a temporary fix (there is no new release yet).

**Comment by LoganJFisher** [comment]
Yeah, I had done updates but hadn't made any config changes.

Having deleted my alarmo.storage and reinstalled I just rebuilt what I previously had set up. Since it wasn't much, it wasn't a big deal. I'm all good now. This issue is just worth noting for anyone else in the same boat and perhaps as something to consider in future releases (e.g. automatically updating the config when a new release is installed so it never falls out of date).
