### ISSUE TITLE
Cannot Find Working Notifications 

### ISSUE THREAD

**Issue by Djal94** [nielsfaber/alarmo#557]
### Alarmo Version

V 1.9.5

### HA Version

2022.8.6

### Bug description

Hi.
I created a TTS notification a long time ago with alarmo (> 1 yr), and it works like a charm every day since.

a few days ago, I wanted to change the TTS message and I couldn’t find the dedicated notification in the action tab.
More precisely, I know which one it is (if I disable it, I have no TTS notification no more), but I can’t see the TTS part in the yaml mode, only the pushover part (which is visible in the visual editor as well).

**Comment by nielsfaber** [comment]
Can you check your `alarmo.storage` file in the `.storage` folder (might be a hidden folder under Windows) in the HA config directory?
All actions should be listed here, with the complete configuration.
If you see anything here which is not shown in Alarmo, please let me know.
Otherwise I wouldn't really know how to help. Actions are only changed when the user edits them (Alarmo will not do this on its own).

**Comment by Djal94** [comment]
In the alarmo.storage file, i can see the TTS configuration, nut not shown in alarmo, as you can see

![8049C75B-06F3-47BF-8442-719E7D798100](https://user-images.githubusercontent.com/35771339/185778948-2c716285-5c35-4aec-8a21-43389c438c37.jpeg)
![090CC376-88D2-4931-9931-A86C383C59D0](https://user-images.githubusercontent.com/35771339/185778952-a984a2c0-8e70-4202-867f-4afe7dac3f81.jpeg)

Thanks for your help.

**Comment by nielsfaber** [comment]
Ah I see.
Well it’s not possible to have multiple actions under a single notification. 
It’s best to create a separate one for the TTS  notification.
You could remove the second action from the storage file directly if this is needed (through Alarmo this is not possible I think).

**Comment by Djal94** [comment]
Ok I see.
You say it's not possible, but it's working fine actually.
I will split my notification so.

Thxs for your quick response
