### ISSUE TITLE
Handling of tamper sensors

### ISSUE THREAD

**Issue by segdy** [nielsfaber/alarmo#586]
This is based on the discussion in https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910/916?

### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal

As proposed in the forum discussion, best would be to have a separate "zone" similar to "24h". When adding a tamper sensor (or smoke/gas etc) they should automatically be added to this zone.
This zone is always active (regardless of arming status) but can temporarily be disabled during maintenance (battery change etc)

**Comment by nielsfaber** [comment]
Thanks for making the request.
Alarmo uses _areas_ instead of _zones_.
However, most users don't use this functionality (all their sensors are in a single area).
I think we should focus on a solution where users can easily add tamper sensors without the need for splitting their alarm in multiple areas.

The default behaviour for a tamper sensor is defined in [this table](https://github.com/nielsfaber/alarmo#sensor-types). In summary, the sensor will be active whilst the alarm is armed, and trigger the alarm instantly (no delay).

The difference with your request is that you want the sensor to be always active, except when performing maintenance.
I think there a two options to accomplish this:

1. In Alarmo there is an 'always on' setting which can be applied to a sensor. When set, the sensor can bring the alarm to triggered state even when the alarm is disarmed. There is no option for temporary disabling for maintenance, the only way would be to go into the sensors tab in Alarmo, and use the toggle switches here to disable each manually.
2. A user can create an area for all tamper sensors. It will be a separate alarm entity which can be armed and disarmed independently (read [here](https://github.com/nielsfaber/alarmo#areas)). The user can keep this area in armed state at all times except when performing maintenance. The user can make use of the [alarm master](https://github.com/nielsfaber/alarmo#alarm-master) to catch a trigger event of a sensor in the "24h" area or the regular area. combined

Both options are already possible to set up without changes in Alarmo, and I think choosing for either depends on the preference of the user. I have my doubts whether any of these should be a default setting for a newly added tamper sensor.
Personally I don't have a desire to have the alarm trigger on a tamper sensor while the alarm is disarmed.

Please share your thoughts on this.

**Comment by segdy** [comment]
Hi Niels, this makes sense to me and as indicated in the forum thread (https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910/918 and https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910/919) this is likely a bug.

In the [table](https://github.com/nielsfaber/alarmo#sensor-types) you quoted, tamper maps to device classes sound, opening, vibration. However there is a device class tamper itself (Zigbee contact sensors expose this device class for example). So maybe the solution is as easy as adding "tamper" to this list?

So now, this is likely not a feature request any more.
I created a bug report https://github.com/nielsfaber/alarmo/issues/587 and closing this one then.

Thanks!
