### ISSUE TITLE
Possible bug: Lock sensor automatically bypassed even if auto bypass is not enabled?

### ISSUE THREAD

**Issue by Dinth** [nielsfaber/alarmo#598]
### Alarmo Version

v1.9.6

### HA Version

2022.10.5

### Bug description

I think i found an incorrect behaviour.
Ive got a lock sensor set up in Alarmo:
![image](https://user-images.githubusercontent.com/313674/198379775-705770bf-32fa-4909-9a24-ce151e4c230c.png)
When im leaving the house (armed Away) this config seems to be working correctly - alarm gets armed even with door unlocked. But what bothers me is the fact that i can also arm Home with door lock unlocked and Alarmo never says that there are sensors to bypass. Why this is happening?

**Comment by nielsfaber** [comment]
I would expect that arming fails in both away and home mode in case the door sensor is active.
Why should arming work with the door unlocked? The sensor is not configured to be bypassed, so the arming should fail.

**Comment by Dinth** [comment]
Use exit delay is enabled so i can have door open, arm the alarm (Away) and go out without triggering it. 
The thing is that the arming doesnt fail in Arm Home mode and as far as i understand it should instantly

**Comment by nielsfaber** [comment]
I failed to reproduce the issue you're having.
I have my back door sensor set up the same way as yours:
![image](https://user-images.githubusercontent.com/16861605/198879063-6fb81648-ec57-4f7c-99e6-ce0febf1ad42.png)

If I click 'arm home' while the back door is open, the arming fails:
![image](https://user-images.githubusercontent.com/16861605/198879129-ef02eb46-4906-4590-8781-2fa044aa4d3d.png)

Please provide more info for me to be able to reproduce the issue, otherwise I cannot help.
