### ISSUE TITLE
Add new variable to alarmo_failed_to_arm

### ISSUE THREAD

**Issue by JOHLC** [nielsfaber/alarmo#605]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
The event alarmo_failed_to_arm is useful, however it would be great if this event passed something like "target mode" for automations to handle certain custom actionable notification. 

### Additional info
n/a

**Comment by nielsfaber** [comment]
No problem.
I made a small change (https://github.com/nielsfaber/alarmo/commit/1d7eb2adf7d7b61b0ec34779ee8719c880b1043a) to facilitate this.
The event will now have the property `command` which will be as defined [here](https://github.com/nielsfaber/alarmo#commands).
Note that this property was already provided in some cases (e.g. the user tries to arm with the wrong pin code), now it will also be provided in case the arming fails due to sensors.
Hope this helps you, otherwise let me know!

I will let you know when this feature is released.

**Comment by nielsfaber** [comment]
Sorry for the delay, this is now released.
Could you test this locally and confirm the change fulfils your request?
