### ISSUE TITLE
Notification action on entry delay started very delayed

### ISSUE THREAD

**Issue by Iceman248** [nielsfaber/alarmo#614]
### Alarmo Version

v1.9.6

### HA Version

2022.11.5

### Bug description

When I first set it up it worked immediately, although once or twice it may have been a little delayed. Now though after trying it several times, when my notification action that has it telling me about the injury delay being started and why using the wildcards with TTS service, it seems to have been delayed about 2 minutes which was way too long and ended up having my alarm going off when I didn't realize it was about to because I didn't get notified.

I tried doing a manual TTS service run and it worked fine like it does with anything else, but within this app it is being seriously delayed for some reason.

**Comment by nielsfaber** [comment]
This is strange behavior which I wouldn't expect.
By design, actions are executed directly on the state change of Alarmo.
There could only be a slight (one or two seconds) delay when a long list of actions have to be eecuted.
I would like to know whether the issue is on the side of Alarmo or external (for example the TTS device itself).
Is it possible for you to reproduce the problem?

You can enable the debug logging for alarmo by adding this to the configuration.yaml (and restarting HA):
```yaml
logger:
  default: warning
  logs:
    custom_components.alarmo: debug
```

This way you will get more information in your HA log of all that Alarmo does (including the times), please share the results if you can 'catch' the issue.

**Comment by Iceman248** [comment]
Thanks. I did test the TTS itself through HA after Alarmo was supposed to execute the TTS action and it worked fine like it typically does. I use it often. Alarmo still executed it some 2 minutes or so later.

I haven't been able to reproduce from test or actual alarm going off, so maybe it'll stay okay and that was temporary. I will close for now and add logs if it does happen again.
