### ISSUE TITLE
Alarmo configuration GUI goes blank after a while

### ISSUE THREAD

**Issue by mikyjazz** [nielsfaber/alarmo#62]
![alarmo](https://user-images.githubusercontent.com/38558161/102093364-5bcdf800-3e21-11eb-95d2-2512624ba15f.jpg)
Ok .. This time it's true ... I found the configuration panel and used it; leaving it open and switching to another chrome tab, returning after a while to the tab where it is alarmo the page is empty, or rather the frame is empty (the side menu remains correctly visible) ... by manually refreshing the page it reloads correctly...

**Comment by nielsfaber** [comment]
I am aware of this issue.

>  leaving it open

Is already enough to see this happening.
I don't know what causes it, would need to investigate it.
Currently I don't consider it a priority since it is a pretty harmless bug.

**Comment by mikyjazz** [comment]
Perfect, the essential thing is that you know it. I share your opinion on the non-urgency of resolution of this bug.
good job
Michele

**Comment by nielsfaber** [comment]
Let's keep the issue open, it may be informative for others as well.
And it is a good reminder for me 👍

**Comment by nielsfaber** [comment]
It seems that the issue is related to having this setting enabled (it's part of the HA user profile settings):
![image](https://user-images.githubusercontent.com/16861605/104505575-67f5d280-55e4-11eb-93d3-fb8f6bf9acfe.png)

I'm still looking for an alternative way to solve this (that doesn't require all alarmo users to change their profile).

**Comment by Masterz69** [comment]
Confirm: when 'Automatically close connection' user profile option disabled - Alarmo page looks fine after perdio of inactivity.
