### ISSUE TITLE
Zone alarm notifications

### ISSUE THREAD

**Issue by beccsjb** [nielsfaber/alarmo#637]
Hi Guys, I love this project! As an alarm installer, there are a few features missing that most/all alarm systems do as standard practice.

The biggest feature I think Alarmo lacks is that on a sensor alarm, it only sends one zone (first zone) that has gone into alarm.
If I walk right through my house and out again in an armed state, I only get a notification for the first zone that went into alarm and I don’t get a restore notification when the motion even has finished.

 A typical alarm system would send every sensor/zone each time it goes in or out of alarm. It would also show the restored state aswell. This is so beneficial as remotely you can see if the trigger is a constant or a once off false alarm, ie someone is still inside my house and they’re now in the master bedroom.

In order to stop annoying the owner on mobile and noise pollution from sirens, there is another feature called swinger bypass, this is a simple feature that is usually a customisable field but you can set the max number of times that eg. Zone 1 can send an alarm. By default most alarms come with this setting on 6, but is customisable.

If the above we to be addressed It would be awesome, I’m not a developer, but would be happy to help out with testing etc, if required.
Thank you and again, I love Alarmo!

**Comment by rct** [comment]
@beccsjb - to me this is an important point.  When I switched CSM companies (AT&T 3G shutdown) I was surprised to learn that their dispatch/call notification procedures for burglary alarms differs based on the number of zones tripped.

A single zone trip is considered to be more likely a false alarm.  Multiple zone trips are more likely to be someone is n the premises. They somewhat except a good installer would provide defense in depth, so someone in the premises would trip both a door/window sensor and a motion sensor.

**Comment by nielsfaber** [comment]
Alarmo employs a state machine where the alarm transitions from 'armed' state to 'triggered' state upon the first sensor that activates.
Notifications (and actions for switching siren etc) are configured on the state transitions.
The activation of a second sensor will not introduce a new state transition, hence it is currently not possible to configure any notification to be sent if this happens.
The alarm will remain in 'triggered' state until the trigger time has passed (or the alarm was manually disarmed) and afterwards the user can choose whether it should return to 'armed' or 'disarmed' state.
The above is in-line with the [convention](https://www.home-assistant.io/integrations/manual/#state-machine) used by HA to guarantee Alarmo is compatible with the HA frontend and can be used in automations.

I'm not sure how your request can be fulfilled without making significant changes to this model.
Consecutive triggers could be detected (Alarmo already does this, but ignores them) but since they will not lead to a state change, it may not be visible from the card or to trigger HA automations. 
Your request seems to require adding a 'logbook' of all trigger events to be captured while the alarm is armed, which should be possible to visualize as well. 
I will think about this, but it might take some time before this can be added.

BTW: Could you please elaborate on the difference between a zone and a sensor? And should the duration of a trigger be depending on the zone or a global setting?

**Comment by beccsjb** [comment]
G’day, sorry for the delayed reply. 

A zone and a sensor are virtually the same thing. The sensor is the physical device (PIR) and a zone is the input terminals on the alarm controller. 

A logbook of events would be great. I just find the way it is that you have to leave Alarmo and go into the sensors in HA to see if any further zones/sensors have been triggered to verify wether it’s a legitimate alarm or a false alarm, ie cat/dog etc. 

Multiple knocks/trips would be another great feature. This would be configured per zone/sensor. ie the sensor has to go from Sealed, Alarm, Sealed Alarm to trigger with a knock count of 2. It can massively reduce false alarms, particularly when using fairly low cost iot PIR/Sensors.
