### ISSUE TITLE
Unable to make automations work with disarmed state

### ISSUE THREAD

**Issue by hardwareadictos** [nielsfaber/alarmo#661]
### Alarmo Version

v1.9.7

### HA Version

2023.02.05

### Bug description

Unable to create a disarmed mode automation with disarmed alarm state.

I'm trying to automate alarm arming with an Aqara button dealing with disarmed state, for this i make a conditional to arm only the alarm if it's only on the disarmed state (to not conflict if the alarm is armed by another actions), but for some reason i'm not able to make the automation work with the disarmed state (it's like the disarmed state does't exists as HA doesn't find it):

![image](https://user-images.githubusercontent.com/20403906/219358833-ad4b2ccd-6ce2-4cc5-8067-f3317b3ca158.png)

Is it a bug? Or i am (probably) missing something?

Thanks in advance.

### Steps to reproduce

Creating an automation with disarmed state as a conditional.

### Relevant log output

```shell
Nothing on logs, just the message on the automation GUI for the conditional not being acomplished.
```

**Comment by nielsfaber** [comment]
As defined in the [documentation](https://github.com/nielsfaber/alarmo#arm-modes), the arm mode can only be any of:
- Armed away
- Armed night
- Armed home
- Armed vacation
- Armed custom bypass 

For the arm_mode attribute of the alarmo entities, these are converted to lowercase and spaces replaced by underscores (e.g. `armed_away`).

The disarmed state is not an arm mode (since the system is not armed). You can simply use the state of the entity directly.
All possible states are also [documented](https://github.com/nielsfaber/alarmo#states).
