### ISSUE TITLE
Exit Delay enabled, arming still cancels upon open door.

### ISSUE THREAD

**Issue by CybrFox** [nielsfaber/alarmo#672]
### Alarmo Version

v1.9.7

### HA Version

2023.2.5

### Bug description

I'm sorry if this is unclear.  Simply trying to enable both exit and entry delays.  When arming any type of mode, I should have 60 seconds to open the door and exit, before the alarm arms.  But as soon as I open any door with a sensor, it cancels the arming.  Any help is appreciated.

![image](https://user-images.githubusercontent.com/91752446/221394608-58f64d9a-29ea-4cff-a300-5a1bedf59628.png)

**Comment by nielsfaber** [comment]
Check your sensor settings.
You need to configure per sensor whether it is allowed to be active during the exit delay.

**Comment by ryny24** [comment]
I just ran into this issue today.    When I "ARM AWAY", I should have 120 seconds to leave the house. But the second I open a door, Alarmo goes DISARMED and cancels the arming.

**Comment by 321row123** [comment]
By default, in ALARM add an opening sensor, what is considered a sabotage type, you must modify the type to input access and thus expand the advanced options of the sensor to be able to activate it during the arming process.
I hope the information is useful to you. greetings

**Comment by 321row123** [comment]
Yes, it would be very useful to be able to have the option to after entering the house after putting the disarm key that auto-arms again. Since there are several of us at home who enter at different times during the day and with the daytime alarm, each one who arrives must disarm and arm the second after his arrival. It's possible?
