### ISSUE TITLE
Fire Alarm always active

### ISSUE THREAD

**Issue by syntos** [nielsfaber/alarmo#673]
I'm using Alarmo as my home alarm system.
All windows and doors are equiped with wired sensors to activate the alarm.
An indoor en outdoor siren are used to sound the alarm.

I also have wired smoke detectors and I would like to create a seperate fire alarm system that's always active regardless of the state of the security alarm system. In case of fire, only the indoor siren should sound and push notifications should be sent to our smartphones.

In case of fire I want to be able to disarm the fire alarm with a seperate alarm control panel card requesting a PIN code to disable the fire alarm system. I have multiple tablets running dashboards to operate the second alarm panel card.

Is it possible to achieve this with the current version of alarmo?

Thank you.

**Comment by nielsfaber** [comment]
You can create a separate area and assign your smoke detectors to this area.
Each area has its own alarm control panel entity in Alarmo, so it will remain independent of the burglar alarm.

Note that by default, the smoke detectors are marked as environmental sensors.
These will have the 'always on' property set, so also when when the alarm is disarmed it can be triggered.
Since you want to stop the fire alarm by means of PIN code, you might want to turn off this setting (and keep your fire alarm armed permanently).

From what I can see all is in place to help your use-case. 
You may close the feature request.
Please use the forums to ask questions about configuration, since other users may be able to help you.
