### ISSUE TITLE
Add Feature Rich User Friendly Action UI Part

### ISSUE THREAD

**Issue by simpan** [nielsfaber/alarmo#68]
Love how you have made the alarm functionality so user friendly and (almost) gathered everything under one UI.

I have some ideas on how to make it a more "complete" and very user friendly integration for setting up your alarm in HA, from start to last action. 

What I felt was missing when I set it up myself was the action parts.
I set up the alarm states, sensors, users etc then ok now I want my alarm to actually do something when it triggers/disarms etc but had to switch from the nice UI to YAML to get my speaker to play different TTS or local files when arming or disarming the alarm. I want to flash all my lights, take a snapshot with my camera and start recording and upload them somewhere but then i was left to yaml and script when everything else is setup with a nice UI so everyone could do it.

So one idea is to for example add a menu item before "Actions" named "Entities" where you can add entities(from specific domains) similar to how sensors work and also group these entities like the new feature you added for sensors, Device Type.
The main things i thought of would be media_players so it tells me straight that my balcony door is open, close it before arming again. Tell me how many seconds I have left to enter the disarm code. Also when the alarm triggers you can play a siren sound on high volume without the need to buy a stand alone siren with a switch to turn on and off. Or a nice welcome message when you have entered the disarm code,

Under create Action you already have the UI to pick when this action should occur, we just have to check what domain/device type they picked and from there display different options. 

Other examples that are very popular from my research on what people usually want to do is flashing lights for example, so the ability to add entities from the light domain so they can get access to set color, brightness etc.

Camera entities would also be a fantastic entity to easily be able to add as an action for snapshots, start/stop recordings.

There are some really nice things that could make this integration very easy to use for everyone and still have the flexibility to let users call their own scripts and service calls, all under one UI.

Maybe I'm way off course and missed something obvious but I would be willing to spend some time on this, many things I will do anyway but maybe not add all the UI stuff if it's not something you or other users think would benefit other users.

PS. Sorry if i have posted this in the wrong section or something, tried to find you on discord to first check if it sounds interesting at all but coulnd't find a way to contact you, personally i rather use this part to specific issues. If im way off could someone please point me in the right direction on where i should post this or how to send a PM or similar to @nielsfaber

Best Regards Simon

**Comment by nielsfaber** [comment]
Hi Simon,
I'm Glad you took the initiative to open this discussion!

I completely agree with you that the actions/notification UI is very limited and deserves more attention.
Looking back, initially (v1.0.0) there was only the option to pick a `switch` entity as your siren device, and enable notifications, which were hard-coded texts.
The added GUI allows you with more control over both items, but still is very basic.
So it's a work-in-progress.

The whole reason I added this function, is because I'm not a big fan of automations in HA.
The GUI for creating automations in HA is very confusing to me, and with YAML I find that the files tend to grow very long and I lose overview.
Then there are the "device automations" in HA, which I never really gave a try:
![image](https://user-images.githubusercontent.com/16861605/102324349-065d2c80-3f82-11eb-9428-56025c812c8a.png)

I would like to avoid making a duplicate of the automations implementation in HA.
All functionality that you want to add can already be achieved through automations.
So it's important to keep asking if it's really worth the effort to keep expanding the Actions for all possible use-cases.
Adding functionality to the UI could make it look confusing at some point, ideally i would like to keep things simple, without making it feel restricted.

I do agree that I heard a lot of users talk about wanting to use smart speakers / tts for notifications, and also the flashing of lights, and the ability to run an action for X time and then abort it (optionally with a closing action).

Currently my priority is creating support for multiple areas/zones, which can each be independently armed/disarmed.
I consider this a core function, which is really restricting usage currently.
While working on this, I'm hoping everyone is able to find a way to combine Alarmo Actions with HA automations, to fit their use-cases.

Let's keep the discussion open for what would be good additions for the Actions/Notifications.
It would be helpful to me if we can place things in the right order (prioritize), and also think about how the GUI should look to be kept simple.
Yesterday I added a new graphical dropdown list to Alarmo, think it would be a great way to give the user a choice over various type of actions, and have the GUI adapt to it:
![image](https://user-images.githubusercontent.com/16861605/102325872-f9d9d380-3f83-11eb-9d0f-e7051751998e.png)

Anyway, I'd like to ask you (and others) for some patience.
I know Alarmo looks simple, but creating it is not (at least not for me).
I would like to have the community decide which features will be added next, so it's helpful to me that you take the effort of sharing your ideas. 
Maybe we can open some sort of vote on which feature(s) are missed the most, to create a wishlist.

**Comment by InjunBob** [comment]
I think you are right in focusing on the basics of an alarm system (first), and leave parts that can be achieved elsewhere (more or less easily) aside for the time being. For my part, I only just installed Alarmo (as it sounded exactly what I was looking for - a basic, simple, easy to manage alarm panel), and one thing I miss out of the box: delayed triggering of alarm based on which zone triggered it. Triggering the alarm should only be delayed for regular access points to the house (front door open and motion, garage door open and motion) to leave time to turn off the alarm. All other sensors, when detecting motion, window opening or vibration etc., should trigger the alarm right away - no delay.
Maybe create a feature request list, where everyone can vote their priorities? And you to decide if you agree with them, of course :)

**Comment by nielsfaber** [comment]
> one thing I miss out of the box: delayed triggering of alarm based on which zone triggered it. Triggering the alarm should only be delayed for regular access points to the house (front door open and motion, garage door open and motion) to leave time to turn off the alarm. All other sensors, when detecting motion, window opening or vibration etc., should trigger the alarm right away - no delay.

This is already in place. Tell Alarmo which sensors are doors/windows/motion etc.

**Comment by InjunBob** [comment]
> > one thing I miss out of the box: delayed triggering of alarm based on which zone triggered it. Triggering the alarm should only be delayed for regular access points to the house (front door open and motion, garage door open and motion) to leave time to turn off the alarm. All other sensors, when detecting motion, window opening or vibration etc., should trigger the alarm right away - no delay.
> 
> This is already in place. Tell Alarmo which sensors are doors/windows/motion etc.

So sorry - just discovered this in "advanced settings" :) Thanks for a very quick reply; will do some more exploring before further comments!

**Comment by nielsfaber** [comment]
@InjunBob That’s alright. Documentation is quite minimal still, so there’s a bit of a learning curve.
I like the idea of voting for feature requests, I will use the forums for that.

**Comment by dannymertens** [comment]
> @InjunBob That’s alright. Documentation is quite minimal still, so there’s a bit of a learning curve.
> I like the idea of voting for feature requests, I will use the forums for that.

Hi Niels,

Is the voting system already online? love to follow the future developments of this great tool!

Thanks!

**Comment by nielsfaber** [comment]
@dannymertens You can vote by giving a thumbs up to someone else's feature request.
If everyone would do this, it would help me prioritize improvements
