### ISSUE TITLE
Add support for smoke, CO2, and leak sensors.

### ISSUE THREAD

**Issue by guystreeter** [nielsfaber/alarmo#69]
I'd like to monitor smoke, water leak, and carbon dioxide monitors, in addition to intrusion sensors.

Perhaps even add over- and under- temperature sensors.

**Comment by nielsfaber** [comment]
This is already in place:
![image](https://user-images.githubusercontent.com/16861605/102368483-2f4de380-3fbb-11eb-8e57-82735fd1b114.png)
Such sensors will always trigger the alarm, even if disarmed.

**Comment by guystreeter** [comment]
Where is that setting? I'm on v1.4.0, and I can't find it.

**Comment by nielsfaber** [comment]
By clicking on a sensor in the sensors page

**Comment by guystreeter** [comment]
OK, so the problem is my smoke and CO2 detectors are not listed on the sensors page, even if I select "show all". They are sensor entities.
Should I open a separate issue?

**Comment by nielsfaber** [comment]
No need for a separate issue..
Alarmo only supports binary_sensors.
This is also [documented](https://github.com/nielsfaber/alarmo#sensor-configuration).

The problem is that a normal sensor can have multiple values, Alarmo has no clue which are considered safe and which not.
You can consider making a [template binary sensor](https://www.home-assistant.io/integrations/binary_sensor.template/) for them.
