### ISSUE TITLE
Different sensor activation options

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#7]
As discussed on the Home Assistant forum, there should be some different options around each sensor. My existing alarm system is really good for this. So you can set a sensor to be:
- Immediate
- Entry/Exit 
- 2x Entry Delay
- 4x Entry Delay
- Fire

Immediate is as you currently have, whilst entry/exit allows the current delays. 2 and 4 times are useful for things like garages where the garage door opens but you don't necessarily get in to turn it off quickly enough.

Fire will always cause the alarm to go off whether the alarm is activated or not.

Hopefully you can implement something like this - would be great!

**Comment by nielsfaber** [comment]
I added some extra options:
![image](https://user-images.githubusercontent.com/16861605/99285689-2b9e3400-2838-11eb-95fb-96a4595ca9ca.png)

The always-on mode causes immediate triggering (regardless of the alarm state).
The 'allow open' setting ignores the state of a sensor when transitioning from arming -> armed. After that, the sensor is watched for a OFF->ON transition (so it may remain ON for a while longer).

I'm not sure about the 2x/4x entry delay yet.
In that case I might as well make the delay a property of a sensor instead of the arm-mode.

**Comment by stefanolson** [comment]
I wonder for each sensor if it should be a drop-down with the options:
Immediate on armed
Entry/Exit
2x Entry Delay
4x Entry Delay
Immediate siren (i.e: Always sensing)
Notify but no siren (see below)

Otherwise the dialog could get a bit complex.

Sadly can't currently test this as it's not picking up any sensors. It is not picking up the updater sensor anymore :-(.  Interestingly it's not even picking up the Shelly overheating sensor which I would expect I should be able to add to the alarm:
binary_sensor.downstairs_office_light_overheating

If it's overheating, I'd want to be notified immediately, although in that case may not want the siren to go off so maybe there should be another one in the list above, Notify but no siren.

Stefan

**Comment by stefanolson** [comment]
Fyi: overheating sensor details:
friendly_name: Downstairs Office Light Overheating
device_class: problem

**Comment by nielsfaber** [comment]
Hi Stefan,

I like your idea about having a dropdown per sensor for choosing the response. 
I will think about it, and check how much effort it would be to implement.

Regarding sensor types, check here:
https://github.com/nielsfaber/alarmo/blob/a4ae0acf20d499c248720e9d294774014ac884e9/frontend/src/data/sensors.ts#L15

I made some stricter filtering because I found the candidates list to be filled with irrelevant entities.
It would surprise me if you have not a single entity of the allowed types, it would mean you have no real security devices yet.

The filtering is not meant to be bothering/limiting.
I will consider to add some way of selecting an entity that is not in this list as well.

You could consider to add some template binary_sensors, which check the state of an input_boolean (this is how I test).
For these entities you can define any device_class.

**Comment by stefanolson** [comment]
No, haven't got anything set up yet after our previous discussion about the Konnected alarm.  Been looking at your suggestions, plus want to make sure that alarmo has all the features I need to replace the existing alarm.

I'd really like the shellys overheating sensors to be able to be used on the alarm (which makes me think maybe it would be good to be able to group sensors by type - so those sensors are in a group to just notify, the fire alarms notify and set off the siren and then I can put the entry zones into a group, and the 2/4x in a group and the others in an immediate if armed group. But not sure whether you can structure it that way on the backend or it would end up looking too confusing anyway). So would be good to be able to add extra binary sensors.

I'll try and figure out how to set up template binary_sensors. 

Thanks!

Stefan

**Comment by nielsfaber** [comment]
I'm closing this issue.
As for your original request:
> 2x Entry Delay
4x Entry Delay

Will not be implemented.

Instead I hope the support for multiple areas (with their own timing) will help/solve your use-case.
