### ISSUE TITLE
Alarmo

### ISSUE THREAD

**Issue by dreyerc6554** [nielsfaber/alarmo#700]
### Alarmo Version

v1.9.8

### HA Version

2023.4.2

### Bug description

This Alarmo entity is missing according to the Watchman report. 

+-------------------------------------+---------+----------------------------------------------------------------------------------+
| Entity ID                                          | State   | Location                                                                         |
+----------------------------------------------------+---------+-------------------------------------------------------------------+
| alarm_control_panel.alarm                          | missing | custom_components/alarmo/services.yaml:9,59  

### Steps to reproduce

I have commented out all references to this entity, uninstalled the addon & deleted all the Alrmo files, 
Run the Watchman report - no missing entity - obviously.
Re-installed the HACS addon, and reboot but the error message remains. 

Please advise what needs to be done to clear this missing entity from the Watchman Report.

### Relevant log output

```shell
+-------------------------------------+---------+----------------------------------------------------------------------------------+
| Entity ID                                          | State   | Location                                                                         |
+----------------------------------------------------+---------+-------------------------------------------------------------------+
| alarm_control_panel.alarm                          | missing | custom_components/alarmo/services.yaml:9,59
```

**Comment by iAutom8** [comment]
Hello,

I can also confirm this.  

If lines 9 and 59 on service.yaml are changed from 
`      example: "alarm_control_panel.alarm"`
to 
`      example: "alarm_control_panel.alarmo"`
the issue goes away.

However, this is an issue with Watchman as it should ignore the contents of ` example: ` from the file.  While the above change will remove the error from Watchman on a new install of Alarmo, if the Alarmo entity id is changed, Watchman will pick it up as an issue again.  

Therefore the fix is not a solution, and the issue should be logged with Watchman.

Thank you and this integration is awesome!

**Comment by dreyerc6554** [comment]
Thank you. Issue resolved.
I have tried this but think a restart was not good enough and maybe forgot to reload Alarmo to refresh the files.

**Comment by nielsfaber** [comment]
False bug report
