### ISSUE TITLE
Cannot go to state armed_away from state triggered.

### ISSUE THREAD

**Issue by kroese** [nielsfaber/alarmo#707]
### Alarmo Version

v1.9.8

### HA Version

2023.4.6

### Bug description

When I leave my house, it triggers the alarm because of frontdoor motion, that is fine.  But another automation detects my presence being away, and tries to set Alarmo from armed Home mode to armed Away mode.

And this causes the following error in Alarmo:

`Cannot go to state armed_away from state triggered.`

Maybe I can workaround this by introducing all kinds of delays in the automations, but I'd rather not. 

So why is it not allowed to go from triggered to away mode in the first place?

### Steps to reproduce

- Trigger alarm
- Set away mode
- See it fail

**Comment by nielsfaber** [comment]
This is not a bug, this is by design.
See also the flow diagram in the [documentation](https://github.com/nielsfaber/alarmo#alarm-functionality).
The user is required to disarm the alarm (usually with a pin code) after the alarm was triggered.
If you want to arm directly after, you could change your automation into a sequence consisting of disarming + arming.
