### ISSUE TITLE
Template variable warning: 'open_sensors' is undefined when rendering '{{open_sensors}}'

### ISSUE THREAD

**Issue by kroese** [nielsfaber/alarmo#708]
### Alarmo Version

v1.9.8

### HA Version

2023.4.6

### Bug description

I use the `{{open_sensors}}` in the alarm triggered notification, which usually works fine. But sometimes I see the error:

`Template variable warning: 'open_sensors' is undefined when rendering '{{open_sensors}}'`

I am not sure what is causing this, but could open_sensors not just be filled with "N/A" so that at least the notification doesn't fail.

### Steps to reproduce

- No idea

**Comment by nielsfaber** [comment]
Without providing more information, I don't know how to help.
Perhaps you trigger the alarm via the `alarm_control_panel.alarm_trigger` service, rather than a sensor tripping?

**Comment by nielsfaber** [comment]
In this case, I think your proposal
> could open_sensors not just be filled with "N/A" 

is not really a solution, since there should be an actual sensor which triggered the alarm. The variable should always be defined.

It would help if you could identify in which case you get this situation (reproduction scenario).
In the developer tools -> states you should see this property being populated with the sensor that triggered the alarm.
![image](https://github.com/nielsfaber/alarmo/assets/16861605/828aef2d-cf22-4e83-a1c6-705cc90c86be)
Could you please take a look at this setting next time this occurs (before disarming)?

**Comment by nielsfaber** [comment]
I was assuming the error occurs only when the alarm is triggered, are you suggesting this is not the case?
