### ISSUE TITLE
Alarmo Intergration fails with error

### ISSUE THREAD

**Issue by robertfgoodworth** [nielsfaber/alarmo#722]
### Alarmo Version

v1.9.9

### HA Version

2023.5.2

### Bug description

HACS Alarmo install (Download) appears to be successfull, after a restart of HA, going to HA Settings ->Devices&Services - Intergrations, then adding Alarmo, this fails with a red box around Alarmo stating  "error", refer to logs below.  

### Steps to reproduce

Using the Latest version of HA, Just add Alarmo intergration from the HA intergation page.

### Relevant log output

```shell
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/alarmo/store.py:674
Integration: Alarmo (documentation, issues)
First occurred: 9:40:50 AM (3 occurrences)
Last logged: 4:38:46 PM

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/alarmo/init.py", line 55, in async_setup_entry
store = await async_get_registry(hass)
File "/config/custom_components/alarmo/store.py", line 674, in async_get_registry
return cast(AlarmoStorage, await task)
TypeError: SensorEntry.init() got an unexpected keyword argument 'entity'
```

**Comment by nielsfaber** [comment]
I just tried to perform a fresh install of Alarmo 1.9.9 under HA 2023.5.2.
For me the installation succeeded without problems (no errors in the integrations page, nor the HA logs).

I suggest to take a look in the `.storage` subfolder in your HA configuration folder.
Alarmo stores its settings in a `alarmo.storage` file within this directory.
Based on the error I am suspecting that there is an older version of this file stored, possibly due to a previous installation of alarmo which was not cleaned up properly.
In case you find such file, could you share it here such that I can reproduce the problem?
I am hopeful that after deleting this file the installation succeeds without issues.

**Comment by robertfgoodworth** [comment]
Sorry I deleted the file before reading you entire responce.  This did the trick.  I don't recall trying to use it in the past, then again i've been using HA for a long time now.
THANKS for helping, i'll be sure to contribute to this intergration, great job by the way.
