### ISSUE TITLE
Improvement on excluded sensors with auto-reinclude

### ISSUE THREAD

**Issue by CyborgNL** [nielsfaber/alarmo#729]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [ ]x My request is generic, other users may benefit from it too.

### Proposal
Add the possibility/option to include a excluded sensor after closing closing it.

### Additional info
When arming the alarm and a window is still open the sensor is excluded after the exit delay.
When closing the window after the exit delay, the sensor is included and part of the arming.

**Comment by Extreme79** [comment]
I'm exactly in the same "issue", if I undertand what @CyborgNL saying.
If I have an open window and I exclude it (automatically or bypassing during manual arming), the sensor stay excluded.. so If I close the window and open it again the alarm not trigger (if I'm not doing something wrong!).
Real use case:
1- hot night in the summer, I left a folding window open.
2- Alarm auto arm night by rules at a given time, bypassing all admitted sensors.
3- during the night I decide to close the folding window.
4- an happy burglar decide to force my window and... bingo! burglar wins , because the window was excluded. 

Probably we need an option to "re-enable" excluded sensors on a state change. (window opened > excluded > window closed > auto re-included >safe!)

**Comment by nielsfaber** [comment]
The requested behaviour is not difficult to implement, in fact this is already in place for motion sensors.
Here the setting is called ‘Allow open after arming’.
If you remove the sensor type it becomes available for your window sensors (click the X behind the type to erase it).

This setting should not be combined with the automatic bypassing, since bypassing will remain active until the alarm is disarmed.
In this case you want alarmo to simply ignore the initial state (during/after arming) and only trigger in case of a state change sequence open-closed-open.

Im open to discuss a change in the interface to make the option visible and more clear for everyone.
Please try out the setting and let me know if it satisfies your needs.

**Comment by Extreme79** [comment]
I'll try tomorrow. 
Probably could be done more user friendly.
I'm thinking about an extra option in the 3dot menu of Alarmo card "ignore initial states", and obviously same setting in the sensor settings as the same way as auto-bypass, auto-ignore.
Just my idea 👍

**Comment by CyborgNL** [comment]
I understand what you say but I have still some questions/remarks:
- I do not like to change the sensor type. This makes the total overview of sensors unclear.
- You mention that this setting should not be combined with automatic bypassing. This is option should be possible because I would leave a window open when arming the alarm in some cases.
- Would it be possible to add this option 'Allow open after arming' to the type of window and door sensor)?

**Comment by Extreme79** [comment]
I made some tests today.
As you said, to have the "allow open" option in the UI we have to delete sensor type (and enable "use exit delay", or allow open is not visible) and this make the sensors view unclear as @CyborgNL already said.

Looking from a "regular" user pov, probably it's a little bit tricky to obtain the final result: open the sensor, delete sensor type, activate "use exit delay" that activate the just shown "allow open" option.
I try to figure out what a base user can expect (I work in customers support since 20yrs, so often I try to look the things with a base user pov), and probably find options like the following could be better.

**Auto-Bypass if active**        (@)==
<sub>allow arming the alarm also with active/open sensor, but **without excluding** it. It **will trigger** if you close than open.</sub>
**Auto-Exclude if active**        (@)==
<sub>allow arming the alarm also with active/open sensor, **excluding** it. It will **not trigger** if you close than open.</sub>

If you enable Auto-Bypass it will disable Auto-exclude and viceversa.
And in the alarmo card, in the three dot menu, you can place options with the same logic (exclude open sensors, bypass open sensors).

**Comment by KSchmeeds** [comment]
> The requested behaviour is not difficult to implement, in fact this is already in place for motion sensors. Here the setting is called ‘Allow open after arming’. If you remove the sensor type it becomes available for your window sensors (click the X behind the type to erase it).
> 
> This setting should not be combined with the automatic bypassing, since bypassing will remain active until the alarm is disarmed. In this case you want alarmo to simply ignore the initial state (during/after arming) and only trigger in case of a state change sequence open-closed-open.
> 
> Im open to discuss a change in the interface to make the option visible and more clear for everyone. Please try out the setting and let me know if it satisfies your needs.

I tried this out, and the option for allow open after arming does not show up when clearing the device type.  It does show up for motion device type.

**Comment by nielsfaber** [comment]
I made the 'allow open' setting available for window/door sensors and made the description for the setting a bit more explicit:
<img src="https://github.com/nielsfaber/alarmo/assets/16861605/89ebeafe-a9bc-4bac-b4ba-d1eb6b2944b5" width="75%" height="75%">

I will let you know when this feature is released.

@Extreme79 I prefer not to differentiate between bypassing and excluding, I think this would lead to confusion. In Alarmo they are the same thing and will remain effective until disarming.

**Comment by CyborgNL** [comment]
Thank Niels for the update, much appreciated. 👌🏻

**Comment by Extreme79** [comment]
I'll test It as soon as I’ll back @home
Thanks!👍

**Comment by CyborgNL** [comment]
@nielsfaber This option works if you skip bypass open sensors option when arming the alarm. 
What I noticed is that the notification part does not provide any open sensor info any more when you enable this new option. Is there still a notification possible of the open sensors when arming the alarm?

**Comment by nielsfaber** [comment]
@CyborgNL 
>  This option works if you skip bypass open sensors option when arming the alarm.

Yes, the auto-bypass function causes the sensor to be excluded until the alarm is disarmed. Combining it with the 'allow initially open' wouldn't have any effect, since the sensor is already bypassed.

> What I noticed is that the notification part does not provide any open sensor info any more when you enable this new option. Is there still a notification possible of the open sensors when arming the alarm?

Do you mean with the `{{bypassed_sensors}}` wildcard?
The sensor will not show up here since it is not bypassed (only the initial state is ignored)
I could check if it can be made visible in the `{{open_sensors}}` wildcard instead, but I don't think it does currently (since the initial state is ignored, it is also not reported as an open sensor).

**Comment by CyborgNL** [comment]
Yes that is what I ment.

It would be great if you are able to add this to the notification in the {{open_sensors}} even the sensor is ignored or open when arming. 🤞🏻

**Comment by CyborgNL** [comment]
Hi @nielsfaber any news or status on the sensor reporting part?
