### ISSUE TITLE
Sensor trigger threshold

### ISSUE THREAD

**Issue by noapex** [nielsfaber/alarmo#766]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Add the hability to configure a time threshold for unreliable sensors, particularly motion sensors, in cases where sensor grouping is not feasible. In my scenario, I have multiple motion sensors that are the sole sensors in their respective areas, making it impossible to group them.

### Additional info
It could be a section on "edit sensor" page or in the "advanced" options.

**Comment by noapex** [comment]
Up to avoid close.

**Comment by nielsfaber** [comment]
Sorry for the lack of response from my side.
> Add the hability to configure a time threshold for unreliable sensors, particularly motion sensors,

The problem is that most motion sensors remain on for 30 sec or 1 min after a motion was detected.
Hence the time threshold would have to be set quite high (in the order of mins) for the threshold to have any effect.
As a result the burglar would also have to remain present for that time or he would be discarded as a false trigger.
I think would never become a reliable and universal solution.
I believe placing a second motion sensor is the better approach. I don't agree with your statement of this being 'impossible', but it would involve extra hardware investment and installation.

If you want to implement a time threshold as you proposed, you could do so via a [template binary sensor](https://www.home-assistant.io/integrations/template/#binary_sensor) and use that one instead in alarmo. I believe the 'delay_on' setting provides exactly what you are looking for.

**Comment by noapex** [comment]
Hi! Please, thank you for taking the time to respond.
Didn't know that most sensors behave like that. The ones I use are cheap microwave sensors attached to an ESP board, and those are very erratic.
I'm sorry, I misspoke when i use the word "impossible". What I  meant to say was that in my current scenario, where I have 1 sensor per room, I can't use the grouping functionality.
Thank you for the suggestion of template binary sensors, that may do the trick. If not, I'll have to add sensors.

Cheers!
