### ISSUE TITLE
Alarmo doesn't work 

### ISSUE THREAD

**Issue by actabi** [nielsfaber/alarmo#776]
### Alarmo Version

v1.9.10

### HA Version

2023.7. 3

### Bug description

From the start I've been unable to start alarmo. When I click on any button to arm the alarm nothing happens. I'm not sure how to help you. If you need more information, let me know how to proceed. I've activated the log remount, restarted the alarmo plugin and this is what I see in the logs :

Logger: homeassistant.components.alarm_control_panel
Source: helpers/entity_platform.py:607
Integration: Alarm control panel (documentation, issues)
First occurred: 08:49:56 (1 occurrences)
Last logged: 08:49:56

Platform alarmo does not generate unique IDs. ID alarm_control_panel.alarmo is already used by alarm_control_panel.alarmo - ignoring alarm_control_panel.alarmo

### Steps to reproduce

I tried deleting and reinstalling, same problem. I've checked the configuration.yaml file for duplicates, but I can't find anything. Once installed, sometimes it works, then the next day nothing and sometimes even reinstalling it doesn't work.

**Comment by calz64** [comment]
I have the same problem.
Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3

**Comment by reubano** [comment]
Not working for me either. I've tried 1.9.6 through 1.9.10.

Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

**Comment by XxCabbyoO** [comment]
Have you unrecognized entitys? Just disable them and test again:

-> https://github.com/nielsfaber/alarmo/issues/773#issuecomment-1648482097

**Comment by nielsfaber** [comment]
Please check the developer tools -> states and look for the `alarm_control_panel.alarmo` (or similar) entity.
The error message suggest that HA has created a duplicate entity `alarm_control_panel.alarmo_2` (or similar).
If you find that alarmo 'doesn't work' this could be caused by the wrong/old entity being controlled, which has become unavailable.
This issue is also described [here](https://github.com/nielsfaber/alarmo/issues/704). Unfortunately I don't know what causes it, so I haven't been able to address this.

**Comment by nielsfaber** [comment]
@Multipage 
> I've just spend hours trying to find out why i can't arm through Alarmo. 

> 1 door was open....no error, no notification. 

> Strangely enough i was able to arm/disarm after a reboot without a problem with the door open

This all sounds pretty horrible, not at all the experience I intended to create.
Is this behaviour reproducible for you?
If so, could you create a separate bug report for it and share your findings?
I just opened a door and restarted HA, afterwards I couldn't arm because of this door. I wonder what is going on in your setup. 

Generally, I recommend users to install the alarmo-card. 
It's pretty much the same as the default alarm panel card in HA, but should give a clear feedback of what's going on:
<img src="https://github.com/nielsfaber/alarmo/assets/16861605/dce136ff-0be4-4316-b2af-2e1aca978483" width="75%" height="75%">
