### ISSUE TITLE
Menu Alarmo doesn't appear on left

### ISSUE THREAD

**Issue by Arctan13** [nielsfaber/alarmo#787]
### Alarmo Version

v1.9.10

### HA Version

2023.8.3

### Bug description

After installation, Alarmo doesn't appear on left.

### Steps to reproduce

I remove Alarmo and try again : idem !

**Comment by Arctan13** [comment]
In fact, the entity "alarm_control_panel.alarmo" is not in the list of entities. It means that there is a problem in the installation.

**Comment by nielsfaber** [comment]
This is not a valid bug report.
Follow the installation steps here: https://github.com/nielsfaber/alarmo#installation

**Comment by Arctan13** [comment]
I tried the two possible installations:
- using HACS
- manually
Every time I can't get the Alarmo menu to the left. The "alarm_control_panel.alarmo" entity is not added to HA. Indeed, this is not a bug specific to Alarmo, but it is an installation problem. Someone can help me ?

**Comment by abate** [comment]
same problem here. I've tried with 1.9.{8,9,10} . Either this is a long standing problem, or a most probably with my local configuration... but I'm not sure how to debug it.

**Comment by Arctan13** [comment]
For me HACS is version 1.32.1

**Comment by nielsfaber** [comment]
Is alarmo installed as an integration?
In other words, under settings -> devices & services, in the integrations tab, you see this tile:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/cd91bbf7-08e1-428c-8cca-23052d66cbb8)

Since you don't provide any details of which steps you performed for installation, I can only guess what went wrong.
Some extra info would help.
Perhaps the HA log shows some error?

**Comment by Arctan13** [comment]
Thank you for your answer.

I found the solution on another forum. I hadn't done the last manipulation.
Sorry for the inconvenience.
