### ISSUE TITLE
Open_sensors attribute is not updated in HA

### ISSUE THREAD

**Issue by nielsfaber** [nielsfaber/alarmo#79]
Note to myself:

Open_sensors attribute is not updated in HA.
Occurs when using exit delay = 0, transition from Disarmed->Disarmed.
Check lines 433+:
```
                # Go to Disarmed state in an Unknown state or Arming state
                if not self._state or self._state == STATE_ALARM_ARMING:
                    await self.async_update_state(STATE_ALARM_DISARMED)
```

**Comment by bjw-s** [comment]
Hi! I’m not 100% sure that what I’m seeing is related, but if I follow the code, it might be:

Use case: I want to write an automation (outside of the alarmo UI) that sends me a notification when the alarm cannot be armed. 

Situation: I have arm_home, arm_away and arm_night enabled, all with exit delay > 0. When I open a window and try to arm the alarm I see a line / event in the logs stating that the alarm cannot be armed. However I cannot see anything changing on the `alarm_control_panel` entity in HA, and I also am not able to see this event when I subscribe to `*`. Am I missing something?

**Comment by quizzical86** [comment]
hello there,
As I discovered this issue I'll explain it:
If you have exit delay = 0 and try to arm the alarm, but for example a window is open, it will fail to arm.
As this is a transition from disarmed -> Disarmed, Alarmo does not send an update to home assistant and therefore the Open_sensors attribute does not get filled in with the problematic sensor.

If however you set an exit delay >0, when you try to arm, the alarm will go to 'arming', and after arming it will try to arm, but fail due to the open window.
It will therefore transition from arming->disarmed, alarmo sends an update to home assistant and the open_sensors attribute does get filled in with the problematic sensor.
So the way to catch an issue with arming for the moment (until the bug is fixed) is to set an exit delay and then monitor for changes to the open_sensors attribute.

**Comment by nielsfaber** [comment]
This should be solved in v1.5.0.
Please try it out 👍

**Comment by quizzical86** [comment]
I tested it and it works, thanks a lot @nielsfaber

**Comment by bjw-s** [comment]
Yes, it seems to work for me too, thanks!! 👍
