### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by mccoy88f** [nielsfaber/alarmo#81]
Hi, i wrote italian translation...
Please add to the next release
https://pastebin.com/tTdxaZH2
Thanks

**Comment by nielsfaber** [comment]
Thank you.
Could you create a pull request for this translation?
You can do this by going here: https://github.com/nielsfaber/alarmo/tree/main/custom_components/alarmo/frontend/localize/languages

And then adding/uploading the `it.json` file by clicking here:
![image](https://user-images.githubusercontent.com/16861605/103257832-241f8e00-4993-11eb-8642-c7086f462270.png)

It helps us both, because it makes it easier for you to make updates to the translation file later, and they are automatically included in the next update (i only have to approve your changes).
Give it a try 👍

**Comment by mccoy88f** [comment]
Got it 👍
