### ISSUE TITLE
Alarm Panel Sounds for states

### ISSUE THREAD

**Issue by feradelectronics** [nielsfaber/alarmo#813]
Alarm Panel visible to play sounds for different states, eg. beep when arming. (faster beep 10 seconds remaining) similar to DSC.,

  - Have these sounds customizable or TTS option
  - expose / know exact status of delay countdown timer eg. 33 seconds remaining

**Comment by stonegray** [comment]
You can do this using Browser Mod (https://github.com/thomasloven/hass-browser_mod)

- Create a Helper switch called "Alarm Warning Chime"
- Add an Automation that triggers on "When Alarm Warning Chime changes from any state to On" and plays media on your tablet, and stops it "When Alarm Warning Chime changes from On to any state"
- Configure Alarmo->Actions to turn the Alarm Warning Chime on and off when entry delay starts

If you want the beep rate to change, just make a 30 second audio clip with whatever audio pattern you like.  You can either use the builtin Play Media function and upload an Mp3 through the web UI, or use Browser Mod's javascript service if you want a bit more control over volume and stuff. 

I only use it to warn on entry, as I use my door sensor to arm Alarmo instantly after I request arming and the door closes behind me. You can likely share the same warning on entry, so it would just be two Actions in Alarmo.

**Comment by feradelectronics** [comment]
Thanks, I will try thatSent from Outlook for Android

**Comment by stonegray** [comment]
From a feature request perspective, I think there's a general need for people (esp. with wall mounted tablets) to play sound that is more generic than just Alarmo, and it could be out of Alarmo's scope for this reason. 

It would be a TON easier if Alarmo would support calling Services directly instead of needing to create a helper switch, now that I think about it it's a total hack. Alarmo currently only seems to allow switch/lights and notifications.
