### ISSUE TITLE
Add Conditions to Notifications and Actions

### ISSUE THREAD

**Issue by Eeeeeediot** [nielsfaber/alarmo#82]
Alarmo is great - well done!. It would be great if conditions could be implements for notifications/actions.

I want to turn on a garden strobe light when my alarm is triggered. BUT, I only want to turn it on when its the garden motion sensor that has triggered the alarm and if its dark outside (binary_sensor.above_horrizon =='off').

Currently, I need to have this automation in a yaml package to supplement Alarmo.

EDIT: on reflection, maybe integrating blueprints in the alarmo ui will solve alot of your issues/feature requests.

**Comment by nielsfaber** [comment]
I'm a bit struggling with how far to go with these actions.
I want to avoid creating a second 'automation engine' since this is already in HA.
I like the idea of supporting blueprints that can be shared from user to user, but I think they will be installed outside of Alarmo.

I propose that you close this issue and add your wishlist/ideas in this issue: https://github.com/nielsfaber/alarmo/issues/68
It will be helpful if we can create some sort of discussion and filter out which features are most needed.
