### ISSUE TITLE
Reloading groups triggers alarmo event and eventually resets alarm state to disarmed

### ISSUE THREAD

**Issue by mleiber** [nielsfaber/alarmo#828]
### Alarmo Version

v1.9.12

### HA Version

Home Assistant 2023.10.5

### Bug description

Reloading groups causes alarmo to send an event and (eventually) reset the current alarm state.

The ``trigger.from_state.state`` in this event seems to be always ``arming``, independent of what the current state is. The ``trigger.to_state.state`` is alwas ``disarmed``. See automation trace output below.

If the alarm state machine is currently not ``disarmed`` then this event will reset the alarm state to ``disarmed``.

### Steps to reproduce

- define HA binary_sensor groups of contact and motion sensors
- use those groups (not the individual sensors) in the sensor settings for alarmo
- reload group definition in Developer Tools
- debug the state event coming from alarmo
- observe a state change event being received

YAML trigger setup to receive the state events:

```
  - id: e46b02f1-1234-5678-9534-3d7899208aac
    alias: 'Alarm State Machine'
    trigger:
    - platform: state
      entity_id: alarm_control_panel.alarmo
      to: null
```

### Relevant log output

```shell
Trigger information:

this:
  entity_id: automation.send_notification_when_alarm_triggered
  state: 'on'
  attributes:
    id: e46b02f1-f721-41fa-9534-3d7899208aac
    last_triggered: '2023-11-01T15:30:08.089137+00:00'
    mode: restart
    current: 1
    friendly_name: Alarm State Machine
  last_changed: '2023-11-01T15:06:31.603617+00:00'
  last_updated: '2023-11-01T15:30:08.089233+00:00'
  context:
    id: 01HE5R362RCE00E54BR4P6ESJ9
    parent_id: 01HE5R362JT0M8TBH98S6RYKM4
    user_id: null
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: state
  entity_id: alarm_control_panel.alarmo
  from_state:
    entity_id: alarm_control_panel.alarmo
    state: arming
    attributes:
      code_format: null
      changed_by: null
      code_arm_required: false
      arm_mode: armed_away
      open_sensors: null
      bypassed_sensors: null
      delay: 15
      ready_to_arm_modes:
        - home
      icon: mdi:shield-home
      friendly_name: Alarmanlage
      supported_features: 11
    last_changed: '2023-11-01T15:30:22.401578+00:00'
    last_updated: '2023-11-01T15:30:22.407532+00:00'
    context:
      id: 01HE5R3M1AWT7A4P0JMJ0PREND
      parent_id: 01HE5R3M12G1WVJT9YK4ZVBBBB
      user_id: null
  to_state:
    entity_id: alarm_control_panel.alarmo
    state: disarmed
    attributes:
      code_format: null
      changed_by: null
      code_arm_required: false
      arm_mode: null
      open_sensors: null
      bypassed_sensors: null
      delay: null
      ready_to_arm_modes:
        - home
      icon: mdi:shield-home
      friendly_name: Alarmanlage
      supported_features: 11
    last_changed: '2023-11-01T15:30:22.455948+00:00'
    last_updated: '2023-11-01T15:30:22.455948+00:00'
    context:
      id: 01HE5R3M23G4TPM94DTD7R9SR0
      parent_id: 01HE5R3M1S025NSS6T41D0AX75
      user_id: null
  for: null
  attribute: null
  description: state of alarm_control_panel.alarmo
_to_state: disarmed
_from_state: arming
```

**Comment by nielsfaber** [comment]
I tried to reproduce the issue but couldn't.
I created the following group (back door and motion entrance are a contact and motion type binary_sensor).
![image](https://github.com/nielsfaber/alarmo/assets/16861605/d2ea5dca-7145-41f4-be48-7c414be502e8)

I removed the back door and motion entrance sensors from alarmo, and added the created group (also assigned it to the 'home' and 'away' modes):
![image](https://github.com/nielsfaber/alarmo/assets/16861605/0cb00baa-d525-41a5-8a1b-2b8efa04e9e9)

I created an automation to trigger on state change of alarmo:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/7d936322-cfe1-46f2-ae41-4eac221a2b86)

With the alarm in disarmed state, I reload the group configurations:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/589a096a-0c62-4a54-9d0b-c880044b9209)

But for me the automation is not triggered due to the reloading:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/511933d1-0d03-4afe-a187-0853b68c8f29)

**Comment by mleiber** [comment]
Thx for the thorough investigation. 

hmmm, so something else must contribute to this behavior. I will dig deeper and also provide you with more details of my configuration. It'll take a day or two to get to it.
