### ISSUE TITLE
Require code for switching mode is always required even if off

### ISSUE THREAD

**Issue by cromelex** [nielsfaber/alarmo#838]
### Alarmo Version

v1.9.13

### HA Version

2023.11.1

### Bug description

If I switch between different alarm modes, where previously it would not require the code, Alarmo is now requiring me to input the code to change the mode.

Example, Armed Home to Armed Night, or Armed Night to Armed Home.
When I do the mode change, the code/pinpad shows up and requires me to input the code to change the mode.

Require code for switching mode is always required even if off in the settings. I have tried turning it on (in case it was reversed in the settings) but that doesn't solve it.

Interestingly, if I do this change, despite using the pin/passcode, the last_changed attribute stays as null

_changed_by: null_

### Steps to reproduce

Changing the alarm mode from Armed Home to Armed Night or vice versa.

**Comment by nielsfaber** [comment]
I think you are reporting a false bug report, because the changed functionality has been tested.

> Example, Armed Home to Armed Night, or Armed Night to Armed Home.
When I do the mode change, the code/pinpad shows up and requires me to input the code to change the mode.

Shows up where?
That the keypad shows up is probably unrelated from alarmo.
Try to switch the arm mode via the Developer Tools -> Services panel (use service alarmo.arm or alarm_control_panel.alarm_arm_away, etc.). It should work without entering a code (if you configured it like this).

**Comment by cromelex** [comment]
Showing up in the GUI.

I will double check - I updated HASS on the same day, maybe the GUI bug is actually coming from there, rather than Alarmo. Or from how Alarmo interacts with HASS.
Given the note of the new option being added on Alarmo, I assumed it was there.

I'll test further and confirm back. My automations in NodeRed are switching between the Alarmo modes end are still working, I'll check if I'm calling the mode changes with or without code to try and figure out exactly where the issue is coming from.

Thanks

**Comment by nielsfaber** [comment]
I found out that the HA frontend checks this property to determine whether or not the keypad must be displayed:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/4088c335-aa90-4f66-ade1-1c7ea3f58bb5)

In alarmo this property is currently only linked to the setting 'Require code for arming'.

I could change the code to look at the setting 'Require code for switching mode' for determining the property, in case the alarm is already armed.

I expect that would improve things for your situation.
However, you should already be able to ignore the keypad and switch mode without entering any code (since Alarmo validates the code).

**Comment by cromelex** [comment]
The HA frontend seems to "force" me to input a code, ie if I press the X to close the box it stays on the original alarm mode.
Alarmo is not validating the code, as you said. If I type a random code it'll still change the arm mode anyway.
I saved a video but can't attach on my phone, will add it here later.

My automations are working, and that's how I interact with Alarmo 99% of the time. It was an exceptional case where I used the HA frontend to change the Arm mode and how I spotted this.

Do you think this is something you should address or do you rather feel like this is a HA frontend bug instead?

To be perfectly honest, it's not an issue for me, I reported it for the sake of improvement - Alarmo has been working really well, and I might just turn on the option to require the code for each change, as that will allow me to log the user doing all the arm-mode changes on a template sensor, as a kind of log.

**Comment by cromelex** [comment]
Just the video demonstrating the frontend situation.
I used a 1234 pin just to show.

https://github.com/nielsfaber/alarmo/assets/96779452/48bd1123-90c0-4a10-8d43-5d97bc2e776c
