### ISSUE TITLE
Alarmo Only Triggers if Sensor in Alarmo Area

### ISSUE THREAD

**Issue by Sinfonia97** [nielsfaber/alarmo#846]
### Alarmo Version

1.9.13

### HA Version

2023.11.3

### Bug description

I have several sensors in different configured areas.  When Alarmo is armed, only those sensors that are configured in the Alarmo area will change the Alarmo state to triggered.  I have been able to move one of my sensors to the Alarmo area and it will change the Alarmo state to triggered.

This is a manual installation of Alarmo as I have been using prior to it being available through HACS.

### Steps to reproduce

Create additional areas in Alarmo and add sensors that are configured for Armed Home or Away to trigger in those additional areas.
Arm Alarmo to either home or away.
Open the sensor in that new area.
For me I can see the state of the sensor change to open, but Alarmo does not trigger.

### Relevant log output

```shell
There are no entries in the log files to indicate an error.
```

**Comment by Sinfonia97** [comment]
This is still an issue for me and is requiring me to move all sensors out of the assigned rooms/locations to be able to trigger the alarm.  Has anyone run into this issue or tested it to see if it is occurring in their Alarmo configuration as well?

**Comment by nielsfaber** [comment]
> I have several sensors in different configured areas. When Alarmo is armed, only those sensors that are configured in the Alarmo area will change the Alarmo state to triggered.

To me this sounds like how it is supposed to work. 
Perhaps it is more a case of misinterpretation of how this works rather than a bug?

**Comment by Sinfonia97** [comment]
It used to work the other way when I first started using Alarmo.  I had not updated the code in quite some time, so the most recent one is what changed it for me.  I have all of the sensors configured to trigger both home or away modes, but unless they are in the Alarmo Area, they do not trigger the alarm.  I am including some pictures to show you how things are configured.  If I arm Alarmo to either Away or Home, then open one of those office windows it does not trigger.

![2023-12-27 17_20_44-Alarmo – Home Assistant](https://github.com/nielsfaber/alarmo/assets/75184065/9fcb7b84-3df8-4c66-8d5e-8a67a262f26c)
![2023-12-27 17_21_21-Alarmo – Home Assistant](https://github.com/nielsfaber/alarmo/assets/75184065/2fef6da1-a14d-49e6-bb2b-b0015fc2af15)
![2023-12-27 17_21_57-Alarmo – Home Assistant](https://github.com/nielsfaber/alarmo/assets/75184065/a641218f-17e6-47d1-8f61-83e806999e17)

**Comment by nielsfaber** [comment]
> It used to work the other way when I first started using Alarmo. 

Which other way do you mean?
From the introduction of 'areas' in Alarmo (which is in there for over 2 years), each sensor had to be assigned to an area in order to trigger it.

From your screenshots it appears that not every sensor is assigned to an area. Area 'alarmo' has 3 sensors, area 'office' has 4, but your list shows more than 7. You should click on the sensors in the list and assign them to one of the areas.

Note that for the office area, alarmo will create a separate alarm entity (alarm_control_panel.office). This entity needs to be armed/disarmed separately, and will also trigger separately. 
If you wish to use alarmo with all areas simultaneously armed/disarmed, you should enable the 'master' alarm. This will create a 3rd alarm entity which controls all areas together.

**Comment by Sinfonia97** [comment]
Thanks @nielsfaber, I was under the impression that Areas were the equivalent of zones.  I did not realize that these areas created segregated alarms that would each have their own alarm_control_panel.  I've since changed the panel that I was using to the master alarm.
