### ISSUE TITLE
Sensor groups a duplicate sensor in the alarmo.storage file causing bugs

### ISSUE THREAD

**Issue by VNRARA** [nielsfaber/alarmo#868]
### Alarmo Version

v1.9.13

### HA Version

2023.12.3 and older

### Bug description

![image](https://github.com/nielsfaber/alarmo/assets/3942672/884faf68-5f3e-4f73-87b7-c7cd9feec008)

Sensor groups allow a duplicate sensor in the alarmo.storage file causing bugs like #860.

Also random deletions of groups keep happening. 

### Steps to reproduce

Create group with 2 sensors. Come back and see 3 sensors added. File shows a dupe sensor added.

**Comment by VNRARA** [comment]
Log added:
[home-assistant_alarmo_2024-01-02T00-03-23.658Z.log](https://github.com/nielsfaber/alarmo/files/13806372/home-assistant_alarmo_2024-01-02T00-03-23.658Z.log)

**Comment by VNRARA** [comment]
Note: the sensors I try to group are in different zones:

![image](https://github.com/nielsfaber/alarmo/assets/3942672/2a632233-6a07-4121-8e49-f972695fa413)

**Comment by nielsfaber** [comment]
> Steps to reproduce
Create group with 2 sensors. Come back and see 3 sensors added. File shows a dupe sensor added.

In an attempt to reproduce this issue, I created this group with 2 sensors:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/44f4eb49-29c3-4a9f-9819-fb40c2b9e0b6)

When I save this and return later to the page, the group still has still the same 2 sensors, not 3.

Looking at the code, the only situation in which the sensor groups could be modified is when clicking the save button in this dialog.
So:
> Come back and see 3 sensors added. 

As well as:
> Also random deletions of groups keep happening.

Seem unlikely to me, at least I cannot find any reason for this to happen in the source code.

Could you provide more information for me to reproduce the issue?
For example, could you create a screen video in which you create a sensor group and show that it becomes modified when you open it later?

**Comment by VNRARA** [comment]
I'll create a different ticket for this but: Alarmo for some reason also creates duplicate conflicting master alarm entity (usually named house).. idk wtf is going on in the code, but it's very bugged.

**Comment by PowerBat80** [comment]
Hi 
I have the same problem:
If I press "Save" in "Edit sensor" on a sensor that belongs to a group, the sensor is added again to the group. I have made the group with 2 devices and then I have clicked saved 6 times on the Save button :
![Alarmo_DeviceEditSensorWithGroup](https://github.com/nielsfaber/alarmo/assets/155341362/9bfc606a-ecfc-4b32-86f7-753f41be975d) 
Now when I click on "Setup Groups" the group now have 8 sensors:
![Alarmo_ManageSensorGroup](https://github.com/nielsfaber/alarmo/assets/155341362/bf253a80-c1f0-4dfe-a1a3-ae56125558c6)
But when I open the group it has only the 2 sensors selected and I cant save the group due to it contains duplicate items:
![Alarmo_DeviceEditSensorGroup](https://github.com/nielsfaber/alarmo/assets/155341362/073f2c6a-7f61-4916-be02-ef5ac79d852c)

So it seems to save the device into the group when you save the sensor..

Thanks for a very nice integration!
Regards

**Comment by nielsfaber** [comment]
@VNRARA / @PowerBat80
Thank you very much for your input. This helped me identify the issue.
I made a fix for this in the v1.9.14 release. Could you update your local installation and verify the problem is gone for you as well?

**Comment by PowerBat80** [comment]
Hi
It works with editing sensor groups now, thanks!
But after upgrade to v1.9.14 with HACS 1.34.0 and reboot, it still shows v1.9.13 in the Alarmo - Alarm panel?
![image](https://github.com/nielsfaber/alarmo/assets/155341362/2c052d95-73a7-4665-a651-53a7c10b9c51)
BR

**Comment by VNRARA** [comment]
Seems to be working fine now :)
