### ISSUE TITLE
Actions for Androids with buttons are not shown after editing yaml

### ISSUE THREAD

**Issue by fribse** [nielsfaber/alarmo#90]
HA: 2021.1.0
Alarmo: 1.4.1
I've created an Android Action (the suggested failed arming -> retry) with an android.
I know the config is there as the action works, and buttons are shown on the phone, it's shown like this in the UI:

![image](https://user-images.githubusercontent.com/13660621/104153760-7759fd80-53e3-11eb-9125-84b765ae623a.png)

But when I switch to Yaml it shows:
![image](https://user-images.githubusercontent.com/13660621/104153784-8640b000-53e3-11eb-9cc2-fefee3621313.png)

**Comment by lesleypersyn** [comment]
Same here when starting from scratch. Same versions and also tested with 1.4.0.

**Comment by nielsfaber** [comment]
This could be due to HA’s lazy-loading.
Which means that some components (like its yaml editor) are only loaded when the page requires it.
Unfortunately for custom_components there is no option to request the lazy-loading of a component.
I have a workaround in place, which I thought works in 100% of cases, but apparently not.
I will have to investigate this.
If you have tips for reproducing, please let me know.

**Comment by fribse** [comment]
I'm not sure how to force it to reproduce, but if it shows, then I can press F5, and then again do a 'switch to yaml' and it will show the automation normally.

**Comment by nielsfaber** [comment]
I’m having trouble reproducing this issue.
For me the yaml editor appears 10/10 times, no matter in what click sequence I end up there.
Could someone share some pattern that leads to this issue?

**Comment by fribse** [comment]
@nielsfaber I think I can get it to show on a firefox with empty cache, but I can't empty my cache right now 😭
