### ISSUE TITLE
Sensor option 'arm after closing' has no effect 

### ISSUE THREAD

**Issue by erkr** [nielsfaber/alarmo#901]
### Alarmo Version

V1.9.14

### HA Version

2024.2.4

### Bug description

Thanks for this great integration!
I found this advanced sensor option:
![image](https://github.com/nielsfaber/alarmo/assets/4363599/8b09c4c1-2d21-4a4e-be3d-4121fec5a819)
when I  select the option  `arm after closing` it seems to have no effect. Alarm won’t trigger when it was closed and then opened after arming

### Steps to reproduce

“Bypass automatically” is off (not tried while on)
“Arm after closing” is on
“Allow open initially” is off

1: In the card I check the option “bypass open sensors” ( 3dots menu)
2: Then I arm the alarm 
3: close the bypassed door sensor
4: open the door —> no alarm triggered!!!

**Comment by nielsfaber** [comment]
I use this feature on a daily basis in my own house, it definitely works for me.
I doný really understand why you combine it with bypassing sensors, I suggest to try without that.

**Comment by erkr** [comment]
Hi @nielsfaber 

I reported the issue, as it seems that this specific combination of not configuring `allow_open_initially` in the sensor settings and selection the bypass_open option in the card when arming is what doesn't work.

My reasoning not to 
enable `allow_open_initially` as I want to explicitly decide to bypass them when arming (not accidental because they are bypassed automatically).

**Comment by erkr** [comment]
I still think it's a bug

**Comment by erkr** [comment]
Hi Niels,

You mentioned:

> these are different features and should not be mixed
 
So I take that I probably don't fully grasp the concepts, and there is also no restriction in the configuration UI safeguarding me from selecting unintended combinations.

So maybe it is more clear if I try to explain my use case:
```
I don't want to enable `allow_open_initially` 
for some sensors as I want to deliberately decide to bypass them with `bypass_open` when Arming.

But once they are bypassed, it would be nice to re-arm these sensors when closed. That is why I enabled the option `arm after closing`
```

I now understand that `arm after closing` only works when enabling `allow_open_initially`. Right??

If that is the case, it is indeed not a bug, but I believe the UI can guide the novice user better☺️

**Comment by nielsfaber** [comment]
Allow_open_initially is intended for windows.
When it is set, you can leave a window open when arming the alarm, if you later close it, it will be watched (opening again would trigger the alarm).
The behavior is similar to bypassing, only bypassing is permanent until disarming, so sensor will not be watched at all.

The arm_on_close feature is intended for doors. It should not be combined with bypassing or the allow_open_initially function, since they are contradictive.
with the feature enabled, you can open+close the front door and the alarm will become armed (instead of waiting until the exit delay has completed).

I believe that if you set the sensor type correctly, the options that are not suitable will become hidden.
