### ISSUE TITLE
Require Code for Disarming not accepting PIN code

### ISSUE THREAD

**Issue by kjf77** [nielsfaber/alarmo#914]
### Alarmo Version

v1.9.14

### HA Version

2024.3.3

### Bug description

Alarmo has been installed and reinstalled twice.  Nothing I do seems to allow me to enter a PIN code to Disarm the Alarm.  I am set to allow Arm without PIN and Disarm with PIN.  It prompts for the PIN using the keypad but then ignores it and leaves it Armed.  

### Steps to reproduce

Setup Alarmo to require PIN to disarm.
Add a 6 digit PIN for my user account.
Add Alarmo to a dashboard.
Arm the alarm system.
Attempt to Disarm, enter PIN, alarm remains armed.

**Comment by ginkel** [comment]
I am experiencing the same issue with the subtle variation that my code works, but our daughter's code doesn't. Maybe only the first enrolled code works?

**Comment by nielsfaber** [comment]
I cannot help with this bug report. I don't think anything is wrong with the implementation of alarmo related to this.
I suggest to install alarmo-card and use it instead, since this card gives feedback when you enter a wrong code (and will give different feedback in case of a different problem).

@ginkel 
> Maybe only the first enrolled code works?

It should work for all. At least it does for me. I suggest to double-check the user configuration in alarmo. 

If either of you are convinced there is an issue with alarmo, please create a screen video to demonstrate the issue. the video should show the creation of a user with specific pin, followed by trying to (dis)arm using alarmo-card and showing that this pin is not accepted.  For me this works fine, so I don't know what I am doing different than you.

**Comment by ginkel** [comment]
@nielsfaber I tried reproducing the issue with a screen recorder running, but failed doing so. I'm not sure what went wrong when initially creating the users, but right now I think we can consider the issue resolved.
