### ISSUE TITLE
Add event for any sensor being offline 

### ISSUE THREAD

**Issue by danielrosehill** [nielsfaber/alarmo#917]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal

You can use Watchman for this (with difficulty) but ... I think it would be great (and make a lot of sense) if this could be configured directly in Alarmo.

Feature idea: a notification event for any of the sensors in the alarm group turning to unavailable.

This way, users could be quickly notified if any of their sensors (or alarms) goes offline and remedy the problem to avoid degraded security.

### Additional info

A quick sketch to articulate what I was envisioning:

![alarm offline](https://github.com/nielsfaber/alarmo/assets/40233203/1f83e2f9-453c-4e84-9fdc-615525c29d3c)

**Comment by nielsfaber** [comment]
The list of events are all related to the status of the alarm itself, not the sensors.
I don't think this item belongs in the list.
In addition, a decent alarm installation should not have sensors going offline or should not be vulnerable to a sensor going offline. So I would focus on obtaining this, rather than wasting effort on implementation for supporting a vulnerable alarm.
If you want this still, I suggest to create an automation in HA which triggers when any of your sensors becomes unavailable, this should be super simple.
