### ISSUE TITLE
Disarm Notification Is Not Working

### ISSUE THREAD

**Issue by mogultekin** [nielsfaber/alarmo#932]
### Alarmo Version

v1.10.0

### HA Version

2024.4.4

### Bug description

Thank you for this great project. Setup was simple and it works fine from day one to now.
I have made two notifications for Arm and Disarm Triggers. They are running the same script.
The script is setting the volume on my living room speaker to desired level and playing a sound on that speaker.
When I arm the Alarmo the sound plays OK. But when I disarm the sound is not played.

### Steps to reproduce

Arming the Alarmo runs the notification action.
Disarming the Alarmo does not run the notification action.
![image](https://github.com/nielsfaber/alarmo/assets/81960545/b730e536-d840-47bf-ba8e-5895c1517314)

**Comment by nielsfaber** [comment]
For me (and many users) this works without problems.
I just created a notification for testing:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/f4a81d48-be73-45a2-9d97-6f1d926b2b66)

It appears on my phone when disarming the alarm, so works OK.
Perhaps some error occurs and you should check the log for this.

Otherwise, you can enable debug logging for alarmo by adding this to the configuration.yaml file:
```
logger:
  default: warning
  logs:
    custom_components.alarmo: debug
```
When the alarm is disarmed, you should see in the HA logs that the notification is triggered.

**Comment by mogultekin** [comment]
Sorry for the late answer. After a few days opening this issue and a few updates it began working for me also.
