### ISSUE TITLE
Entry zone follower

### ISSUE THREAD

**Issue by jterfehr2000** [nielsfaber/alarmo#934]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [x ] My request is generic, other users may benefit from it too.

Create an advanced option to make a sensor an 'entry follower'.  This means that the 'entry follower' zone has an entry delay ONLY if an entry zone is triggered first.  

For example, you have a front door that has an entry delay, but when you enter the front door, the living room motion sensor will activate.  That living room motion could be programmed as an 'entry follower' so that it also is delayed if the front door opens first.  However, should a bad guy come into that room without entering the front door first then the motion sensor would activate Alarmo immediately.

**Comment by skaggerik** [comment]
I would also like to have this feature!

**Comment by nielsfaber** [comment]
I think this feature is too complex to implement. My concerns:
* users needs o both mark which sensors are 'entries'  and which are 'followers'. So we would need to add 2 options, and the feature only works if both are set (and entry delay is applied).
* historic info of previous sensor triggers need to be kept (e.g. the opening+closing of a door before entering living room)
* the processing of a sensor (follower) becomes dependent of another sensor (entry)

I think it's better to keep things simple. Your living room sensors shouldn't have any entry delay since you don't enter via the living room. Obviously you need to make sure the alarm is disarmed before entering the living room, but I would the expect the marjority of users to have some keypad / rfid scanner / display or similar in the hall.

**Comment by jterfehr2000** [comment]
I understand the complexity and understand it would take a lot, much appreciate you even considering it and providing your feedback.  It is a standard feature on all alarm system panels, however, because not everyone who has access to your house/office will be able to turn off the alarm before entering (like a houseguest, housekeeper, etc.).  Example: The Keypad/tablet is in the living room, and the front door opens to the living room.  That means the front door and the motion sensor in the living room must be delayed if the houseguest is to reach the keypad and turn off the alarm within the entry delay.  However, if someone breaks the glass on the living room window and climbs in (or otherwise subverts your perimeter protection) that motion sensor would also give them enough delay to potentially sabotage the system.  All that said, I think can figure something out using a helper and automation (the helper would be a Boolean of whether or not the front door was triggered in x time).

**Comment by mwareman** [comment]
I have to say - coming from an Elk M1 I really miss not having 'Entry Follower' zone types. I know this request got stale - but really do not want to clutter things with a new request just to get it turned down. I'd just like to add my voice to those also wanting this feature.
