### ISSUE TITLE
Alarm disabled without code in particular conditions

### ISSUE THREAD

**Issue by DaniDF** [nielsfaber/alarmo#941]
### Alarmo Version

v1.10.1

### HA Version

2024.5.3

### Bug description

**General Configuration**:

+ *Disarm after trigger*: disabled
+ *Enable MQTT*: disabled
+ *Enable alarm master*: enabled

**Areas**:

* Area_0:
  * Sensors:
    * sensor_0 (*Allow open initially*: disabled)
* Area_1:
  * No sensors

**Codes**
 + *Require code for arming*: disabled
 + *Require code for disarming*: enabled
 + *Require code for switching mode*: enabled
 + *Code format*: "PINCODE"

When the alarm of the *Area_1* is armed, the alarm of *Area_0* is disabled and the *sensor_0* is "open" (state in which if armed *Area_0* will trigger the alarm).

In this state when trying to arm the master alarm the system immediately disarm all the alarm in all areas without asking the code.

### Steps to reproduce

1. Arm *Area_1*
2. Disarm *Area_0*
3. Put *sensor_0* in "open" state (that will trigger the alarm of *Area_0* if armed)
4. Arm "master"

After these steps the system automatically disarm all alarms without asking the code.

**Comment by nielsfaber** [comment]
> In this state when trying to arm the master alarm the system immediately disarm all the alarm in all areas without asking the code.

What would you expect to happen instead? The alarm master attempts to synchronize the states of all areas, so it should either arm all areas or disarm all areas. In this case arming is not possible, so disarming happens.
It could be argued that it would be better to restore the states of the areas as they were before, but I don't know if this information is available.

In the documentation the following is stated:

> * The Alarm Master cannot determine its state if some are disarmed while others are armed. If the Alarm Master is used for arming/disarming the alarm, this condition should not occur.
> * If the areas are independently operated, the user is reponsible to maintain synchronism between the areas. If independent operation is desired, usage of the Master Alarm is not recommended.

What is meant here, is that users should choose either to operate their areas via the master OR operate the areas independently.
You are using a mix of them, which is very difficult to handle by design.
A lot of scenarios can occur and the implementation will be able to deal with all to your expectation.
If one area is armed and the other is disarmed, the state of the alarm master cannot be determined, also the transitions between states of the areas are not the same.

To extend the discussion, let's consider another (more extreme) scenario:
* area A is in state disarmed
* area B is in state armed home
* area C is in state triggered

User attempts to set alarm to armed away via the master.
However, area B has a sensor active that prevents that area to go into state armed away.
What would you expect to happen to all 3 areas and what should become the state of the alarm master?


If you have a clear idea how the master alarm should behave, I could see if I could improve the implementation.
However since I have been struggling with this during implementation, at the moment the disclaimers in the documentation should be taken as advice/warning.
