### ISSUE TITLE
Not seeing master entity

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#95]
Just installed 1.5.0b.  Looks AMAZING!!! So impressed with your work.

First off, a suggestion:
- when I assigned the garage door sensors to the new garage area I got myself a bit confused because it didn't say that it was enabled for away.  turns out I had to change the area under modes to be enabled for away. I wonder if when you create a new area the modes should just copy the existing area if you only have one area? But maybe that's a silly idea it just wasn't obvious to me how I could get that  sensor assigned to that mode. Turns out that the away mode was off by default, so sorted now.

Now to the issue:
- I can't seem to find the master sensor.  It's on:
![image](https://user-images.githubusercontent.com/1751192/104881009-7a498500-59c5-11eb-932f-ab6bb3acf1de.png)
but the entities don't include it:
![image](https://user-images.githubusercontent.com/1751192/104881062-89c8ce00-59c5-11eb-8f95-96577d656dae.png)

What am I missing?

Anyway, just a fantastic job thank you so much.

Stefan

**Comment by stefanolson** [comment]
Now got it by turning off the master, saving it and then turning on again. may possibly have been an upgrade issue? Other than that everything else appears to have upgraded flawlessly, I'm still not sure what the unavailable entity is here:
![image](https://user-images.githubusercontent.com/1751192/104883202-4a9c7c00-59c9-11eb-9760-8192898dc77e.png)

**Comment by nielsfaber** [comment]
Hi Stefan,
Thanks for liking it.
I hope it also solves the limitations you were having before.
I will check the issue with the alarm master. The entity should always be created when the checkbox is on and you have multiple areas. 

Regarding:
> I'm still not sure what the unavailable entity is here:

This happens.
I wrote a little bit about this in the [documentation](https://github.com/nielsfaber/alarmo#areas):
> After renaming an area, the old entity ID may appear again in your entities list after a restart of HA. This entity shows up as unavailable and has to be deleted manually.

I would prefer to have this entity removed completely, but I don't know how I can force this. 
Documentation on the HA side is very limited... The developers basically say: 'just learn from existing code'.

**Comment by stefanolson** [comment]
Hi,

Yes, it looks like it will be brilliant for me! Thanks.  You have done such a fantastic job.  Hope you can add donate option on the github page too...

The alarm master was on by default, don't know if that makes any difference.  In other words I didn't actually turn it on and then click save.

Re: unavailable entity, sorry missed that in the docs:
After rebooting home assistant it is available again:
![image](https://user-images.githubusercontent.com/1751192/104885197-85ec7a00-59cc-11eb-91b9-ec2033cb43e3.png)

Don't know if I should delete it now or not?

**Comment by nielsfaber** [comment]
Hi Stefan,

I just released v1.5.0 which should take care of the issues you reported.
Sorry for the wait!

> wonder if when you create a new area the modes should just copy the existing area if you only have one area? But maybe that's a silly idea it just wasn't obvious to me how I could get that sensor assigned to that mode. Turns out that the away mode was off by default, so sorted now.

Done 👍 
![image](https://user-images.githubusercontent.com/16861605/105740085-1d0b8180-5f39-11eb-88d0-756031a813f8.png)

I decided a dropdown would be more appropriate since you can have two areas and create a third (Alarmo doesn't know from which to copy).

> I can't seem to find the master sensor. It's on:
but the entities don't include it:

I found a bug in the code, it should now automatically pop up if you have more than 1 area (no reboots required).

> Re: unavailable entity, sorry missed that in the docs:
After rebooting home assistant it is available again:

I reached out to the dev team, they helped me with a more robust way of removing the entities. It shouldn't occur anymore.

> . Hope you can add donate option on the github page too...

Since you're not the first to ask for this, I added a "buy me a coffee" button. 
I'm really not looking for profits with this project so there is no need for it, but I surely appreciate the gesture.
I cannot deny that donations stimulate me more to keep spending time on Alarmo than the mountain of open bug reports/feature requests 🙂

**Comment by stefanolson** [comment]
All seems good now, so I'll close this.  Thanks for adding the donation button. Will send one soon!
