### ISSUE TITLE
 Ignores open sensors from alarm mode

### ISSUE THREAD

**Issue by array81** [nielsfaber/alarmo#956]
It is possible to have the "ignore open sensors" function at the mode level and not at the individual sensor level. For example, you would like open sensors not to be ignored in "away from home" mode while in "at home" mode they are ignored and in both cases you can receive the notification with the sensors open.

**Comment by andreasbrett** [comment]
Have the same requirement. I want to be able to have my terrace door open when the night-alarm auto-engages, because especially during summer we're still out on the terrace late in the evening. When arming the away-alarm I want to be notified though that I left the terrace door open (as I arm this mode manually and not triggered by automation).

My current workaround: I cloned the door entity with a helper entity (binary sensor template) and add one entity to away mode with "ignore open sensors" unchecked and the other one is added to the night mode with "ignore open sensors" checked. It works but this is cumbersome when you want to have this behavior for more than just 1 sensor.

**Comment by array81** [comment]
I believe implementing the feature is not difficult and could be useful. Managing this manually for different sensors would be a complication.
