### ISSUE TITLE
Failed in call alarm_control_panel/alarm_disarm. AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by pabloandrei** [nielsfaber/alarmo#973]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

V1.10.1

### HA Version

2024.6.2

### Bug description

This bug occurred after informed the password for disarm.

### Steps to reproduce

- after informed the password to disarm.

**Comment by nielsfaber** [comment]
![image](https://github.com/nielsfaber/alarmo/assets/16861605/23c44d77-6822-4ab0-95a0-ab3b2844524f)

**Comment by pabloandrei** [comment]
Tks... bug resolved!

**Comment by Dinth** [comment]
@nielsfaber Sorry for bothering you about this but do you know which change in HA is responsible for this problem? I have looked at the HA changelog and it seems that changes to the alarm were only cosmetic and yet i cannot disarm the alarm neither with Alarm card (standard) and with my automations since updating HA. Same error. Im running Alarmo 1.5.2.
