### ISSUE TITLE
Disable specific sensors temporary with Automation

### ISSUE THREAD

**Issue by GitCharlieHub** [nielsfaber/alarmo#982]
### Proposal
Allow a HomeAssistant automation to disable certain sensors temporarily.

I have a Vacuum robot that works on a specific time schedule. When it's going around the house, it triggers some PIR movement sensors which cause Alarmo to trigger.  However these sensors are critical for the alarm as they are looking for movement near some large windows so I don't want them disconnected from Alarmo permanaently.

Could we add a feature to Alarmo where we disable some sensors temporarily?

### Additional info
Example:
Automation in HomeAssistant that is triggered by the robot starting cleaning and disables/ignores 2 motion sensors from ALARMO . Another automation that re-enables these sensores when the robot confirms to Homeassistant it has stopped / docked.

Avoids false triggers

**Comment by nielsfaber** [comment]
Alarmo doesn't have a service to enable/disable a sensor. 
IMO this is would be a security flaw, since such service could be used to disable all sensors -without providing any pincode- which would make the alarm useless.
Did you consider using the 'Custom' arming mode for this? I configured this mode exactly for the purpose of having the robot vacuum passing the house while we are away. The alarm is automatically switched from away to custom (and back) while the vacuum is cleaning.
