### ISSUE TITLE
Log an warning/error when: 'alarm doesn't get enabled due to open sensors'.

### ISSUE THREAD

**Issue by VNRARA** [nielsfaber/alarmo#986]
I believe that in Alarmo should log a system warning/error when alarm doesn't get enabled due to open sensors that would make debugging automations a lot easier. This regardless of the GUI settings/automations.

**Comment by andyb2000** [comment]
Hi,
Yes I agree with this. At the moment if a sensor is in open state and you try to arm, the system silently just doesn't do anything.
It would be ideal if it could log/alert/event trigger so we can catch this and report/alert the user as otherwise they may just press "ARM" and walk away without realising.

**Comment by VNRARA** [comment]
To add; some users may choose NOT to enable the Alarmo notification for this and later end up not realising canceling an arm-action is possible. They'd only see the alarm not turning on thinking it's a bug.

**Comment by VNRARA** [comment]
Maybe this issue should be converted to a discussion?

**Comment by VNRARA** [comment]
No don't close please

**Comment by uELKO** [comment]
This is a huge point for me. I thought alarmo had a bug over the last few weeks because sometimes it didn't got into 'armed' state. It was an opened window...wow. We live in the 3rd floor so after taking a shower we usually leave the window open.
So in my opinion alarmo should only trigger on changes for initially open sensors at the time of arming!
Otherwise, I love this integration. Greetings.

**Comment by nielsfaber** [comment]
Alarmo publishes many information via the HA logs. 
However, the information is printed as informative (logging level info), not as warning or error.
I changed the logging level for triggering of the alarm and failure to arm to warning (https://github.com/nielsfaber/alarmo/commit/4da65343a6865a6b24b296d09462a24bccf77786), hope this helps and fulfills the request.

@andyb2000 
> At the moment if a sensor is in open state and you try to arm, the system silently just doesn't do anything.

This is not true. However, the user needs to configure how he wants to be informed.
Alarmo publishes events for any state change of the alarm, provides built-in support for configuring notifications and comes with a dedicated alarmo-card for visualization. Am I missing something?
